# Generated by Django 5.2.14 on 2026-09-20 14:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0041_productvideo_youtube_video_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Higher priority wins when multiple rules match.')),
                ('brand_match', models.CharField(blank=True, help_text='Optional case-insensitive brand name selector.', max_length=120)),
                ('category_match', models.CharField(blank=True, help_text='Optional case-insensitive category/slug selector.', max_length=160)),
                ('product_identifier_match', models.CharField(blank=True, help_text='Optional SKU/model/name selector for one product or product family.', max_length=160)),
                ('fixed_markup', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percentage_markup', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Example: 12.5 means +12.5%.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('rounding_mode', models.CharField(choices=[('none', 'No rounding'), ('100', 'Nearest 100'), ('500', 'Nearest 500'), ('1000', 'Nearest 1,000')], default='none', max_length=10)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('extraction_mode', models.CharField(choices=[('generic', 'Generic structured-page extractor'), ('adapter', 'Dedicated website adapter'), ('api', 'Official/API connector')], default='generic', max_length=20)),
                ('default_currency', models.CharField(default='NGN', max_length=3)),
                ('adapter_key', models.CharField(blank=True, help_text='Registry key for a dedicated adapter when extraction_mode=adapter.', max_length=120)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Source-specific options. Do not store secrets here.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_mode', models.CharField(choices=[('urls', 'Product URLs'), ('names', 'Product names / model numbers'), ('mixed', 'Mixed URLs and product names')], default='mixed', max_length=20)),
                ('original_input', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('analysing', 'Analysing'), ('review', 'Ready for review'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('max_images', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('verify_against_manufacturer', models.BooleanField(default=True)),
                ('generate_or_prepare_images', models.BooleanField(default=True)),
                ('reject_watermarked_images', models.BooleanField(default=True)),
                ('remove_source_identity', models.BooleanField(default=True)),
                ('require_human_approval', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_batches', to=settings.AUTH_USER_MODEL)),
                ('pricing_rule', models.ForeignKey(blank=True, help_text='Optional explicit rule. Otherwise the pricing engine selects the best match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='catalog_imports.importpricingrule')),
                ('source', models.ForeignKey(blank=True, help_text='Leave blank to auto-detect sources per item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='catalog_imports.importsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_value', models.TextField(help_text='Original URL, product name, model number, or identifier supplied by the admin.')),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('extracting', 'Extracting'), ('normalized', 'Normalized'), ('verifying', 'Verifying'), ('ready', 'Ready for review'), ('blocked', 'Blocked by quality checks'), ('imported', 'Imported'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('verification_report', models.JSONField(blank=True, default=dict)),
                ('contamination_report', models.JSONField(blank=True, default=dict)),
                ('image_report', models.JSONField(blank=True, default=dict)),
                ('duplicate_report', models.JSONField(blank=True, default=dict)),
                ('source_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source_currency', models.CharField(blank=True, max_length=3)),
                ('calculated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog_imports.importbatch')),
                ('created_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_items', to='products.product')),
                ('pricing_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog_imports.importpricingrule')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog_imports.importsource')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ImportAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='catalog_imports.importitem')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='importpricingrule',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='catalog_imports.importsource'),
        ),
        migrations.AddIndex(
            model_name='importitem',
            index=models.Index(fields=['batch', 'status'], name='catalog_imp_batch_i_e26b33_idx'),
        ),
        migrations.AddIndex(
            model_name='importitem',
            index=models.Index(fields=['source', 'source_external_id'], name='catalog_imp_source__5a0da3_idx'),
        ),
    ]
