# Generated by Django 5.2.14 on 2026-09-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandVerificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=160)),
                ('official_domain', models.CharField(blank=True, help_text='Official manufacturer domain, e.g. logitech.com.', max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Optional brand aliases/model-family tokens used for conservative matching.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
        migrations.AddField(
            model_name='importitem',
            name='hold_reason',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='importitem',
            name='identity_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='importitem',
            name='manual_price_evidence_url',
            field=models.URLField(blank=True, help_text='URL where the manually entered current source price was verified.', max_length=1000),
        ),
        migrations.AddField(
            model_name='importitem',
            name='manual_verified_source_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional price manually verified by an admin when the retailer page cannot be fetched. Requires a price evidence URL before it is accepted.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='importitem',
            name='manufacturer_url',
            field=models.URLField(blank=True, help_text='Optional official manufacturer product URL used as authoritative identity/spec evidence. It never replaces the retailer price.', max_length=1000),
        ),
        migrations.AddField(
            model_name='importitem',
            name='price_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='importitem',
            name='secondary_evidence_urls',
            field=models.TextField(blank=True, help_text='Optional one evidence URL per line. Used only as supporting evidence.'),
        ),
        migrations.AddField(
            model_name='importitem',
            name='specifications_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ImportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('retailer', 'Retailer/source evidence'), ('manufacturer', 'Official manufacturer evidence'), ('secondary', 'Secondary supporting evidence'), ('manual_price', 'Manual price evidence')], db_index=True, max_length=20)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('source_name', models.CharField(blank=True, max_length=160)),
                ('is_authoritative', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('fetched', 'Fetched'), ('blocked', 'Blocked'), ('failed', 'Failed'), ('manual', 'Manually verified')], db_index=True, default='queued', max_length=20)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('extracted_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='catalog_imports.importitem')),
            ],
            options={
                'ordering': ['role', 'id'],
                'indexes': [models.Index(fields=['item', 'role', 'status'], name='catalog_imp_item_id_67e67b_idx')],
            },
        ),
    ]
