# Generated by Django 5.2.14 on 2026-09-20 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_imports', '0002_brandverificationprofile_importitem_hold_reason_and_more'),
        ('products', '0041_productvideo_youtube_video_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='default_brand',
            field=models.ForeignKey(blank=True, help_text='Optional destination brand override. Exact existing-brand matching is attempted when blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_default_batches', to='products.brand'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='default_category',
            field=models.ForeignKey(blank=True, help_text='Optional default destination category for this batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_default_batches', to='products.category'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='target_vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor that will own newly prepared Arolana product drafts.', limit_choices_to={'user_type': 'vendor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_destination_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importitem',
            name='draft_preparation_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importitem',
            name='draft_prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importitem',
            name='existing_product_match',
            field=models.ForeignKey(blank=True, help_text='Exact/strong existing-product match detected before draft creation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_duplicate_matches', to='products.product'),
        ),
        migrations.AddField(
            model_name='importitem',
            name='media_plan_prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importitem',
            name='target_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_destination_items', to='products.brand'),
        ),
        migrations.AddField(
            model_name='importitem',
            name='target_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_destination_items', to='products.category'),
        ),
        migrations.AddField(
            model_name='importitem',
            name='target_vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'vendor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_destination_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importitem',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('extracting', 'Extracting'), ('normalized', 'Normalized'), ('verifying', 'Verifying'), ('ready', 'Ready for review'), ('draft_created', 'Arolana draft created'), ('blocked', 'Blocked by quality checks'), ('imported', 'Imported'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20),
        ),
        migrations.CreateModel(
            name='ImportCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_category_match', models.CharField(blank=True, max_length=180)),
                ('source_subcategory_match', models.CharField(blank=True, max_length=180)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_mappings', to='catalog_imports.importsource')),
                ('target_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_import_mappings', to='products.category')),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImportMediaCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('reference', 'Reference only'), ('generation', 'Generation job'), ('owned_upload', 'Arolana-owned upload'), ('prepared', 'Prepared/generated result')], db_index=True, max_length=30)),
                ('view_role', models.CharField(blank=True, choices=[('main', 'Main / hero'), ('front', 'Front'), ('left_angle', 'Left angle'), ('right_angle', 'Right angle'), ('side', 'Side'), ('back', 'Back'), ('top_detail', 'Top / detail'), ('ports_detail', 'Ports / controls detail'), ('package_contents', 'Package / contents'), ('lifestyle', 'Lifestyle'), ('closeup', 'Close-up')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('planned', 'Planned / waiting for image provider'), ('reference', 'Reference only'), ('ready_review', 'Ready for review'), ('approved', 'Approved for product'), ('rejected', 'Rejected')], db_index=True, default='planned', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('source_url', models.URLField(blank=True, max_length=1500)),
                ('asset_storage_alias', models.CharField(blank=True, help_text='Django storage alias containing an approved review-stage asset.', max_length=80)),
                ('asset_storage_name', models.CharField(blank=True, help_text='Storage object/key for an approved review-stage asset. Not a public URL.', max_length=1000)),
                ('asset_original_name', models.CharField(blank=True, help_text='Original/generated filename used only to preserve the file extension.', max_length=255)),
                ('reference_urls', models.JSONField(blank=True, default=list)),
                ('generation_prompt', models.TextField(blank=True)),
                ('provider_key', models.CharField(blank=True, max_length=80)),
                ('provider_asset_id', models.CharField(blank=True, max_length=255)),
                ('exact_identity_required', models.BooleanField(default=True)),
                ('exact_identity_verified', models.BooleanField(default=False)),
                ('watermark_status', models.CharField(choices=[('unknown', 'Not checked'), ('clear', 'No watermark detected'), ('detected', 'Watermark detected')], default='unknown', max_length=20)),
                ('rights_status', models.CharField(choices=[('unknown', 'Not confirmed'), ('confirmed', 'Usage rights confirmed'), ('rejected', 'Do not use')], default='unknown', max_length=20)),
                ('selected_for_product', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('attached_product_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_import_media_candidates', to='products.productimage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_candidates', to='catalog_imports.importitem')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['item', 'kind', 'status'], name='catalog_imp_item_id_504932_idx')],
            },
        ),
    ]
