# Generated by Django 5.2.14 on 2026-09-20 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_imports', '0003_importbatch_default_brand_and_more'),
        ('products', '0041_productvideo_youtube_video_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importmediacandidate',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_catalog_import_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='attached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='generation_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_catalog_import_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='source_identity_check_passed',
            field=models.BooleanField(default=False, help_text='Human confirmed no retailer/source identity, watermark-like source branding, or copied seller overlay is present.'),
        ),
        migrations.AddField(
            model_name='importmediacandidate',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importmediacandidate',
            name='asset_original_name',
            field=models.CharField(blank=True, help_text='Generated filename used to preserve the extension.', max_length=255),
        ),
        migrations.AlterField(
            model_name='importmediacandidate',
            name='asset_storage_alias',
            field=models.CharField(blank=True, help_text='Django storage alias containing a review-stage asset.', max_length=80),
        ),
        migrations.AlterField(
            model_name='importmediacandidate',
            name='asset_storage_name',
            field=models.CharField(blank=True, help_text='Storage object/key for a review-stage asset. Not a public URL.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='importmediacandidate',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned / waiting for image provider'), ('generating', 'Generating'), ('reference', 'Reference only'), ('ready_review', 'Ready for review'), ('approved', 'Approved for product'), ('rejected', 'Rejected'), ('attached', 'Attached to product'), ('failed', 'Generation failed')], db_index=True, default='planned', max_length=30),
        ),
        migrations.AddIndex(
            model_name='importmediacandidate',
            index=models.Index(fields=['item', 'sha256'], name='catalog_imp_item_id_adf5d0_idx'),
        ),
    ]
