# Generated by Django 6.0.4 on 2026-05-03 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('local', 'Local File'), ('embed', 'Embed Code'), ('streaming', 'Streaming URL')], default='youtube', max_length=20)),
                ('youtube_id', models.CharField(blank=True, help_text='YouTube video ID or URL', max_length=100)),
                ('vimeo_id', models.CharField(blank=True, help_text='Vimeo video ID or URL', max_length=100)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/')),
                ('embed_code', models.TextField(blank=True, help_text='Custom embed code')),
                ('streaming_url', models.URLField(blank=True, help_text='HLS or MP4 streaming URL')),
                ('custom_thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/%Y/%m/')),
                ('auto_thumbnail', models.URLField(blank=True, help_text='Auto-fetched thumbnail')),
                ('autoplay', models.BooleanField(default=False)),
                ('loop', models.BooleanField(default=False)),
                ('muted', models.BooleanField(default=False)),
                ('controls', models.BooleanField(default=True)),
                ('start_time', models.IntegerField(default=0, help_text='Start time in seconds')),
                ('end_time', models.IntegerField(blank=True, help_text='End time in seconds', null=True)),
                ('preferred_quality', models.CharField(choices=[('auto', 'Auto'), ('2160p', '4K'), ('1440p', '2K'), ('1080p', 'Full HD'), ('720p', 'HD'), ('480p', 'SD')], default='auto', max_length=10)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='videos/galleries/')),
                ('is_active', models.BooleanField(default=True)),
                ('videos', models.ManyToManyField(related_name='galleries', to='videos.video')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('play', 'Play'), ('pause', 'Pause'), ('complete', 'Complete'), ('seek', 'Seek')], max_length=50)),
                ('watch_time', models.IntegerField(default=0, help_text='Watch time in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='videos.video')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['video', 'timestamp'], name='videos_vide_video_i_c7da52_idx')],
            },
        ),
    ]
