# Generated by Django 6.0.4 on 2026-05-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Summer Mega Sale!', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='Get up to 50% off on selected items + Free Shipping', max_length=500)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_url', models.CharField(default='/products/?deals=true', max_length=500)),
                ('background_color_start', models.CharField(default='#3B82F6', help_text='Start color (e.g., #3B82F6)', max_length=7)),
                ('background_color_end', models.CharField(default='#9333EA', help_text='End color (e.g., #9333EA)', max_length=7)),
                ('image', models.ImageField(blank=True, help_text='Optional background image', null=True, upload_to='promo/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Promo Banner',
                'verbose_name_plural': 'Promo Banners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site_name', models.CharField(default='Arolana', max_length=100)),
                ('site_tagline', models.CharField(blank=True, default='Premium Multi-Vendor Marketplace', max_length=200)),
                ('site_description', models.TextField(blank=True, help_text='SEO description for the site')),
                ('site_keywords', models.CharField(blank=True, help_text='SEO keywords, comma separated', max_length=500)),
                ('site_logo', models.ImageField(blank=True, help_text='Main logo (recommended size: 200x60)', null=True, upload_to='settings/')),
                ('site_favicon', models.ImageField(blank=True, help_text='Browser favicon (recommended size: 32x32)', null=True, upload_to='settings/')),
                ('footer_logo', models.ImageField(blank=True, help_text='Footer logo', null=True, upload_to='settings/')),
                ('contact_email', models.EmailField(default='contact@arolana.com', max_length=254)),
                ('contact_phone', models.CharField(default='1-800-AROLANA', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Primary brand color', max_length=7)),
                ('secondary_color', models.CharField(default='#10B981', help_text='Secondary brand color', max_length=7)),
                ('footer_copyright', models.CharField(default='© 2024 Arolana.com. All rights reserved.', max_length=200)),
                ('shipping_note', models.CharField(blank=True, default='Free shipping on orders over $50', max_length=200)),
                ('return_policy', models.CharField(blank=True, default='30-day easy returns', max_length=200)),
                ('warranty_note', models.CharField(blank=True, default='2-year warranty on all products', max_length=200)),
                ('meta_author', models.CharField(blank=True, max_length=100)),
                ('meta_robots', models.CharField(blank=True, default='index, follow', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
