# Generated by Django 5.2.14 on 2026-05-16 20:17

import django.core.validators
from django.db import migrations, models


def create_default_admin_appearance(apps, schema_editor):
    AdminAppearance = apps.get_model('core', 'AdminAppearance')
    AdminAppearance.objects.get_or_create(name='Default Admin Theme')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(default='Default Admin Theme', max_length=100)),
                ('page_background_color', models.CharField(default='#F6F8FB', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #F8FAFC.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('content_background_color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #F8FAFC.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('card_background_color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #F8FAFC.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('text_color', models.CharField(default='#111827', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #F8FAFC.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('muted_text_color', models.CharField(default='#667085', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #F8FAFC.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('primary_color', models.CharField(default='#2563EB', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #F8FAFC.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('accent_color', models.CharField(default='#0F766E', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #F8FAFC.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('hero_start_color', models.CharField(default='#111827', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #F8FAFC.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('hero_end_color', models.CharField(default='#0F766E', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #F8FAFC.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('navbar_background_color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #F8FAFC.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('navbar_text_color', models.CharField(default='#111827', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #F8FAFC.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('sidebar_background_color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #F8FAFC.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('sidebar_text_color', models.CharField(default='#1F2937', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #F8FAFC.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
            ],
            options={
                'verbose_name': 'Admin Appearance',
                'verbose_name_plural': 'Admin Appearance',
            },
        ),
        migrations.RunPython(create_default_admin_appearance, migrations.RunPython.noop),
    ]
