# Generated by Django 5.2.14 on 2026-05-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adminappearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo_height',
            field=models.PositiveIntegerField(default=76, help_text='Footer logo height in pixels'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_height_desktop',
            field=models.PositiveIntegerField(default=88, help_text='Storefront logo height on desktop in pixels'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_height_mobile',
            field=models.PositiveIntegerField(default=58, help_text='Storefront logo height on mobile/tablet in pixels'),
        ),
    ]
