# Generated by Django 5.2.14 on 2026-06-09 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_smart_chat_bot_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(default='Homepage Background Settings', max_length=120)),
                ('desktop_background_image', models.ImageField(blank=True, help_text='Desktop homepage background. Recommended: 1920×1080 WebP.', null=True, upload_to='homepage/backgrounds/desktop/')),
                ('mobile_background_image', models.ImageField(blank=True, help_text='Mobile homepage background. Recommended: 1080×1350 WebP or 1080×1920 WebP.', null=True, upload_to='homepage/backgrounds/mobile/')),
                ('desktop_overlay_opacity', models.DecimalField(decimal_places=2, default=0.35, help_text='Desktop overlay opacity. 0.15 = clear image, 0.35 = balanced, 0.70 = muted.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('mobile_overlay_opacity', models.DecimalField(decimal_places=2, default=0.5, help_text='Mobile overlay opacity. Mobile usually needs stronger overlay for readability.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('desktop_position', models.CharField(default='center center', help_text='Desktop CSS background position. Example: center center, top center, center right.', max_length=50)),
                ('mobile_position', models.CharField(default='center center', help_text='Mobile CSS background position. Example: center center, top center, center right.', max_length=50)),
                ('blur_background', models.BooleanField(default=False, help_text='Softly blur the homepage background image.')),
                ('fixed_background', models.BooleanField(default=True, help_text='Keep desktop background fixed while scrolling. Mobile uses scroll for performance.')),
                ('make_sections_glass', models.BooleanField(default=True, help_text='Make homepage cards and white sections slightly transparent so the background shows nicely.')),
            ],
            options={
                'verbose_name': 'Homepage Appearance',
                'verbose_name_plural': 'Homepage Appearance',
            },
        ),
    ]
