# Generated by Django 5.2.14 on 2026-06-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homepageappearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cart_whatsapp_message',
            field=models.TextField(blank=True, default='Hello Arolana Support, I am contacting you from the cart page.\n\nI need help with my cart, checkout, delivery, payment, or order support before completing my purchase.', help_text='First WhatsApp message customers send when contacting support from the cart page.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_whatsapp_number',
            field=models.CharField(blank=True, default='2349132924620', help_text='Arolana admin/support WhatsApp number. Use international format, for example: 2349132924620.', max_length=40),
        ),
    ]
