# Generated by Django 5.2.14 on 2026-06-29 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_sitesettings_cart_whatsapp_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('field_name', models.CharField(db_index=True, max_length=100)),
                ('file_name', models.CharField(db_index=True, max_length=500)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('perceptual_hash', models.CharField(blank=True, db_index=True, max_length=32)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_duplicate', models.BooleanField(db_index=True, default=False)),
                ('allow_duplicate', models.BooleanField(default=False, help_text='Admin override for legitimate shared manufacturer/product images.')),
                ('duplicate_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_assets', to='core.protectedimageasset')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_protected_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protected Image Asset',
                'verbose_name_plural': 'Protected Image Assets',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_protec_content_3e7e17_idx'), models.Index(fields=['sha256', 'is_duplicate'], name='core_protec_sha256_275975_idx'), models.Index(fields=['perceptual_hash', 'is_duplicate'], name='core_protec_percept_5aceec_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'field_name', 'file_name'), name='unique_protected_image_asset')],
            },
        ),
    ]
