# Generated by Django 5.2.14 on 2026-06-29 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_protectedimageasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('translation_key', models.CharField(blank=True, db_index=True, help_text='Use for shared labels, for example product.condition.brand_new.', max_length=255)),
                ('language_code', models.CharField(db_index=True, help_text='BCP-47 language code, for example yo, ig, ha, fr, or es.', max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Model field being translated, for example name, description, or specifications.', max_length=100)),
                ('translated_text', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arolana_content_translations', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content Translation',
                'verbose_name_plural': 'Content Translations',
                'ordering': ('content_type', 'object_id', 'field_name', 'language_code'),
                'indexes': [models.Index(fields=['content_type', 'object_id', 'language_code'], name='core_conten_content_adec2e_idx'), models.Index(fields=['translation_key', 'language_code', 'is_active'], name='core_conten_transla_fd7045_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('content_type__isnull', False), ('object_id__isnull', False)), fields=('content_type', 'object_id', 'language_code', 'field_name'), name='unique_content_field_translation'), models.UniqueConstraint(condition=models.Q(('translation_key', ''), _negated=True), fields=('translation_key', 'language_code'), name='unique_system_key_translation')],
            },
        ),
    ]
