# Generated by Django 5.2.14 on 2026-07-01 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_protected_image_duplicate_policy'),
        ('vendors', '0015_vendorprofile_business_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(blank=True, max_length=220)),
                ('message', models.TextField()),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('product_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('admin_review', 'Admin Review'), ('sent_to_vendor', 'Sent to Vendor'), ('vendor_replied', 'Vendor Replied'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=30)),
                ('admin_notes', models.TextField(blank=True)),
                ('vendor_response', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_quote_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Vendor Quote Request',
                'verbose_name_plural': 'Vendor Quote Requests',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['vendor', 'status'], name='core_vendor_vendor__e9380b_idx'), models.Index(fields=['customer', 'created_at'], name='core_vendor_custome_8f143f_idx'), models.Index(fields=['status', 'created_at'], name='core_vendor_status_3c8c19_idx')],
            },
        ),
    ]
