# Generated by Django 5.2.14 on 2026-07-01 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vendorquoterequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorquoterequest',
            name='admin_customer_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='admin_last_followed_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vendor_quote_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='customer_last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='email_notification_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='internal_resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='is_admin_intervention_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='sent_to_vendor_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='vendor_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorquoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('admin_review', 'Admin Review'), ('sent_to_vendor', 'Sent to Vendor'), ('vendor_replied', 'Vendor Replied'), ('admin_follow_up', 'Admin Follow-up'), ('customer_updated', 'Customer Updated'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=30),
        ),
        migrations.CreateModel(
            name='VendorQuoteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_admin_message', models.BooleanField(default=False)),
                ('is_vendor_message', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_messages', to='core.vendorquoterequest')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_vendor_quote_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_vendor_quote_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['quote_request', 'created_at'], name='core_vendor_quote_r_b9729f_idx'), models.Index(fields=['recipient', 'is_read'], name='core_vendor_recipie_28be37_idx')],
            },
        ),
    ]
