# Generated by Django 5.2.14 on 2026-07-01 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_quote_message_roles(apps, schema_editor):
    VendorQuoteMessage = apps.get_model("core", "VendorQuoteMessage")
    VendorQuoteMessage.objects.filter(is_admin_message=True).update(sender_role="admin")
    VendorQuoteMessage.objects.filter(is_vendor_message=True).update(
        sender_role="vendor",
        is_customer_visible=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_vendorquoterequest_admin_customer_response_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorquotemessage',
            name='is_customer_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorquotemessage',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorquotemessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorquotemessage',
            name='sender_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('customer', 'Customer'), ('system', 'System')], db_index=True, default='system', max_length=16),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='admin_vendor_message',
            field=models.TextField(blank=True, help_text='Send a new message to the vendor. This field is cleared after delivery.', verbose_name='Message to vendor'),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='escalation_status',
            field=models.CharField(choices=[('none', 'None'), ('delayed', 'Vendor Delayed'), ('admin_followup', 'Admin Follow-up'), ('admin_resolved', 'Admin Resolved')], db_index=True, default='none', max_length=24),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='last_customer_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='last_vendor_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorquoterequest',
            name='vendor_response_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorquotemessage',
            name='quote_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.vendorquoterequest'),
        ),
        migrations.AlterField(
            model_name='vendorquotemessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_vendor_quote_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorquoterequest',
            name='admin_customer_response',
            field=models.TextField(blank=True, verbose_name='Message to customer'),
        ),
        migrations.AlterField(
            model_name='vendorquoterequest',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Internal admin notes'),
        ),
        migrations.AlterField(
            model_name='vendorquoterequest',
            name='internal_resolution_notes',
            field=models.TextField(blank=True, verbose_name='Internal resolution notes'),
        ),
        migrations.AlterField(
            model_name='vendorquoterequest',
            name='vendor_response',
            field=models.TextField(blank=True, verbose_name='Latest vendor response'),
        ),
        migrations.RunPython(backfill_quote_message_roles, migrations.RunPython.noop),
    ]
