# Generated by Django 5.2.14 on 2026-07-09 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_vendorquotemessage_is_customer_visible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMediaAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(blank=True, db_index=True, help_text='Private media authorization rule used for the request.', max_length=120)),
                ('scope', models.CharField(blank=True, db_index=True, help_text='Security scope such as kyc, payment, chat, delivery, or hr.', max_length=50)),
                ('model_label', models.CharField(blank=True, db_index=True, help_text='Django model that owns the protected media resource.', max_length=150)),
                ('object_id', models.CharField(blank=True, db_index=True, help_text='Primary key of the database object that owns the file.', max_length=100)),
                ('decision', models.CharField(choices=[('allowed', 'Allowed'), ('denied', 'Denied')], db_index=True, max_length=20)),
                ('reason', models.CharField(blank=True, db_index=True, help_text='Authorization reason such as owner_or_participant, role_or_permission, matching_session, or not_authorized.', max_length=100)),
                ('path_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of the private storage path. The raw sensitive path is intentionally not stored.', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=700)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='Cloudflare, Railway, or application request identifier.', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_media_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Media Access Log',
                'verbose_name_plural': 'Private Media Access Logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['decision', '-created_at'], name='pmedia_decision_time_idx'), models.Index(fields=['rule_key', '-created_at'], name='pmedia_rule_time_idx'), models.Index(fields=['user', '-created_at'], name='pmedia_user_time_idx'), models.Index(fields=['model_label', 'object_id'], name='pmedia_resource_idx')],
            },
        ),
    ]
