# Generated by Django 6.0.4 on 2026-05-03 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=20)),
                ('is_base', models.BooleanField(default=False, help_text='Base currency for conversions')),
                ('is_active', models.BooleanField(default=True)),
                ('symbol_position', models.CharField(choices=[('left', 'Left (e.g., $100)'), ('right', 'Right (e.g., 100$)'), ('space_left', 'Space Left (e.g., $ 100)'), ('space_right', 'Space Right (e.g., 100 $)')], default='left', max_length=20)),
                ('decimal_places', models.IntegerField(default=2)),
                ('thousands_separator', models.CharField(default=',', max_length=1)),
                ('decimal_separator', models.CharField(default='.', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CountryCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(max_length=2, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='currency.currency')),
            ],
            options={
                'verbose_name_plural': 'Country Currencies',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyConversionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('converted_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('session_id', models.CharField(blank=True, max_length=200)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='currency.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='currency.currency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
