# Generated by Django 5.2.14 on 2026-05-18 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(help_text='Example: USDT TRC20, USDT ERC20, BTC, ETH', max_length=80)),
                ('currency', models.CharField(default='USDT', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='crypto_wallet_qr/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'network'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, editable=False, max_length=80, unique=True)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('gateway', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paypal', 'PayPal'), ('stripe', 'Stripe / Card'), ('coinbase', 'Coinbase Commerce Crypto'), ('manual_crypto', 'Manual Crypto Wallet Transfer')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('review', 'Manual Review'), ('refunded', 'Refunded')], default='pending', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=180)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, max_length=220)),
                ('gateway_checkout_url', models.URLField(blank=True, max_length=1000)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('manual_wallet_network', models.CharField(blank=True, max_length=80)),
                ('manual_wallet_address', models.CharField(blank=True, max_length=255)),
                ('manual_sender_wallet', models.CharField(blank=True, max_length=255)),
                ('manual_tx_hash', models.CharField(blank=True, max_length=255)),
                ('manual_proof', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('manual_note', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arolana_payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gateway', 'status'], name='arolana_pay_gateway_194c26_idx'), models.Index(fields=['order_id', 'status'], name='arolana_pay_order_i_47735d_idx')],
            },
        ),
    ]
