# Generated by Django 5.2.14 on 2026-05-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arolana_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paypal', 'PayPal'), ('stripe', 'Stripe / Card'), ('coinbase', 'Coinbase Commerce Crypto'), ('manual_crypto', 'Manual Crypto Wallet Transfer')], max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=220)),
                ('icon_class', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'ordering': ['display_order', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
