# Generated by Django 5.2.14 on 2026-06-07 07:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arolana_payments', '0003_paystack_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_capture_id',
            field=models.CharField(blank=True, db_index=True, max_length=220),
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('paypal', 'PayPal'), ('paystack', 'Paystack'), ('coinbase', 'Coinbase Commerce Crypto'), ('manual_crypto', 'Manual Crypto Wallet Transfer')], default='paypal', max_length=30)),
                ('gateway_refund_id', models.CharField(db_index=True, max_length=220, unique=True)),
                ('gateway_capture_id', models.CharField(blank=True, db_index=True, max_length=220)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(db_index=True, default='completed', max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('refunded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='arolana_payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-refunded_at'],
                'indexes': [models.Index(fields=['gateway', 'status'], name='arolana_pay_gateway_29191c_idx'), models.Index(fields=['order_id', 'status'], name='arolana_pay_order_i_ad14a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayPalWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=180, unique=True)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=120)),
                ('resource_type', models.CharField(blank=True, max_length=80)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=220)),
                ('status', models.CharField(choices=[('received', 'Received'), ('verified', 'Verified'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('signature_verified', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paypal_webhook_logs', to='arolana_payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'PayPal Webhook Event',
                'verbose_name_plural': 'PayPal Webhook Events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type', 'status'], name='arolana_pay_event_t_9037e1_idx'), models.Index(fields=['resource_id', 'status'], name='arolana_pay_resourc_8e467d_idx')],
            },
        ),
    ]
