# Generated by Django 5.2.14 on 2026-07-10 05:57

import core.private_upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arolana_payments', '0004_paymenttransaction_gateway_capture_id_paymentrefund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='manual_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/', validators=[core.private_upload_validation.PrivateUploadValidator('payment_proof')]),
        ),
    ]
