# Generated by Django 5.2.14 on 2026-07-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arolana_payments', '0005_alter_paymenttransaction_manual_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='fulfillment_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='fulfillment_error',
            field=models.TextField(blank=True),
        ),
    ]
