# Generated by Django 5.2.14 on 2026-07-11 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arolana_payments', '0006_paymenttransaction_fulfilled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='manual_review_decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='manual_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='manual_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='manual_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_manual_crypto_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('manual_tx_hash', ''), _negated=True), fields=('manual_tx_hash',), name='uniq_payment_manual_tx_hash_nonblank'),
        ),
    ]
