# Generated by Django 5.2.14 on 2026-07-11 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arolana_payments', '0007_paymenttransaction_manual_review_decision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinbaseWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=180, unique=True)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coinbase_webhook_logs', to='arolana_payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
