# Generated by Django 5.2.14 on 2026-05-18 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_productvariant_color_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('ai', 'AI Active'), ('admin_requested', 'Admin Requested'), ('admin_active', 'Admin Active'), ('closed', 'Closed')], db_index=True, default='ai', max_length=30)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('customer_name', models.CharField(blank=True, max_length=160)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('selected_variants', models.JSONField(blank=True, default=dict)),
                ('page_url', models.URLField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('admin_requested_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_admin', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_smart_chat_conversations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_chat_conversations', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'Customer'), ('ai', 'AI Assistant'), ('admin', 'Admin'), ('system', 'System')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_private_note', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='smartchat.smartchatconversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='smartchatconversation',
            index=models.Index(fields=['status', '-last_message_at'], name='smartchat_s_status_4bf9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='smartchatconversation',
            index=models.Index(fields=['session_key', '-last_message_at'], name='smartchat_s_session_322ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='smartchatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='smartchat_s_convers_21b359_idx'),
        ),
        migrations.AddIndex(
            model_name='smartchatmessage',
            index=models.Index(fields=['sender_type', 'created_at'], name='smartchat_s_sender__ac6d11_idx'),
        ),
    ]
