# Generated by Django 5.2.14 on 2026-05-21 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_manufacturer_sku'),
        ('smartchat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartchatconversation',
            options={'ordering': ['-last_message_at'], 'verbose_name': 'Smart Chat Conversation', 'verbose_name_plural': 'Smart Chat Conversations'},
        ),
        migrations.AlterModelOptions(
            name='smartchatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Smart Chat Message', 'verbose_name_plural': 'Smart Chat Messages'},
        ),
        migrations.AddField(
            model_name='smartchatconversation',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='smartchatconversation',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='smartchatconversation',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='smartchatconversation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='smartchatconversation',
            name='page_url',
            field=models.URLField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='smartchatconversation',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Visitor session key for guests.', max_length=120),
        ),
        migrations.AlterField(
            model_name='smartchatconversation',
            name='title',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddIndex(
            model_name='smartchatconversation',
            index=models.Index(fields=['customer_email'], name='smartchat_s_custome_47008a_idx'),
        ),
        migrations.AddIndex(
            model_name='smartchatconversation',
            index=models.Index(fields=['created_at'], name='smartchat_s_created_c75c67_idx'),
        ),
        migrations.AddIndex(
            model_name='smartchatmessage',
            index=models.Index(fields=['conversation', 'id'], name='smartchat_s_convers_2976ed_idx'),
        ),
    ]
