# Generated by Django 5.2.14 on 2026-05-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartchat', '0002_alter_smartchatconversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartchatmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional customer/admin image attachment.', null=True, upload_to='smartchat/images/%Y/%m/'),
        ),
    ]
