# Generated by Django 5.2.14 on 2026-06-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartchat', '0004_ai_operations_assistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartchatmessage',
            name='sender_type',
            field=models.CharField(choices=[('user', 'Customer'), ('ai', 'Arolana Chat'), ('admin', 'Admin'), ('system', 'System')], db_index=True, max_length=20),
        ),
    ]
