# Generated by Django 5.2.14 on 2026-07-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartchat', '0008_seed_marketplace_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiknowledgebase',
            name='answer_type',
            field=models.CharField(choices=[('customer_answer', 'Customer answer'), ('internal_rule', 'Internal rule'), ('policy_rule', 'Policy rule'), ('catalog_lookup_rule', 'Catalog lookup rule'), ('recommendation_rule', 'Recommendation rule'), ('escalation_rule', 'Escalation rule')], db_index=True, default='customer_answer', max_length=40),
        ),
        migrations.AddField(
            model_name='ailearnedknowledge',
            name='answer_type',
            field=models.CharField(choices=[('customer_answer', 'Customer answer'), ('internal_rule', 'Internal rule'), ('policy_rule', 'Policy rule'), ('catalog_lookup_rule', 'Catalog lookup rule'), ('recommendation_rule', 'Recommendation rule'), ('escalation_rule', 'Escalation rule')], db_index=True, default='customer_answer', max_length=40),
        ),
        migrations.AddField(
            model_name='ailearnedknowledge',
            name='context_type',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ailearnedknowledge',
            name='context_value',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='ailearnedknowledge',
            name='knowledge_type',
            field=models.CharField(choices=[('standalone_question', 'Standalone question'), ('follow_up_context', 'Follow-up context'), ('recommendation_request', 'Recommendation request'), ('recommendation_decision', 'Recommendation decision'), ('product_availability', 'Product availability'), ('category_availability', 'Category availability'), ('brand_availability', 'Brand availability'), ('product_comparison', 'Product comparison'), ('product_specification', 'Product specification'), ('stock_question', 'Stock question'), ('price_question', 'Price question'), ('warranty_question', 'Warranty question'), ('order_support', 'Order support'), ('return_support', 'Return support'), ('vendor_question', 'Vendor question'), ('service_request', 'Service request'), ('human_handoff', 'Human handoff'), ('unclear', 'Unclear')], db_index=True, default='standalone_question', max_length=50),
        ),
        migrations.AddField(
            model_name='ailearnedknowledge',
            name='requires_live_catalog',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ailearnedknowledge',
            name='requires_previous_context',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='aitrainingdata',
            name='answer_type',
            field=models.CharField(choices=[('customer_answer', 'Customer answer'), ('internal_rule', 'Internal rule'), ('policy_rule', 'Policy rule'), ('catalog_lookup_rule', 'Catalog lookup rule'), ('recommendation_rule', 'Recommendation rule'), ('escalation_rule', 'Escalation rule')], db_index=True, default='customer_answer', max_length=40),
        ),
    ]
