# Generated by Django 5.2.14 on 2026-07-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartchat', '0009_aiknowledgebase_answer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiknowledgebase',
            name='answer_type',
            field=models.CharField(choices=[('customer_answer', 'Customer answer'), ('internal_rule', 'Internal rule'), ('policy_rule', 'Policy rule'), ('routing_rule', 'Routing rule'), ('catalog_lookup_rule', 'Catalog lookup rule'), ('recommendation_rule', 'Recommendation rule'), ('escalation_rule', 'Escalation rule')], db_index=True, default='customer_answer', max_length=40),
        ),
        migrations.AlterField(
            model_name='ailearnedknowledge',
            name='answer_type',
            field=models.CharField(choices=[('customer_answer', 'Customer answer'), ('internal_rule', 'Internal rule'), ('policy_rule', 'Policy rule'), ('routing_rule', 'Routing rule'), ('catalog_lookup_rule', 'Catalog lookup rule'), ('recommendation_rule', 'Recommendation rule'), ('escalation_rule', 'Escalation rule')], db_index=True, default='customer_answer', max_length=40),
        ),
        migrations.AlterField(
            model_name='aitrainingdata',
            name='answer_type',
            field=models.CharField(choices=[('customer_answer', 'Customer answer'), ('internal_rule', 'Internal rule'), ('policy_rule', 'Policy rule'), ('routing_rule', 'Routing rule'), ('catalog_lookup_rule', 'Catalog lookup rule'), ('recommendation_rule', 'Recommendation rule'), ('escalation_rule', 'Escalation rule')], db_index=True, default='customer_answer', max_length=40),
        ),
    ]
