# Generated by Django 5.2.14 on 2026-07-10 05:57

import core.private_upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartchat', '0010_alter_aiknowledgebase_answer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartchatmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional customer/admin image attachment.', null=True, upload_to='smartchat/images/%Y/%m/', validators=[core.private_upload_validation.PrivateUploadValidator('chat_image')]),
        ),
    ]
