# Generated by Django 5.2.14 on 2026-06-21 19:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('browser', models.CharField(blank=True, db_index=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, db_index=True, max_length=100)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('page_url', models.URLField(blank=True, db_index=True, max_length=1000)),
                ('path', models.CharField(blank=True, db_index=True, max_length=1000)),
                ('clicked_text', models.CharField(blank=True, db_index=True, max_length=500)),
                ('clicked_url', models.URLField(blank=True, db_index=True, max_length=1000)),
                ('element_tag', models.CharField(blank=True, max_length=50)),
                ('element_id', models.CharField(blank=True, max_length=200)),
                ('element_classes', models.CharField(blank=True, max_length=500)),
                ('event_type', models.CharField(choices=[('unknown', 'Unknown'), ('button', 'Button'), ('link', 'Link'), ('product', 'Product'), ('category', 'Category'), ('landing_cta', 'Landing Page CTA'), ('vendor', 'Vendor Link'), ('whatsapp', 'WhatsApp Link'), ('phone', 'Phone Link'), ('email', 'Email Link'), ('video', 'Video Button')], db_index=True, default='unknown', max_length=50)),
                ('product_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('category_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('vendor_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('landing_page_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Click Event',
                'verbose_name_plural': 'Click Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'country'], name='visitor_ana_created_1bb9ed_idx'), models.Index(fields=['created_at', 'device_type'], name='visitor_ana_created_b30b96_idx'), models.Index(fields=['created_at', 'browser'], name='visitor_ana_created_0b6dc6_idx'), models.Index(fields=['event_type', 'created_at'], name='visitor_ana_event_t_c5fea7_idx'), models.Index(fields=['clicked_url', 'created_at'], name='visitor_ana_clicked_9d433f_idx'), models.Index(fields=['clicked_text', 'created_at'], name='visitor_ana_clicked_345155_idx'), models.Index(fields=['session_key', 'created_at'], name='visitor_ana_session_6954cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('browser', models.CharField(blank=True, db_index=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, db_index=True, max_length=100)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('page_url', models.URLField(blank=True, db_index=True, max_length=1000)),
                ('path', models.CharField(blank=True, db_index=True, max_length=1000)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('method', models.CharField(blank=True, max_length=20)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Visit',
                'verbose_name_plural': 'Page Visits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'country'], name='visitor_ana_created_8b5fa3_idx'), models.Index(fields=['created_at', 'device_type'], name='visitor_ana_created_c54b1c_idx'), models.Index(fields=['created_at', 'browser'], name='visitor_ana_created_5310c9_idx'), models.Index(fields=['path', 'created_at'], name='visitor_ana_path_fc1cb7_idx'), models.Index(fields=['session_key', 'created_at'], name='visitor_ana_session_9a1e18_idx')],
            },
        ),
    ]
