# Generated by Django 5.2.14 on 2026-06-21 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='referrer_domain',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='traffic_source',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='utm_campaign',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='utm_content',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='utm_term',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='referrer_domain',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='traffic_source',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='utm_campaign',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='utm_content',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='utm_term',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['created_at', 'traffic_source'], name='visitor_ana_created_4b8bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['created_at', 'utm_source'], name='visitor_ana_created_d5b8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['created_at', 'utm_campaign'], name='visitor_ana_created_d42b51_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['created_at', 'referrer_domain'], name='visitor_ana_created_ff3cef_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['created_at', 'traffic_source'], name='visitor_ana_created_e74c7a_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['created_at', 'utm_source'], name='visitor_ana_created_9ce1ca_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['created_at', 'utm_campaign'], name='visitor_ana_created_032d40_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['created_at', 'referrer_domain'], name='visitor_ana_created_760a45_idx'),
        ),
    ]
