# Generated by Django 5.2.14 on 2026-08-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_analytics', '0002_clickevent_referrer_domain_clickevent_traffic_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='recommendation_algorithm',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='recommendation_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='recommendation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='recommendation_section',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clickevent',
            name='source_product_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='event_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('button', 'Button'), ('link', 'Link'), ('product', 'Product'), ('category', 'Category'), ('landing_cta', 'Landing Page CTA'), ('vendor', 'Vendor Link'), ('whatsapp', 'WhatsApp Link'), ('phone', 'Phone Link'), ('email', 'Email Link'), ('video', 'Video Button'), ('recommendation_impression', 'Recommendation Impression'), ('recommendation_click', 'Recommendation Click')], db_index=True, default='unknown', max_length=50),
        ),
    ]
