# Generated by Django 5.2.14 on 2026-05-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercampaign',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='recipient_scope',
            field=models.CharField(choices=[('subscribers', 'Active newsletter subscribers'), ('registered', 'Registered user emails'), ('all', 'Subscribers and registered users')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='send_frequency',
            field=models.CharField(choices=[('once', 'One time'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom schedule')], default='once', max_length=20),
        ),
    ]
