# Generated by Django 5.2.14 on 2026-05-15 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newslettercampaign_last_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAudienceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('registered', 'Registered user'), ('newsletter', 'Newsletter subscriber'), ('both', 'Registered and newsletter'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_promos', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audience_memberships', to='newsletter.newslettersubscriber')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_audience_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Audience Member',
                'verbose_name_plural': 'Email Audience',
                'ordering': ['email'],
            },
        ),
    ]
