# Generated by Django 5.2.14 on 2026-06-23 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_emailaudiencemember_opt_in_default'),
        ('products', '0020_categoryarticlelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercampaign',
            name='button_text',
            field=models.CharField(blank=True, default='Shop now', max_length=80),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='button_url',
            field=models.URLField(blank=True, help_text='Main CTA link. Example: product page, landing page, vendor page.'),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='campaign_type',
            field=models.CharField(choices=[('product_announcement', 'Product Announcement'), ('new_arrival', 'New Arrival'), ('promotion', 'Promotion'), ('marketplace_update', 'Marketplace Update'), ('vendor_update', 'Vendor Update'), ('launch_news', 'Launch News'), ('general', 'General Newsletter')], db_index=True, default='general', max_length=40),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='eyebrow',
            field=models.CharField(blank=True, help_text='Small label above headline. Example: New Product, Vendor Update, Launch News.', max_length=120),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='footer_note',
            field=models.TextField(blank=True, default='You are receiving this email because you subscribed to Arolana updates.'),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='headline',
            field=models.CharField(blank=True, help_text='Main email headline.', max_length=220),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Upload designed banner/hero image for the email.', null=True, upload_to='newsletter/campaigns/hero/'),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Optional external hero image URL. Used if no uploaded hero image is selected.'),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='preheader',
            field=models.CharField(blank=True, help_text='Short preview text shown by many email apps under the subject.', max_length=220),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Optional product image for the email.', null=True, upload_to='newsletter/campaigns/products/'),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='product_image_url',
            field=models.URLField(blank=True, help_text='Optional external product image URL.'),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='product_price_text',
            field=models.CharField(blank=True, help_text='Example: ₦989,550 or Contact for price.', max_length=80),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='product_title',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='related_product',
            field=models.ForeignKey(blank=True, help_text='Optional product connected to this newsletter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_campaigns', to='products.product'),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='secondary_button_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='secondary_button_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='subheadline',
            field=models.TextField(blank=True, help_text='Short supporting message under headline.'),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='test_email',
            field=models.EmailField(blank=True, help_text='Email address to receive test campaign before sending to all subscribers.', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailaudiencemember',
            name='accepts_promos',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='emailaudiencemember',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='emailaudiencemember',
            name='source',
            field=models.CharField(choices=[('registered', 'Registered user'), ('newsletter', 'Newsletter subscriber'), ('both', 'Registered and newsletter'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='content',
            field=models.TextField(help_text='Plain text email body/fallback content.'),
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='html_content',
            field=models.TextField(blank=True, help_text='Optional custom HTML. If filled, it can be used as extra body content inside the designed template.'),
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='recipient_scope',
            field=models.CharField(choices=[('subscribers', 'Active newsletter subscribers'), ('registered', 'Registered user emails'), ('all', 'Subscribers and registered users')], db_index=True, default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User preferences for newsletters.'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='source',
            field=models.CharField(choices=[('homepage', 'Homepage'), ('blog', 'Blog'), ('footer', 'Footer'), ('checkout', 'Checkout'), ('registration', 'Registration'), ('google', 'Google Signup'), ('facebook', 'Facebook Signup'), ('api', 'API'), ('manual', 'Manual'), ('other', 'Other')], db_index=True, default='homepage', max_length=50),
        ),
        migrations.AddIndex(
            model_name='newslettercampaign',
            index=models.Index(fields=['status', '-created_at'], name='newsletter__status_3fee50_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettercampaign',
            index=models.Index(fields=['campaign_type', '-created_at'], name='newsletter__campaig_94ed9c_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettercampaign',
            index=models.Index(fields=['recipient_scope', '-created_at'], name='newsletter__recipie_01cbf6_idx'),
        ),
    ]
