# Generated by Django 5.2.14 on 2026-06-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_newslettercampaign_button_text_and_more'),
        ('products', '0020_categoryarticlelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercampaign',
            name='hero_only',
            field=models.BooleanField(default=False, help_text='Turn this on when you want the email to be one big designed promotional image. Best for luxury product campaigns, launch banners, and image-led ads.'),
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Optional external hero image URL. Must be a direct image URL ending in .webp, .jpg, .jpeg, .png, .gif, or .svg. Leave empty if using uploaded image.'),
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='html_content',
            field=models.TextField(blank=True, help_text='Optional custom HTML. Used as extra body content inside the designed template.'),
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='product_image_url',
            field=models.URLField(blank=True, help_text='Optional external product image URL. Must be a direct image URL ending in .webp, .jpg, .jpeg, .png, .gif, or .svg. Do not put product page links here.'),
        ),
        migrations.AddIndex(
            model_name='newslettercampaign',
            index=models.Index(fields=['hero_only', '-created_at'], name='newsletter__hero_on_932ad0_idx'),
        ),
    ]
