# Generated by Django 5.2.14 on 2026-05-24 03:33

from django.db import migrations, models


def seed_contact_defaults(apps, schema_editor):
    ContactPageSettings = apps.get_model('pages', 'ContactPageSettings')
    ContactQuickAction = apps.get_model('pages', 'ContactQuickAction')

    ContactPageSettings.objects.get_or_create(
        title='Arolana Contact Settings',
        defaults={
            'support_email': 'contact@arolana.com',
            'support_phone': '+2349132924620',
            'coverage_text': 'Nigeria, Africa, and global marketplace support',
            'protection_title': 'Marketplace Protection',
            'protection_text': 'For order issues, include your order number, delivery tracking code, vendor name, and screenshots where possible.',
            'is_active': True,
        },
    )

    for order, label, url in [
        (10, 'Track Order', '/orders/track/'),
        (20, 'Help Center', '/help/'),
        (30, 'Returns', '/returns/'),
        (40, 'FAQs', '/faq/'),
    ]:
        ContactQuickAction.objects.get_or_create(
            label=label,
            defaults={'url': url, 'order': order, 'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Arolana Contact Settings', max_length=120)),
                ('support_email', models.EmailField(default='contact@arolana.com', max_length=254)),
                ('support_phone', models.CharField(default='+2349132924620', max_length=50)),
                ('coverage_text', models.CharField(default='Nigeria, Africa, and global marketplace support', max_length=255)),
                ('protection_title', models.CharField(default='Marketplace Protection', max_length=120)),
                ('protection_text', models.TextField(default='For order issues, include your order number, delivery tracking code, vendor name, and screenshots where possible.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Page Setting',
                'verbose_name_plural': 'Contact Page Settings',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactQuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(help_text='Use a path like /help/ or a full URL.', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.RunPython(seed_contact_defaults, migrations.RunPython.noop),
    ]
