# Generated by Django 5.2.14 on 2026-06-25 20:29

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactpagesettings_contactquickaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpcenterhero',
            options={'ordering': ['-is_active', '-updated_at'], 'verbose_name': 'Help Center Hero', 'verbose_name_plural': 'Help Center Heroes'},
        ),
        migrations.AlterField(
            model_name='careercategory',
            name='icon',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='careercategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('orders', 'Orders & Shipping'), ('returns', 'Returns & Refunds'), ('vendors', 'Vendor Help'), ('account', 'Account'), ('products', 'Products'), ('payments', 'Payments'), ('security', 'Security & Trust')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='faq',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for this FAQ', null=True, upload_to='support/faqs/'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload resume, PDF or DOC', null=True, upload_to='job_applications/resumes/'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='application_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='responsibilities',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Key responsibilities'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='footer_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='show_in_footer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='show_in_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='sidebar_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Optional sidebar content'),
        ),
        migrations.AlterField(
            model_name='supportarticle',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supportarticle',
            name='not_helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supportarticle',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supporttopic',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon class, e.g. fas fa-truck', max_length=80),
        ),
        migrations.AlterField(
            model_name='supporttopic',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional topic image/icon', null=True, upload_to='support/topics/'),
        ),
        migrations.AlterField(
            model_name='supporttopic',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
