# Generated by Django 5.2.14 on 2026-07-10 05:57

import core.private_upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_helpcenterhero_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload resume in PDF or DOCX format.', null=True, upload_to='job_applications/resumes/', validators=[core.private_upload_validation.PrivateUploadValidator('resume')]),
        ),
    ]
