# Generated by Django 6.0.4 on 2026-05-09 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/')),
                ('url', models.URLField(blank=True)),
                ('button_text', models.CharField(default='Learn More', max_length=100)),
                ('placement', models.CharField(choices=[('sidebar', 'Sidebar'), ('banner', 'Banner'), ('homepage', 'Homepage'), ('footer', 'Footer')], default='sidebar', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='targeting',
            field=models.CharField(choices=[('all', 'All Visitors'), ('logged_in', 'Logged In Users'), ('new', 'New Visitors')], default='all', max_length=20),
        ),
        migrations.CreateModel(
            name='AdAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='ads.adcampaign')),
            ],
            options={
                'verbose_name': 'Ad Analytics',
                'verbose_name_plural': 'Ad Analytics',
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
