# Generated by Django 6.0.4 on 2026-05-10 00:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_advertisement_alter_adcampaign_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adanalytics',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='adplacement',
            options={'ordering': ['-priority', 'name']},
        ),
        migrations.RenameField(
            model_name='adanalytics',
            old_name='spent',
            new_name='revenue',
        ),
        migrations.RenameField(
            model_name='adbanner',
            old_name='mobile_image',
            new_name='image_mobile',
        ),
        migrations.RenameField(
            model_name='adcampaign',
            old_name='cost_per_click',
            new_name='max_bid',
        ),
        migrations.RenameField(
            model_name='adcampaign',
            old_name='budget',
            new_name='total_budget',
        ),
        migrations.RemoveField(
            model_name='adcampaign',
            name='cost_per_impression',
        ),
        migrations.RemoveField(
            model_name='adcampaign',
            name='sponsor_logo',
        ),
        migrations.RemoveField(
            model_name='adcampaign',
            name='sponsor_name',
        ),
        migrations.RemoveField(
            model_name='adcampaign',
            name='sponsor_website',
        ),
        migrations.AddField(
            model_name='adanalytics',
            name='conversion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='adanalytics',
            name='conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adanalytics',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='adanalytics',
            name='cpc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='adanalytics',
            name='cpm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='adanalytics',
            name='ctr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='adanalytics',
            name='roas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='adanalytics',
            name='roi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='adanalytics',
            name='unique_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adanalytics',
            name='unique_impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='animation',
            field=models.CharField(blank=True, choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom'), ('none', 'None')], max_length=50),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='conversion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='hover_effect',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='avg_position',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='bid_strategy',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('target', 'Target CPA')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='browser_targeting',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='budget_type',
            field=models.CharField(choices=[('daily', 'Daily Budget'), ('total', 'Total Budget'), ('lifetime', 'Lifetime Budget')], default='total', max_length=10),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='clicks_per_user',
            field=models.IntegerField(default=0, help_text='Max clicks per user'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='conversion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='conversion_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='custom_segments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='daily_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='dayparting',
            field=models.JSONField(blank=True, default=dict, help_text='Schedule for specific hours/days'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='device_targeting',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='frequency_cap',
            field=models.IntegerField(default=0, help_text='Frequency cap per day'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='geo_targeting',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='impressions_per_user',
            field=models.IntegerField(default=0, help_text='Max impressions per user'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='interest_targeting',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='os_targeting',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='quality_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='roas',
            field=models.FloatField(default=0.0, help_text='Return on Ad Spend'),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='target_cpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adclick',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adclick',
            name='click_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='adclick',
            name='conversion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adclick',
            name='conversion_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='adclick',
            name='converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adclick',
            name='device_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adclick',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adclick',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adclick',
            name='referer',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='device_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='impression_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='referer',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='view_duration',
            field=models.IntegerField(default=0, help_text='View duration in seconds'),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='visible_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='was_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='allowed_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='allowed_devices',
            field=models.JSONField(blank=True, default=list, help_text="['mobile', 'tablet', 'desktop']"),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='max_impressions_per_session',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='min_visit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='placement_type',
            field=models.CharField(choices=[('sidebar', 'Sidebar'), ('banner', 'Banner'), ('footer', 'Footer'), ('homepage', 'Homepage'), ('popup', 'Popup Modal'), ('interstitial', 'Interstitial'), ('native', 'Native Ad'), ('video', 'Video Ad'), ('carousel', 'Carousel'), ('sticky', 'Sticky Bottom')], default='sidebar', max_length=20),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='requires_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adplacement',
            name='rotation_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ctr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='show_to_guests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='show_to_logged_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_audience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='adanalytics',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='cta_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('cpc', 'Cost Per Click'), ('cpm', 'Cost Per Mille'), ('cpa', 'Cost Per Action'), ('sponsored', 'Sponsored Product'), ('display', 'Display Banner'), ('video', 'Video Ad'), ('native', 'Native Ad'), ('retargeting', 'Retargeting')], default='display', max_length=20),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='targeting',
            field=models.CharField(choices=[('all', 'All Visitors'), ('logged_in', 'Logged In Users'), ('new', 'New Visitors'), ('returning', 'Returning Visitors'), ('high_value', 'High Value Customers')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='adclick',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adimpression',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='placement',
            field=models.CharField(choices=[('sidebar', 'Sidebar'), ('banner', 'Banner'), ('footer', 'Footer'), ('homepage', 'Homepage'), ('popup', 'Popup')], default='sidebar', max_length=20),
        ),
        migrations.CreateModel(
            name='AdConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('conversion_type', models.CharField(choices=[('purchase', 'Purchase'), ('signup', 'Signup'), ('lead', 'Lead'), ('download', 'Download'), ('view', 'View'), ('custom', 'Custom')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.adcampaign')),
                ('click', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='ads.adclick')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('creative_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('html5', 'HTML5'), ('native', 'Native'), ('carousel', 'Carousel'), ('dynamic', 'Dynamic')], default='image', max_length=20)),
                ('headline', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cta_text', models.CharField(default='Learn More', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/creatives/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='ads/creatives/mobile/')),
                ('video_url', models.URLField(blank=True)),
                ('html_content', models.TextField(blank=True, help_text='HTML5 creative content')),
                ('carousel_items', models.JSONField(blank=True, default=list)),
                ('dynamic_fields', models.JSONField(blank=True, default=dict)),
                ('clickthrough_url', models.URLField()),
                ('tracking_url', models.URLField(blank=True)),
                ('ab_variant', models.CharField(blank=True, max_length=20)),
                ('ab_weight', models.IntegerField(default=100)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='ads.adcampaign')),
            ],
            options={
                'ordering': ['-ab_weight', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adbanner',
            name='creative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='ads.adcreative'),
        ),
        migrations.AddField(
            model_name='adclick',
            name='creative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.adcreative'),
        ),
        migrations.AddField(
            model_name='adimpression',
            name='creative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.adcreative'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['session_id', 'timestamp'], name='ads_adimpre_session_0dbc62_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['campaign', 'timestamp'], name='ads_adimpre_campaig_987b42_idx'),
        ),
    ]
