# Generated by Django 5.2.14 on 2026-05-16 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_add_adcreative_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='height_override',
            field=models.PositiveIntegerField(blank=True, help_text='Optional desktop height override in pixels. Falls back to placement height.', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='image_fit',
            field=models.CharField(choices=[('cover', 'Fill frame (crop if needed)'), ('contain', 'Fit whole image'), ('fill', 'Stretch to frame'), ('scale-down', 'Scale down only')], default='cover', max_length=20),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='image_position',
            field=models.CharField(default='center center', help_text='CSS object-position for desktop/tablet.', max_length=50),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='mobile_height_override',
            field=models.PositiveIntegerField(blank=True, help_text='Optional mobile height override in pixels.', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(1600)]),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='mobile_image_fit',
            field=models.CharField(choices=[('cover', 'Fill frame (crop if needed)'), ('contain', 'Fit whole image'), ('fill', 'Stretch to frame'), ('scale-down', 'Scale down only')], default='cover', max_length=20),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='mobile_image_position',
            field=models.CharField(default='center center', help_text='CSS object-position for mobile.', max_length=50),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='mobile_width_override',
            field=models.PositiveIntegerField(blank=True, help_text='Optional mobile width override in pixels.', null=True, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(1600)]),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='width_override',
            field=models.PositiveIntegerField(blank=True, help_text='Optional desktop width override in pixels. Falls back to placement width.', null=True, validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
