# Generated by Django 5.2.14 on 2026-05-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_adbanner_height_override_adbanner_image_fit_and_more'),
        ('blog', '0002_blogpost_hero_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbanner',
            name='article_open_behavior',
            field=models.CharField(choices=[('same_page', 'Open in same page'), ('new_page', 'Open in new tab'), ('popup', 'Open in popup modal')], default='same_page', max_length=20),
        ),
        migrations.AddField(
            model_name='adbanner',
            name='linked_article',
            field=models.ForeignKey(blank=True, help_text='Optional article target. If set, it is used before the CTA URL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_banners', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='article_open_behavior',
            field=models.CharField(choices=[('same_page', 'Open in same page'), ('new_page', 'Open in new tab'), ('popup', 'Open in popup modal')], default='same_page', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='linked_article',
            field=models.ForeignKey(blank=True, help_text='Optional article target. If set, it is used before the URL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_ads', to='blog.blogpost'),
        ),
    ]
