# Generated by Django 5.2.14 on 2026-08-16 01:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_button_colors'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('installers', '0015_serviceprojectmedia_approved_at_and_more'),
        ('orders', '0012_cartitem_recommendation_algorithm_and_more'),
        ('products', '0040_videocommercecomment_videocommercerating'),
        ('vendors', '0017_alter_vendorprofile_pickup_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner_type', models.CharField(choices=[('vendor', 'Vendor'), ('provider', 'Service Provider'), ('platform', 'Platform')], db_index=True, max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advertiser_identities', to='installers.serviceproviderprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advertiser_identities', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advertiser_identities', to='vendors.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AdChannelExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(db_index=True, max_length=30)),
                ('status', models.CharField(db_index=True, default='draft', max_length=20)),
                ('external_campaign_id', models.CharField(blank=True, max_length=200)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_executions', to='ads.adcampaign')),
                ('advertiser_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_executions', to='ads.advertiseridentity')),
            ],
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='advertiser_identity',
            field=models.ForeignKey(blank=True, help_text='Optional V2 advertiser owner. Legacy campaigns may be blank.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='ads.advertiseridentity'),
        ),
        migrations.CreateModel(
            name='CampaignAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset_type', models.CharField(choices=[('product', 'Product'), ('product_video', 'Product Video'), ('vendor_store', 'Vendor Store'), ('provider_profile', 'Provider Profile'), ('provider_service', 'Provider Service'), ('external_url', 'External URL')], db_index=True, max_length=30)),
                ('object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('destination_url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('advertiser_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_assets', to='ads.advertiseridentity')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ads.adcampaign')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('product_video', models.ForeignKey(blank=True, help_text='Canonical ProductVideo reference for video commerce ads.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ad_campaign_assets', to='products.productvideo')),
            ],
        ),
        migrations.CreateModel(
            name='AdEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('delivery_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click'), ('view', 'View'), ('conversion', 'Conversion')], db_index=True, max_length=30)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('event_source', models.CharField(db_index=True, default='internal', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v2_events', to='ads.adcampaign')),
                ('channel_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ads.adchannelexecution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_events', to=settings.AUTH_USER_MODEL)),
                ('advertiser_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_events', to='ads.advertiseridentity')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ads.campaignasset')),
            ],
        ),
        migrations.CreateModel(
            name='AdAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('attribution_type', models.CharField(choices=[('view_through', 'View-through'), ('click_through', 'Click-through'), ('direct', 'Direct')], db_index=True, max_length=30)),
                ('attribution_model', models.CharField(choices=[('last_touch', 'Last touch'), ('first_touch', 'First touch'), ('linear', 'Linear'), ('position_based', 'Position based'), ('data_driven', 'Data driven')], db_index=True, default='last_touch', max_length=30)),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('revenue_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v2_attributions', to='ads.adcampaign')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_attributions', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_attributions', to='orders.orderitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_attributions', to='products.product')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_attributions', to='vendors.vendorprofile')),
                ('source_click_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_attributions', to='ads.adevent')),
                ('source_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='ads.adevent')),
                ('advertiser_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='ads.advertiseridentity')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='ads.campaignasset')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalAdvertisingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('meta', 'Meta'), ('google', 'Google'), ('tiktok', 'TikTok'), ('other', 'Other')], db_index=True, max_length=30)),
                ('external_account_id', models.CharField(blank=True, max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connected', 'Connected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('advertiser_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_accounts', to='ads.advertiseridentity')),
            ],
        ),
        migrations.AddField(
            model_name='adchannelexecution',
            name='external_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_executions', to='ads.externaladvertisingaccount'),
        ),
        migrations.AddIndex(
            model_name='advertiseridentity',
            index=models.Index(fields=['owner_type', 'is_active'], name='ads_adverti_owner_t_47a3a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='advertiseridentity',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor__isnull', False)), fields=('owner_type', 'vendor'), name='unique_ads_vendor_advertiser_identity'),
        ),
        migrations.AddConstraint(
            model_name='advertiseridentity',
            constraint=models.UniqueConstraint(condition=models.Q(('provider__isnull', False)), fields=('owner_type', 'provider'), name='unique_ads_provider_advertiser_identity'),
        ),
        migrations.AddIndex(
            model_name='campaignasset',
            index=models.Index(fields=['asset_type', 'is_active'], name='ads_campaig_asset_t_45c442_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignasset',
            index=models.Index(fields=['content_type', 'object_id'], name='ads_campaig_content_a52718_idx'),
        ),
        migrations.AddIndex(
            model_name='adevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='ads_adevent_event_t_29f225_idx'),
        ),
        migrations.AddIndex(
            model_name='adevent',
            index=models.Index(fields=['campaign', 'event_type'], name='ads_adevent_campaig_77bf75_idx'),
        ),
        migrations.AddIndex(
            model_name='adevent',
            index=models.Index(fields=['asset', 'event_type'], name='ads_adevent_asset_i_8ea765_idx'),
        ),
        migrations.AddIndex(
            model_name='adattribution',
            index=models.Index(fields=['attribution_type', 'created_at'], name='ads_adattri_attribu_9c8215_idx'),
        ),
        migrations.AddIndex(
            model_name='adattribution',
            index=models.Index(fields=['campaign', 'attribution_model'], name='ads_adattri_campaig_3f5d33_idx'),
        ),
        migrations.AddIndex(
            model_name='adattribution',
            index=models.Index(fields=['asset', 'delivery_id'], name='ads_adattri_asset_i_da07e3_idx'),
        ),
        migrations.AddIndex(
            model_name='adattribution',
            index=models.Index(fields=['order', 'order_item'], name='ads_adattri_order_i_195c69_idx'),
        ),
        migrations.AddIndex(
            model_name='adattribution',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='ads_adattri_target__e59022_idx'),
        ),
        migrations.AddConstraint(
            model_name='adattribution',
            constraint=models.UniqueConstraint(condition=models.Q(('order_item__isnull', False)), fields=('source_event', 'order_item', 'attribution_type', 'attribution_model'), name='unique_ads_order_item_attribution'),
        ),
        migrations.AddIndex(
            model_name='externaladvertisingaccount',
            index=models.Index(fields=['channel', 'status'], name='ads_externa_channel_ae6d67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externaladvertisingaccount',
            unique_together={('advertiser_identity', 'channel', 'external_account_id')},
        ),
        migrations.AddIndex(
            model_name='adchannelexecution',
            index=models.Index(fields=['campaign', 'channel', 'status'], name='ads_adchann_campaig_7cf359_idx'),
        ),
        migrations.AddIndex(
            model_name='adchannelexecution',
            index=models.Index(fields=['advertiser_identity', 'channel'], name='ads_adchann_adverti_43db8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='adchannelexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('campaign', 'channel'), name='unique_active_ads_channel_execution'),
        ),
    ]
