# Generated by Django 5.2.14 on 2026-08-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_advertiseridentity_adchannelexecution_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0012_cartitem_recommendation_algorithm_and_more'),
        ('products', '0041_productvideo_youtube_video_id_and_more'),
        ('vendors', '0017_alter_vendorprofile_pickup_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adattribution',
            name='gross_revenue_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='adattribution',
            name='lifecycle_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('reversed', 'Reversed'), ('adjusted', 'Adjusted')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='adattribution',
            name='net_revenue_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='adattribution',
            name='reversal_reason',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='adattribution',
            name='reversal_reference',
            field=models.CharField(blank=True, db_index=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='adattribution',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='adattribution',
            index=models.Index(fields=['advertiser_identity', 'lifecycle_status'], name='ads_adattri_adverti_df14c1_idx'),
        ),
    ]
