# Generated by Django 5.2.14 on 2026-08-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_attribution_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='objective',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('product_visits', 'Product Visits'), ('video_views', 'Video Views'), ('leads', 'Leads'), ('quote_requests', 'Quote Requests'), ('messages', 'Messages'), ('store_visits', 'Store Visits'), ('brand_awareness', 'Brand Awareness'), ('engagement', 'Engagement')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
