# Generated by Django 5.2.14 on 2026-08-20 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_advertiser_dashboard_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingConnectionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(db_index=True, max_length=30)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('message', models.CharField(blank=True, max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisingCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(db_index=True, max_length=30)),
                ('encrypted_access_token', models.BinaryField(blank=True, null=True)),
                ('encrypted_refresh_token', models.BinaryField(blank=True, null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('credential_version', models.PositiveIntegerField(default=1)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisingOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(db_index=True, max_length=30)),
                ('state', models.CharField(db_index=True, max_length=128, unique=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=160)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('redirect_uri', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='externaladvertisingaccount',
            name='channel',
            field=models.CharField(choices=[('meta', 'Meta'), ('google', 'Google'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('other', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='externaladvertisingaccount',
            name='status',
            field=models.CharField(choices=[('not_connected', 'Not connected'), ('pending', 'Pending'), ('disconnected', 'Disconnected'), ('connected', 'Connected'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('reauthorization_required', 'Reauthorization required'), ('error', 'Error')], default='disconnected', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='externaladvertisingaccount',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('external_account_id', ''), _negated=True), models.Q(('status__in', ['disconnected', 'revoked']), _negated=True)), fields=('channel', 'external_account_id'), name='uniq_active_external_ad_account'),
        ),
        migrations.AddField(
            model_name='advertisingconnectionauditlog',
            name='advertiser_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_audit_logs', to='ads.advertiseridentity'),
        ),
        migrations.AddField(
            model_name='advertisingconnectionauditlog',
            name='external_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ads.externaladvertisingaccount'),
        ),
        migrations.AddField(
            model_name='advertisingconnectionauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisingcredential',
            name='external_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='ads.externaladvertisingaccount'),
        ),
        migrations.AddField(
            model_name='advertisingoauthstate',
            name='advertiser_identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_states', to='ads.advertiseridentity'),
        ),
        migrations.AddField(
            model_name='advertisingoauthstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_oauth_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='advertisingconnectionauditlog',
            index=models.Index(fields=['provider', 'event_type', 'created_at'], name='ads_adverti_provide_48214d_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisingconnectionauditlog',
            index=models.Index(fields=['advertiser_identity', 'provider', 'created_at'], name='ads_adverti_adverti_bfa3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisingcredential',
            index=models.Index(fields=['provider', 'revoked_at'], name='ads_adverti_provide_17ce3f_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisingoauthstate',
            index=models.Index(fields=['provider', 'expires_at'], name='ads_adverti_provide_cc51f8_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisingoauthstate',
            index=models.Index(fields=['advertiser_identity', 'provider', 'used_at'], name='ads_adverti_adverti_8faa3f_idx'),
        ),
    ]
