# Generated by Django 5.2.14 on 2026-08-21 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_connected_advertising_accounts_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdChannelReportingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(db_index=True, max_length=30)),
                ('reporting_start', models.DateField()),
                ('reporting_end', models.DateField()),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('video_views', models.PositiveIntegerField(default=0)),
                ('provider_conversions', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='channel_budget_allocations',
            field=models.JSONField(blank=True, default=dict, help_text='Optional per-channel intended external budget allocation metadata. Does not move money.'),
        ),
        migrations.AddField(
            model_name='adchannelexecution',
            name='budget_allocation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='adchannelexecution',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='adchannelexecution',
            name='external_ad_group_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='adchannelexecution',
            name='external_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='adchannelexecution',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name='adchannelexecution',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adchannelexecution',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('syncing', 'Syncing'), ('ready', 'Ready'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('reauthorization_required', 'Reauthorization required'), ('disconnected', 'Disconnected'), ('error', 'Error')], db_index=True, default='draft', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='adchannelexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='unique_ads_channel_execution_idempotency'),
        ),
        migrations.AddField(
            model_name='adchannelreportingsnapshot',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_snapshots', to='ads.adchannelexecution'),
        ),
        migrations.AddIndex(
            model_name='adchannelreportingsnapshot',
            index=models.Index(fields=['provider', 'reporting_start', 'reporting_end'], name='ads_adchann_provide_e0eae1_idx'),
        ),
        migrations.AddIndex(
            model_name='adchannelreportingsnapshot',
            index=models.Index(fields=['execution', 'reporting_start'], name='ads_adchann_executi_d500ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='adchannelreportingsnapshot',
            constraint=models.UniqueConstraint(fields=('execution', 'reporting_start', 'reporting_end'), name='unique_ads_channel_reporting_window'),
        ),
    ]
