# Generated by Django 5.2.14 on 2026-09-10 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_adchannelexecution_external_creative_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('meta', 'Meta'), ('google', 'Google'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('other', 'Other')], db_index=True, max_length=30)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], db_index=True, max_length=10)),
                ('source_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('provider_media_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_message', models.CharField(blank=True, max_length=240)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('external_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='ads.externaladvertisingaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['external_account', 'provider', 'status'], name='ads_adverti_externa_5c598d_idx')],
                'constraints': [models.UniqueConstraint(fields=('external_account', 'provider', 'media_type', 'source_fingerprint'), name='unique_ads_account_media_source')],
            },
        ),
    ]
