# Generated by Django 5.2.14 on 2026-05-25 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arolana_payments', '0003_paystack_gateway'),
        ('deliveries', '0003_deliveryrequest_base_fare_and_more'),
        ('orders', '0007_rename_orders_deli_status_58accc_idx_orders_deli_status_12226a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRobotProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_status', models.CharField(choices=[('new_order', 'New Order'), ('payment_confirmed', 'Payment Confirmed'), ('vendor_notified', 'Vendor Notified'), ('vendor_confirmed', 'Vendor Confirmed'), ('packaging', 'Packaging'), ('ready_for_pickup', 'Ready for Pickup'), ('delivery_created', 'Delivery Created'), ('rider_assigned', 'Rider Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_admin', 'Needs Admin')], db_index=True, default='new_order', max_length=40)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('requires_admin', models.BooleanField(db_index=True, default=False)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('vendor_notified_at', models.DateTimeField(blank=True, null=True)),
                ('vendor_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('ready_for_pickup_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_created_at', models.DateTimeField(blank=True, null=True)),
                ('rider_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_processes', to='orders.deliveryrequest')),
                ('live_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_processes', to='deliveries.deliveryrequest')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='robot_process', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_processes', to='arolana_payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Order Robot Process',
                'verbose_name_plural': 'Order Robot Processes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRobotActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new_order', 'New Order'), ('payment_confirmed', 'Payment Confirmed'), ('vendor_notified', 'Vendor Notified'), ('vendor_confirmed', 'Vendor Confirmed'), ('packaging', 'Packaging'), ('ready_for_pickup', 'Ready for Pickup'), ('delivery_created', 'Delivery Created'), ('rider_assigned', 'Rider Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_admin', 'Needs Admin')], db_index=True, max_length=40)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_robot_activities', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='order_robot.orderrobotprocess')),
            ],
            options={
                'verbose_name': 'Order Robot Activity',
                'verbose_name_plural': 'Order Robot Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderRobotVendorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Vendor'), ('confirmed', 'Vendor Confirmed'), ('rejected', 'Vendor Rejected'), ('ready_for_pickup', 'Ready for Pickup'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_tasks', to='order_robot.orderrobotprocess')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_robot_vendor_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Robot Vendor Task',
                'verbose_name_plural': 'Order Robot Vendor Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='orderrobotprocess',
            index=models.Index(fields=['current_status', '-created_at'], name='order_robot_current_52bb16_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrobotprocess',
            index=models.Index(fields=['requires_admin', '-created_at'], name='order_robot_require_79fd93_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrobotvendortask',
            index=models.Index(fields=['vendor', 'status', '-created_at'], name='order_robot_vendor__b2f972_idx'),
        ),
        migrations.AddIndex(
            model_name='orderrobotvendortask',
            index=models.Index(fields=['status', '-created_at'], name='order_robot_status_5e3d2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderrobotvendortask',
            unique_together={('process', 'vendor')},
        ),
    ]
