# Generated by Django 6.0.4 on 2026-04-30 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='products.product'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='chattypingstatus',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_status', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='chattypingstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorchatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorchatroom',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorchatroom',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='vendorchatroom',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='vendorchatroom',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorchatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.vendorchatroom'),
        ),
        migrations.AlterUniqueTogether(
            name='chattypingstatus',
            unique_together={('room', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='vendorchatroom',
            unique_together={('vendor', 'customer', 'product')},
        ),
    ]
