# Generated by Django 5.2.14 on 2026-07-10 05:57

import core.private_upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat/attachments/%Y/%m/', validators=[core.private_upload_validation.PrivateUploadValidator('chat_attachment')]),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, help_text='Room name for group chats.', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorchatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat/vendor_attachments/%Y/%m/', validators=[core.private_upload_validation.PrivateUploadValidator('chat_attachment')]),
        ),
        migrations.AlterField(
            model_name='vendorchatmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
