# Generated by Django 6.0.4 on 2026-04-30 12:00

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='e.g., Shop, Support, Company', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Description for this menu section (supports HTML formatting)', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in footer')),
            ],
            options={
                'verbose_name': 'Footer Menu Category',
                'verbose_name_plural': 'Footer Menu Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FooterMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='Display text for the menu item', max_length=100)),
                ('url', models.CharField(help_text='URL or path (e.g., /products/, /contact/)', max_length=500)),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('display_order', models.IntegerField(default=0, help_text='Order within category')),
                ('is_external', models.BooleanField(default=False, help_text='Is this an external link?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='footer_menu.footermenucategory')),
            ],
            options={
                'verbose_name': 'Footer Menu Item',
                'verbose_name_plural': 'Footer Menu Items',
                'ordering': ['category__display_order', 'display_order', 'title'],
            },
        ),
    ]
