# Generated by Django 6.0.4 on 2026-05-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_vendoradminmessage_vendornotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoradminmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendoradminmessage',
            name='is_deleted_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendoradminmessage',
            name='is_deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
