# Generated by Django 5.2.14 on 2026-05-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('all', 'All account types'), ('customer', 'Customers'), ('vendor', 'Vendors'), ('manufacturer', 'Manufacturers')], default='all', max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('notification', 'In-app notification'), ('both', 'Email and in-app notification')], default='both', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Available placeholders: {first_name}, {last_name}, {full_name}, {username}, {email}, {account_type}, {site_name}, {login_url}, {profile_url}')),
                ('notification_title', models.CharField(blank=True, max_length=200)),
                ('notification_link', models.CharField(blank=True, default='/accounts/profile/', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('manufacturer', 'Manufacturer'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='customer', max_length=20),
        ),
    ]
