# Generated by Django 6.0.4 on 2026-04-30 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('attempt_count', models.IntegerField(default=1)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'ip_address'], name='accounts_lo_email_b0d539_idx'), models.Index(fields=['is_locked', 'locked_until'], name='accounts_lo_is_lock_d8d97d_idx')],
                'unique_together': {('email', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('email_verified', 'Email Verified'), ('phone_verified', 'Phone Verified'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('account_locked', 'Account Locked')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='accounts_us_user_id_39428d_idx'), models.Index(fields=['action', 'timestamp'], name='accounts_us_action_fb1cb3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('email', 'Email Verification'), ('phone', 'Phone Verification'), ('login', 'Login OTP'), ('password_reset', 'Password Reset'), ('two_factor', '2FA Verification')], max_length=20)),
                ('destination', models.CharField(help_text='Email or phone number where OTP was sent', max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'otp_type', '-created_at'], name='accounts_us_user_id_8463f0_idx'), models.Index(fields=['otp_code', 'is_used'], name='accounts_us_otp_cod_e4da12_idx')],
            },
        ),
    ]
