# Generated by Codex on 2026-05-15

from django.db import migrations


def seed_registration_messages(apps, schema_editor):
    RegistrationMessageTemplate = apps.get_model('accounts', 'RegistrationMessageTemplate')
    defaults = [
        {
            'name': 'Customer welcome',
            'role': 'customer',
            'channel': 'both',
            'subject': 'Welcome to {site_name}',
            'body': (
                'Hello {first_name},\n\n'
                'Welcome to {site_name}. Your customer account is ready. '
                'You can manage your profile, save products, and track orders from {profile_url}.\n\n'
                'Thank you for joining us.'
            ),
            'notification_title': 'Welcome to Arolana',
            'notification_link': '/accounts/profile/',
            'is_active': True,
        },
        {
            'name': 'Seller KYC welcome',
            'role': 'vendor',
            'channel': 'both',
            'subject': 'Complete KYC to start selling on {site_name}',
            'body': (
                'Hello {first_name},\n\n'
                'Your vendor account has been created. Complete KYC verification and choose a subscription plan '
                'before uploading products. Start from {profile_url}.\n\n'
                'Arolana Seller Team'
            ),
            'notification_title': 'Complete KYC to start selling',
            'notification_link': '/kyc/',
            'is_active': True,
        },
        {
            'name': 'Manufacturer KYC welcome',
            'role': 'manufacturer',
            'channel': 'both',
            'subject': 'Verify your manufacturer account on {site_name}',
            'body': (
                'Hello {first_name},\n\n'
                'Your manufacturer account has been created. Complete KYC verification so admin can approve your brand '
                'and product upload access.\n\n'
                'Arolana Manufacturer Team'
            ),
            'notification_title': 'Verify your manufacturer account',
            'notification_link': '/kyc/',
            'is_active': True,
        },
    ]

    for data in defaults:
        RegistrationMessageTemplate.objects.get_or_create(
            name=data['name'],
            role=data['role'],
            defaults=data,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registrationmessagetemplate_alter_user_user_type'),
    ]

    operations = [
        migrations.RunPython(seed_registration_messages, migrations.RunPython.noop),
    ]
