# Generated by Django 5.2.14 on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_email_opt_in_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_messages_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
