CATEGORY_GUIDANCE = {
    "General Marketplace": "Arolana is a multi-category marketplace. Use search and filters, review listing details, confirm vendor information, and use checkout or request a quote as shown on the listing.",
    "Customer Account": "Use your Arolana account for saved addresses, orders, wishlist, messages, and support. Never share passwords, PINs, or verification codes in chat.",
    "Technology": "Check the exact model, specifications, compatibility, condition, stock, warranty, reviews, and vendor details before buying technology.",
    "Electricals": "Confirm voltage, wattage, phase, plug type, load requirement, installation needs, warranty, and safety certification from the listing or vendor.",
    "Smart Home": "Confirm ecosystem compatibility, connectivity, required hubs, power source, installation, app support, and warranty before ordering.",
    "Networking": "Confirm speed, ports, Wi-Fi standard, coverage, user capacity, PoE requirements, compatibility, and installation needs.",
    "Audio Visual": "Confirm room size, brightness, resolution, throw distance, inputs, sound requirements, mounting accessories, and warranty.",
    "Surveillance": "Confirm camera type, resolution, night vision, storage, PoE or power needs, recorder compatibility, installation, and remote viewing.",
    "Properties": "Property availability, ownership documents, inspection, exact location, fees, and final terms require confirmation by the listing agent or Arolana support.",
    "Cars": "Confirm year, mileage, condition, inspection history, documents, location, price, and seller details before making a vehicle commitment.",
    "Food": "Check ingredients, quantity, expiry or preparation date, storage, dietary information, delivery area, and vendor handling information.",
    "Kitchen Items": "Confirm material, dimensions, capacity, heat source compatibility, power requirements where relevant, warranty, and care instructions.",
    "Art": "Confirm dimensions, medium, artist, originality, framing, customization, delivery protection, and certificate information where listed.",
    "Fashion": "Confirm size chart, material, colour, condition, care instructions, seller return terms, and availability before ordering.",
    "Industrial": "Confirm technical capacity, duty cycle, power requirements, installation, operator needs, spare parts, service support, and warranty.",
    "Services": "Confirm service scope, location, schedule, deliverables, provider verification, quotation, exclusions, and completion terms.",
    "Vendors": "Review vendor verification, rating, store information, product history, response quality, and quotation terms. Use Arolana support for sensitive disputes.",
    "Payments": "Only use payment methods enabled at Arolana checkout. Never send card details, passwords, PINs, OTPs, or payment credentials through chat.",
    "Delivery": "Delivery time and cost depend on location, listing, package size, vendor fulfilment, and selected service. Checkout shows available delivery information.",
    "Orders": "Use the order number or tracking code from your account. Order information is private and is only checked for the authenticated customer.",
    "Returns": "Return and refund eligibility depends on the order, item condition, reason, timing, and marketplace policy. Sensitive cases require support verification.",
    "Warranty": "Warranty coverage must come from the product listing, manufacturer warranty, or vendor confirmation. Do not assume unlisted coverage.",
    "Human Support": "Arolana support can take over with the existing conversation context, transcript, customer details, listing, detected intent, and escalation reason.",
}

TOPICS = [
    ("getting_started", "How do I get started with {category} on Arolana?", "Start with the marketplace search, choose the closest category, then apply relevant filters."),
    ("search", "How do I search for {category}?", "Search using the item, brand, location, model, or service name, then refine the results."),
    ("availability", "How do I confirm availability for {category}?", "Availability must be checked from the current listing stock or confirmed by the vendor."),
    ("price", "How do I check the price for {category}?", "Use the current listing price. For negotiable, bulk, property, vehicle, or service transactions, request confirmation."),
    ("budget", "Can Arolana help me shop for {category} within my budget?", "Share your budget and required features so suitable listings can be compared."),
    ("recommendation", "Can you recommend the right {category} option?", "Share your use case, budget, location, preferred condition, and must-have requirements."),
    ("comparison", "How do I compare {category} listings?", "Compare verified facts such as price, condition, specifications, rating, warranty, location, and vendor."),
    ("details", "Where can I see complete details for {category}?", "Open the listing and review its description, specifications, media, Q&A, reviews, seller, and policies."),
    ("missing_details", "What happens when a {category} detail is missing?", "The assistant must say the information is unavailable and request vendor or support confirmation."),
    ("buy", "How do I buy a {category} listing?", "Use Add to Cart and checkout where enabled. Use Request Quote or contact support where manual confirmation is required."),
    ("checkout", "What are the checkout steps for {category}?", "Open the cart, confirm quantity, enter delivery details, choose an enabled payment method, and place the order."),
    ("payment", "What payment methods can I use for {category}?", "Use only methods currently displayed at Arolana checkout."),
    ("delivery", "How does delivery work for {category}?", "Delivery options depend on destination, listing, vendor fulfilment, package type, and available delivery services."),
    ("delivery_time", "How long does delivery take for {category}?", "Use the listing estimate when available; otherwise checkout or support must confirm it."),
    ("delivery_cost", "How is delivery cost calculated for {category}?", "Cost can depend on destination, weight, dimensions, service level, and vendor pickup location."),
    ("location", "Can I find {category} by location?", "Share the preferred location or delivery destination and use available location filters."),
    ("condition", "How do I check the condition of {category}?", "Use the listing condition and supporting description or media; request inspection or confirmation for high-value items."),
    ("vendor", "How do I check the vendor for {category}?", "Review verification, store details, ratings, reviews, response history, and listing information."),
    ("reviews", "Should I read reviews before choosing {category}?", "Yes. Use reviews as one signal alongside verified listing facts, condition, warranty, and vendor information."),
    ("rating", "What does the rating mean for {category}?", "Ratings summarize customer feedback but do not replace checking the exact listing facts."),
    ("warranty", "How do I confirm warranty for {category}?", "Use only the warranty explicitly listed by the product, manufacturer, or vendor."),
    ("return", "Can I return a {category} order?", "Eligibility depends on the order and policy. Keep the item and packaging in the required condition and contact support promptly."),
    ("refund", "How do I request a refund for {category}?", "Open the order and contact support with the reason and evidence. Refund decisions require secure order review."),
    ("support", "How do I get support for {category}?", "Ask for Arolana support in chat. The transcript and current listing context will be transferred."),
    ("human", "Can I speak with a human about {category}?", "Yes. Ask for a human, agent, or support and a takeover request will be created."),
    ("quote", "How do I request a quotation for {category}?", "Provide the item or service, quantity, budget, delivery location, and required date."),
    ("bulk", "Can I place a bulk order for {category}?", "Provide quantity, specification, budget, destination, and deadline so a vendor or staff member can quote."),
    ("compatibility", "How do I confirm compatibility for {category}?", "Compare the exact listed compatibility notes and model requirements. Do not assume compatibility when it is missing."),
    ("specifications", "Where do specifications for {category} come from?", "Specifications must come from the Arolana listing, structured product data, manufacturer, vendor, reviews, or answered Q&A."),
    ("images", "Can I rely on images for {category}?", "Images help show the listing, but confirm written specifications, condition, included items, and seller terms."),
    ("videos", "Are videos available for {category}?", "Use listing video metadata when available. A video does not replace checking written facts."),
    ("accessories", "How do I check included accessories for {category}?", "Use the listing and accessories section. If inclusions are not stated, request confirmation."),
    ("stock", "How do I know if {category} is in stock?", "Use the live stock status. For manual listings, request confirmation before payment."),
    ("order_status", "How do I track my {category} order?", "Use the authenticated account order page or provide the order number to Smart Chat."),
    ("privacy", "Is my {category} conversation private?", "Customer-specific memory and order data are restricted to the same authenticated customer, device, or guest session."),
    ("memory", "Will Smart Chat remember my {category} preferences?", "It can retain relevant customer preferences and current listing context for the same customer when memory is enabled."),
    ("accuracy", "Will Smart Chat invent details about {category}?", "No. Missing facts must be identified as unavailable and escalated when confirmation matters."),
    ("complaint", "What should I do if I am unhappy with {category} support?", "Explain the issue or ask for a human. The assistant should apologize, preserve context, and escalate."),
    ("agent_context", "Will an agent see my previous {category} messages?", "Yes. Handover includes the transcript, detected intent, category, listing context, summary, and escalation reason."),
    ("account", "Do I need an account to buy {category}?", "An account is recommended for orders, history, tracking, support, saved addresses, and secure customer-specific assistance."),
    ("guest", "Can a guest ask about {category}?", "Guests can ask general questions, while personal order and memory access requires the correct session or login."),
    ("security", "What information should I never share for {category}?", "Never share passwords, PINs, OTPs, complete card details, or private authentication credentials."),
    ("verified_data", "What data does Smart Chat check for {category}?", "It checks approved knowledge and available catalog facts such as description, specifications, media, reviews, Q&A, price, stock, delivery, and warranty."),
    ("follow_up", "Can I ask a follow-up question about {category}?", "Yes. Smart Chat keeps the current listing and topic so pronouns such as it or this item can be understood."),
    ("repeat", "Why should Smart Chat not repeat {category} results?", "Search cards are for search and detail intents. Payment, delivery, checkout, support, and follow-up questions use conversation context instead."),
    ("confidence", "What happens when confidence is low for {category}?", "The assistant records the unanswered question and connects the conversation to human support."),
    ("approval", "Does Smart Chat use unapproved learned answers for {category}?", "No. Learned knowledge must be privacy-safe, active, and approved by an administrator before use."),
    ("admin", "Can Arolana admin correct a {category} answer?", "Yes. Admin can edit knowledge, training data, learned answers, settings, memory, conversations, and takeover requests."),
    ("mobile", "Does Smart Chat support {category} on mobile?", "Yes. Mobile uses the same backend conversation, context memory, history, unread count, and support handover."),
    ("unread", "How do unread messages work for {category} support?", "Unread counts identify new customer or staff messages and clear when the correct participant marks them read."),
    ("notification", "Will I be notified about {category} support replies?", "Supported mobile and web notification channels can alert the customer when staff replies."),
    ("seller_contact", "Can I contact the seller about {category}?", "Use the available vendor chat or request support. Paid vendor chat availability can depend on vendor subscription status."),
    ("negotiation", "Can I negotiate a {category} price?", "Only negotiate where the listing or quotation workflow allows it. Final terms must be confirmed by the vendor or staff."),
    ("invoice", "Can I get an invoice for {category}?", "Order and quotation documents depend on the completed transaction and vendor or Arolana process."),
    ("tax", "Does the {category} price include taxes?", "Use the checkout or quotation breakdown. Do not assume taxes or fees that are not displayed."),
    ("cancellation", "Can I cancel a {category} order?", "Cancellation depends on order status and fulfilment progress. Contact support as soon as possible."),
    ("damaged", "What if my {category} order arrives damaged?", "Preserve the packaging, take clear evidence, avoid further use, and contact support with the order number."),
    ("wrong_item", "What if I receive the wrong {category} item?", "Keep the item and packaging, document the issue, and contact support for secure order review."),
    ("late", "What if my {category} delivery is late?", "Check tracking first, then contact support with the order number if the estimate has passed."),
    ("inspection", "Can I inspect {category} before committing?", "Inspection options depend on the listing type and vendor. High-value property, vehicle, art, and industrial deals should be manually confirmed."),
    ("documents", "What documents should I check for {category}?", "Check documents relevant to the listing type and have high-value ownership or compliance documents independently verified."),
    ("authenticity", "How do I confirm authenticity for {category}?", "Use seller verification, listing evidence, serial or certificate information where available, and request manual confirmation when needed."),
    ("custom", "Can I request a custom {category} order?", "Describe the required design, specification, quantity, budget, location, and deadline, then request a quote."),
    ("service_area", "Is {category} available in my area?", "Share your location. Availability depends on vendor coverage, listing location, and delivery or service area."),
    ("deadline", "Can I get {category} by a specific date?", "Share the required date and destination. The listing estimate or vendor must confirm feasibility."),
    ("quantity", "How do I choose quantity for {category}?", "Use available stock and cart controls. Large quantities should use the quotation or bulk-order workflow."),
    ("minimum_order", "Is there a minimum order for {category}?", "Use the listing MOQ or request vendor confirmation when it is not stated."),
    ("wholesale", "Can I buy {category} wholesale?", "Search manufacturer or wholesaler vendors and request a quote with quantity, destination, and required date."),
    ("manufacturer", "Can I find a manufacturer for {category}?", "Use manufacturer and verified-vendor sections, then review verification and request production or supply terms."),
    ("service_provider", "Can I find a service provider for {category}?", "Search verified service providers and confirm scope, location, schedule, deliverables, and quotation."),
    ("saved", "Can I save a {category} listing?", "Use the wishlist or saved-item feature when available while signed in."),
    ("compare_later", "Can I compare {category} later?", "Save relevant listings and return to compare current facts because price and availability can change."),
    ("price_change", "Can the price of {category} change?", "Yes. Use the current listing or quotation price at the time of checkout or confirmation."),
    ("availability_change", "Can {category} availability change?", "Yes. Stock and manual listing availability can change, so confirm before payment."),
    ("chat_image", "Can I send an image about {category}?", "Use the chat image upload when available, but avoid including private credentials or unrelated personal information."),
    ("language", "Can I ask about {category} in normal words?", "Yes. Describe what you need naturally, including budget, location, use case, and preferred condition."),
    ("short_answer", "Will Smart Chat keep {category} answers concise?", "Yes. Answers should be short, practical, sales-focused, and expand only when more detail is requested."),
    ("source", "How does Smart Chat source {category} answers?", "It checks approved knowledge, customer context, live Arolana data, and only then uses model reasoning without inventing facts."),
    ("category", "How does Smart Chat route a {category} question?", "It detects intent first, identifies the marketplace category, checks memory, approved knowledge, live data, and confidence."),
    ("handover_reason", "Why might a {category} chat be handed to support?", "Handover is used for low confidence, sensitive payments or refunds, complaints, quotes, bulk orders, and manual high-value confirmation."),
    ("summary", "What context is transferred for {category} handover?", "The agent receives the transcript, customer details when available, intent, category, listing, AI summary, reason, and urgency."),
    ("data_update", "How can incorrect {category} information be updated?", "The responsible vendor or administrator should correct the listing or approved knowledge entry."),
    ("faq_feedback", "Can I rate a {category} Smart Chat answer?", "Yes. Feedback and ratings are stored for administrator review and training improvement."),
    ("learned_answer", "Can Smart Chat learn from repeated {category} questions?", "Repeated privacy-safe questions can become learned candidates, but they remain unusable until admin approval."),
    ("personal_data", "Does shared {category} knowledge include personal data?", "No. Shared knowledge must contain general useful information, not private customer details."),
    ("different_customer", "Can another customer see my {category} memory?", "No. Customer memory is restricted to the same logged-in user, device, or guest session."),
    ("support_wait", "What happens while waiting for {category} support?", "The conversation remains available, staff can see the transferred context, and unread notifications indicate replies."),
    ("resolved", "How is a {category} support conversation resolved?", "Staff can answer, mark the takeover or ticket resolved, and close the conversation while preserving its history."),
    ("best_practice", "What is the safest way to complete a {category} transaction?", "Use Arolana listing, checkout, quotation, messaging, and support flows; verify high-value facts before commitment."),
    ("final_confirmation", "What should I confirm before paying for {category}?", "Confirm the exact listing, quantity, condition, price, delivery, seller, warranty, and any manual terms."),
]


def build_seed_entries():
    entries = []
    for category, guidance in CATEGORY_GUIDANCE.items():
        for topic, question, answer in TOPICS:
            entries.append({
                "question": question.format(category=category.lower()),
                "answer": f"{answer} {guidance}",
                "category": category,
                "keywords": f"{category}, {topic}, Arolana",
                "audience": "all",
                "approved": True,
                "is_active": True,
                "priority": 60,
            })
    return entries
