# Generated by Django 5.2.14 on 2026-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='hero_background_color',
            field=models.CharField(default='#111827', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_featured_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Optional social/media links. Example: {"YouTube": "https://...", "Instagram": "https://..."}'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='source_url',
            field=models.URLField(blank=True, help_text='Optional source, manufacturer, or external reference link'),
        ),
    ]
