# Generated by Django 5.2.14 on 2026-05-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_hero_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='local_video',
            field=models.FileField(blank=True, help_text='Optional uploaded article video (MP4/WebM). Used when no YouTube/Vimeo URL is provided.', null=True, upload_to='blog/videos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_article_after_author_ad',
            field=models.BooleanField(default=False, help_text='Show an ad after the author box.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_article_footer_ad',
            field=models.BooleanField(default=False, help_text='Show an ad after comments.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_article_native_ad',
            field=models.BooleanField(default=False, help_text='Show a native/sponsored ad inside the article body.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_article_top_ad',
            field=models.BooleanField(default=False, help_text='Show an ad above the article media.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_sidebar_bottom_ad',
            field=models.BooleanField(default=False, help_text='Show the bottom sidebar ad.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_sidebar_mid_ad',
            field=models.BooleanField(default=False, help_text='Show the middle sidebar ad.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_sidebar_newsletter',
            field=models.BooleanField(default=True, help_text='Show newsletter signup on this article.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_sidebar_sticky_ad',
            field=models.BooleanField(default=False, help_text='Show the sticky sidebar ad.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_sidebar_top_ad',
            field=models.BooleanField(default=False, help_text='Show the top sidebar ad.'),
        ),
    ]
