# Generated by Django 5.2.14 on 2026-06-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_local_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='product_article_default_open_behavior',
            field=models.CharField(choices=[('same_page', 'Open in same page'), ('new_page', 'Open in new tab'), ('popup', 'Open in popup / modal'), ('split_reader', 'Open beside product / split reader')], default='split_reader', help_text='Default behavior when this article is opened from a product page.', max_length=30),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='product_article_default_reader_content_mode',
            field=models.CharField(choices=[('clean_full_article', 'Clean full article'), ('full_article', 'Full article page'), ('body_only', 'Article body only')], default='clean_full_article', help_text='Default content mode when this article is opened inside the product split reader.', max_length=30),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='product_article_reader_show_ads',
            field=models.BooleanField(default=False, help_text='Default: show ads inside the product article split reader.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='product_article_reader_show_author_box',
            field=models.BooleanField(default=True, help_text='Default: show author box inside the product article split reader.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='product_article_reader_show_chat_widgets',
            field=models.BooleanField(default=False, help_text='Default: show chat widgets inside the product article split reader.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='product_article_reader_show_comments',
            field=models.BooleanField(default=True, help_text='Default: show comments inside the product article split reader.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='product_article_reader_show_cookie_banner',
            field=models.BooleanField(default=False, help_text='Default: show cookie/consent banners inside the product article split reader.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='product_article_reader_show_newsletter',
            field=models.BooleanField(default=False, help_text='Default: show newsletter blocks inside the product article split reader.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='product_article_reader_show_share_box',
            field=models.BooleanField(default=True, help_text='Default: show share/social box inside the product article split reader.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='product_article_reader_show_site_header_footer',
            field=models.BooleanField(default=False, help_text='Default: show site header/footer inside the product article split reader.'),
        ),
    ]
