# Generated by Django 6.0.4 on 2026-05-03 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Main headline text', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Secondary text', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Additional description')),
                ('image_desktop', models.ImageField(blank=True, help_text='Desktop image (1920x1080 recommended)', null=True, upload_to='hero_banners/desktop/')),
                ('image_tablet', models.ImageField(blank=True, help_text='Tablet image (1024x768)', null=True, upload_to='hero_banners/tablet/')),
                ('image_mobile', models.ImageField(blank=True, help_text='Mobile image (768x1024)', null=True, upload_to='hero_banners/mobile/')),
                ('animation_effect', models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom'), ('none', 'No Effect')], default='fade', max_length=20)),
                ('animation_duration', models.FloatField(default=0.8, help_text='Animation duration in seconds')),
                ('button1_text', models.CharField(default='Shop Now', max_length=50)),
                ('button1_url', models.CharField(default='/products/', max_length=500)),
                ('button1_style', models.CharField(default='primary', max_length=20)),
                ('button2_text', models.CharField(default='Learn More', max_length=50)),
                ('button2_url', models.CharField(blank=True, default='#', max_length=500)),
                ('button2_style', models.CharField(default='outline', max_length=20)),
                ('overlay_color', models.CharField(default='#000000', max_length=20)),
                ('overlay_opacity', models.FloatField(default=0.4)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=20)),
                ('content_position', models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('autoplay_delay', models.IntegerField(default=5000)),
                ('views_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBannerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('action', models.CharField(choices=[('view', 'View'), ('click', 'Click')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='hero_banners.herobanner')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
