# Generated by Django 5.2.14 on 2026-05-14 18:17

import django.core.validators
from django.db import migrations, models


def normalize_overlay_opacity(apps, schema_editor):
    HeroBanner = apps.get_model('hero_banners', 'HeroBanner')
    for banner in HeroBanner.objects.all():
        try:
            opacity = float(banner.overlay_opacity)
        except (TypeError, ValueError):
            opacity = 0.4

        if opacity < 0:
            opacity = abs(opacity)
        if opacity > 1:
            opacity = opacity / 100

        HeroBanner.objects.filter(pk=banner.pk).update(overlay_opacity=min(max(opacity, 0), 1))


class Migration(migrations.Migration):

    dependencies = [
        ('hero_banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='button3_style',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')], default='secondary', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='button3_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='button3_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button1_style',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')], default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button1_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button1_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button2_style',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('outline', 'Outline')], default='outline', max_length=20),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button2_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='overlay_opacity',
            field=models.FloatField(default=0.4, help_text='0 is transparent, 1 is fully dark. Example: 0.4', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.RunPython(normalize_overlay_opacity, migrations.RunPython.noop),
    ]
