# Generated by Django 5.2.14 on 2026-05-16 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_banners', '0002_herobanner_button3_style_herobanner_button3_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='desktop_height',
            field=models.PositiveIntegerField(default=560, help_text='Desktop hero height in pixels.', validators=[django.core.validators.MinValueValidator(160), django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image_fit_desktop',
            field=models.CharField(choices=[('cover', 'Fill frame (crop if needed)'), ('contain', 'Fit whole image'), ('fill', 'Stretch to frame'), ('scale-down', 'Scale down only')], default='cover', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image_fit_mobile',
            field=models.CharField(choices=[('cover', 'Fill frame (crop if needed)'), ('contain', 'Fit whole image'), ('fill', 'Stretch to frame'), ('scale-down', 'Scale down only')], default='cover', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image_fit_tablet',
            field=models.CharField(choices=[('cover', 'Fill frame (crop if needed)'), ('contain', 'Fit whole image'), ('fill', 'Stretch to frame'), ('scale-down', 'Scale down only')], default='cover', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image_position_desktop',
            field=models.CharField(default='center center', help_text='CSS object-position. Examples: center center, left center, 50% 35%.', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image_position_mobile',
            field=models.CharField(default='center center', help_text='CSS object-position for mobile.', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='image_position_tablet',
            field=models.CharField(default='center center', help_text='CSS object-position for tablet.', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='mobile_content_layout',
            field=models.CharField(choices=[('image_only', 'Image only on mobile (B&H style)'), ('overlay', 'Text over image'), ('below', 'Text below image')], default='image_only', help_text='Use image only when your mobile image already contains the text/buttons.', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='mobile_height',
            field=models.PositiveIntegerField(default=380, help_text='Mobile hero height in pixels. Around 360-420 gives a B&H-style mobile banner.', validators=[django.core.validators.MinValueValidator(180), django.core.validators.MaxValueValidator(900)]),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='tablet_height',
            field=models.PositiveIntegerField(default=460, help_text='Tablet hero height in pixels.', validators=[django.core.validators.MinValueValidator(160), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
