# Generated by Django 5.2.14 on 2026-05-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_hero_background_color_and_more'),
        ('hero_banners', '0003_herobanner_desktop_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='article_button_text',
            field=models.CharField(blank=True, default='Read Article', max_length=60),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='article_open_behavior',
            field=models.CharField(choices=[('same_page', 'Open in same page'), ('new_page', 'Open in new tab'), ('popup', 'Open in popup modal')], default='same_page', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='linked_article',
            field=models.ForeignKey(blank=True, help_text='Optional article opened from this hero banner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_banners', to='blog.blogpost'),
        ),
    ]
