# Generated by Django 5.2.14 on 2026-08-08 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_banners', '0006_herobanner_content_and_click_options'),
        ('products', '0034_productlistlowersection_productlisttrustbenefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='brand',
            field=models.ForeignKey(blank=True, help_text="Select a brand only when Placement is 'Brand Detail Page'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_banners', to='products.brand'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='placement',
            field=models.CharField(choices=[('home', 'Homepage'), ('brand_directory', 'Brands Directory'), ('brand_detail', 'Brand Detail Page')], db_index=True, default='home', help_text='Choose where this banner should appear. Existing banners remain Homepage banners.', max_length=30),
        ),
    ]
