# Generated by Django 5.2.14 on 2026-08-09 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_banners', '0007_herobanner_brand_herobanner_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='mobile_content_layout',
            field=models.CharField(choices=[('image_only', 'Image only on mobile (Arolana style)'), ('overlay', 'Text over image'), ('below', 'Text below image')], default='image_only', help_text='Use image only when your mobile image already contains the text/buttons.', max_length=20),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='mobile_height',
            field=models.PositiveIntegerField(default=380, help_text='Mobile hero height in pixels. Around 360-420 gives a Arolana-style mobile banner.', validators=[django.core.validators.MinValueValidator(180), django.core.validators.MaxValueValidator(900)]),
        ),
    ]
