# Generated by Django 5.2.14 on 2026-08-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_banners', '0008_alter_herobanner_mobile_content_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='desktop_content_layout',
            field=models.CharField(choices=[('standard', 'Standard — image with dynamic content'), ('image_only', 'Image only — uploaded artwork only')], default='standard', help_text='Standard displays Admin-managed title, description and CTA content over the image. Image only displays the uploaded artwork without the dynamic content layer on desktop.', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='tablet_content_layout',
            field=models.CharField(choices=[('standard', 'Standard — image with dynamic content'), ('image_only', 'Image only — uploaded artwork only')], default='standard', help_text='Standard displays Admin-managed title, description and CTA content over the image. Image only displays the uploaded artwork without the dynamic content layer on tablet.', max_length=20),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='mobile_content_layout',
            field=models.CharField(choices=[('standard', 'Standard — image with dynamic content'), ('image_only', 'Image only on mobile (Arolana style)'), ('overlay', 'Text over image'), ('below', 'Text below image')], default='image_only', help_text='Use image only when your mobile image already contains the text/buttons.', max_length=20),
        ),
    ]
