# Generated by Django 5.2.14 on 2026-05-30 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0017_category_hero_height_desktop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(blank=True, max_length=160)),
                ('phone_number', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileWishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='mobile_customers.mobilecustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_wishlist_items', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mobilecustomer',
            index=models.Index(fields=['phone_number'], name='mobile_cust_phone_n_2e0798_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilecustomer',
            index=models.Index(fields=['email'], name='mobile_cust_email_85b301_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilecustomer',
            index=models.Index(fields=['-created_at'], name='mobile_cust_created_e05fce_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilewishlistitem',
            index=models.Index(fields=['customer', '-created_at'], name='mobile_cust_custome_6c1f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilewishlistitem',
            index=models.Index(fields=['product', '-created_at'], name='mobile_cust_product_c80936_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mobilewishlistitem',
            unique_together={('customer', 'product')},
        ),
    ]
