# Generated by Django 5.2.14 on 2026-05-30 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecustomer',
            name='api_token',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mobilecustomer',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='mobilecustomer',
            index=models.Index(fields=['api_token'], name='mobile_cust_api_tok_780b40_idx'),
        ),
    ]
