# Generated by Django 5.2.14 on 2026-05-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_customers', '0002_mobilecustomer_api_token_mobilecustomer_pin_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilecustomer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_customers/profile_pictures/'),
        ),
    ]
