# Generated by Django 5.2.14 on 2026-07-10 05:57

import core.private_upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_customers', '0004_mobilecustomer_notification_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecustomer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_customers/profile_pictures/', validators=[core.private_upload_validation.PrivateUploadValidator('private_profile_image')]),
        ),
    ]
