# Generated by Django 5.2.14 on 2026-07-10 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_customers', '0005_alter_mobilecustomer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecustomer',
            name='api_token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=120),
        ),
        migrations.CreateModel(
            name='MobileCustomerAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('fingerprint', models.CharField(db_index=True, help_text='Non-secret prefix of the keyed token digest for support/audit use.', max_length=16)),
                ('device_name', models.CharField(blank=True, max_length=160)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_seen_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='mobile_customers.mobilecustomer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'revoked_at', 'expires_at'], name='mobtok_customer_state_idx'), models.Index(fields=['expires_at', 'revoked_at'], name='mobtok_expiry_state_idx')],
            },
        ),
    ]
