# Generated by Django 6.0.4 on 2026-04-30 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Summer Mega Sale!', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='Get up to 50% off on selected items + Free Shipping', max_length=500)),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_url', models.CharField(default='/products/?deals=true', max_length=500)),
                ('background_color_start', models.CharField(default='#3B82F6', help_text='Gradient start color', max_length=20)),
                ('background_color_end', models.CharField(default='#8B5CF6', help_text='Gradient end color', max_length=20)),
                ('left_image', models.URLField(blank=True, help_text='URL for left floating image')),
                ('right_image', models.URLField(blank=True, help_text='URL for right floating image')),
                ('center_image', models.URLField(blank=True, help_text='URL for center floating image')),
                ('left_animation', models.CharField(default='animate-bounce', max_length=50)),
                ('right_animation', models.CharField(default='animate-pulse', max_length=50)),
                ('center_animation', models.CharField(default='animate-spin-slow', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Banner',
                'verbose_name_plural': 'Homepage Banners',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(default='fas fa-folder-open', help_text='FontAwesome icon class', max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which categories appear')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Category',
                'verbose_name_plural': 'Homepage Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageManufacturerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(default='fas fa-industry', help_text='FontAwesome icon class', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Manufacturer Category',
                'verbose_name_plural': 'Homepage Manufacturer Categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageManufacturerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Top Manufacturers', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='Shop from trusted brands', max_length=500)),
                ('display_count', models.IntegerField(default=8, help_text='Number of manufacturers to show')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_featured_only', models.BooleanField(default=True, help_text='Show only featured manufacturers')),
            ],
            options={
                'verbose_name': 'Homepage Manufacturer Settings',
                'verbose_name_plural': 'Homepage Manufacturer Settings',
            },
        ),
        migrations.CreateModel(
            name='HomepageNewsletterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Subscribe to Our Newsletter', max_length=200)),
                ('subtitle', models.CharField(default='Get exclusive deals, new arrivals, and special offers directly to your inbox', max_length=500)),
                ('button_text', models.CharField(default='Subscribe', max_length=50)),
                ('background_color', models.CharField(default='#F3F4F6', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter Settings',
                'verbose_name_plural': 'Newsletter Settings',
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('section_type', models.CharField(choices=[('featured', 'Featured Products'), ('new', 'New Arrivals'), ('bestsellers', 'Best Sellers'), ('trending', 'Trending'), ('custom', 'Custom Section')], default='featured', max_length=20)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('display_order', models.IntegerField(default=0)),
                ('products_limit', models.IntegerField(default=8, help_text='Number of products to show')),
                ('view_all_url', models.CharField(blank=True, default='/products/', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageVendorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Top Rated Vendors', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='Our trusted partners', max_length=500)),
                ('vendor_count', models.IntegerField(default=8, help_text='Number of vendors to show')),
                ('autoplay_speed', models.IntegerField(default=3000, help_text='Autoplay speed in milliseconds')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Vendor Settings',
                'verbose_name_plural': 'Homepage Vendor Settings',
            },
        ),
        migrations.CreateModel(
            name='HomepageVideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Featured Video', help_text='Section title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Section subtitle', max_length=500)),
                ('video_source', models.CharField(choices=[('youtube', 'YouTube (Online)'), ('local', 'Local Video (MP4 - Works Offline)'), ('vimeo', 'Vimeo')], default='youtube', max_length=20)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video URL')),
                ('youtube_id', models.CharField(blank=True, help_text='YouTube video ID (auto-extracted)', max_length=100)),
                ('local_video', models.FileField(blank=True, help_text='Upload MP4 video file (works offline)', null=True, upload_to='homepage/videos/%Y/%m/', verbose_name='Local Video File')),
                ('poster_image', models.ImageField(blank=True, help_text='Poster/thumbnail image for video', null=True, upload_to='homepage/video_posters/%Y/%m/', verbose_name='Video Poster Image')),
                ('position', models.CharField(choices=[('left', 'Left Aligned'), ('center', 'Center Aligned'), ('right', 'Right Aligned')], default='center', max_length=20)),
                ('video_width', models.CharField(default='100%', help_text='Video width (e.g., 800, 100%, 80%)', max_length=20)),
                ('video_height', models.IntegerField(default=450, help_text='Video height in pixels')),
                ('autoplay', models.BooleanField(default=False, help_text='Auto-play video')),
                ('loop', models.BooleanField(default=False, help_text='Loop video')),
                ('show_controls', models.BooleanField(default=True, help_text='Show video controls')),
                ('modestbranding', models.BooleanField(default=True, help_text='Hide YouTube logo')),
                ('rel', models.BooleanField(default=False, help_text='Show related videos at end')),
                ('background_color', models.CharField(default='#F9FAFB', help_text='Section background color', max_length=20)),
                ('text_color', models.CharField(default='#1F2937', help_text='Text color', max_length=20)),
                ('button_text', models.CharField(blank=True, help_text='Optional button text', max_length=100)),
                ('button_url', models.CharField(blank=True, help_text='Button link URL', max_length=500)),
                ('button_color', models.CharField(default='#3B82F6', help_text='Button color', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Video Section',
                'verbose_name_plural': 'Homepage Video Sections',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Upload banner image', upload_to='homepage/banners/')),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center'), ('background', 'Background')], default='center', max_length=20)),
                ('animation', models.CharField(default='animate-bounce', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='homepage.homepagebanner')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
