# Generated by Django 5.2.14 on 2026-05-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagevideosection',
            name='info_position',
            field=models.CharField(choices=[('right', 'Info on Right'), ('left', 'Info on Left'), ('top', 'Info Above Video'), ('bottom', 'Info Below Video'), ('hidden', 'Hide Info')], default='right', help_text='Choose where title, subtitle, and button appear relative to the video.', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagevideosection',
            name='vimeo_id',
            field=models.CharField(blank=True, help_text='Vimeo video ID (auto-extracted)', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagevideosection',
            name='vimeo_url',
            field=models.URLField(blank=True, help_text='Vimeo video URL'),
        ),
    ]
