# Generated by Django 5.2.14 on 2026-05-16 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_homepagebanner_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebanner',
            name='background_fit',
            field=models.CharField(choices=[('cover', 'Fill frame (crop if needed)'), ('contain', 'Fit whole image'), ('fill', 'Stretch to frame'), ('scale-down', 'Scale down only')], default='cover', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='background_opacity',
            field=models.FloatField(default=0.35, help_text='0 is hidden, 1 is full strength. Image-only banners display at full strength.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='background_position',
            field=models.CharField(default='center center', help_text='CSS object-position. Examples: center center, left center, 50% 35%.', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='content_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='content_layout',
            field=models.CharField(choices=[('designed', 'Designed banner with text/images'), ('image_only', 'Image only')], default='designed', help_text='Choose image-only when the uploaded background already includes all text/buttons.', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='desktop_height',
            field=models.PositiveIntegerField(default=320, help_text='Homepage banner height on desktop in pixels.', validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(900)]),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='mobile_height',
            field=models.PositiveIntegerField(default=260, help_text='Homepage banner height on mobile in pixels.', validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(700)]),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='tablet_height',
            field=models.PositiveIntegerField(default=300, help_text='Homepage banner height on tablet in pixels.', validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(800)]),
        ),
        migrations.AddField(
            model_name='homepagebannerimage',
            name='height_px',
            field=models.PositiveIntegerField(blank=True, help_text='Optional custom display height in pixels.', null=True),
        ),
        migrations.AddField(
            model_name='homepagebannerimage',
            name='object_fit',
            field=models.CharField(choices=[('cover', 'Fill frame (crop if needed)'), ('contain', 'Fit whole image'), ('fill', 'Stretch to frame'), ('scale-down', 'Scale down only')], default='contain', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagebannerimage',
            name='object_position',
            field=models.CharField(default='center center', help_text='CSS object-position for this image.', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagebannerimage',
            name='width_px',
            field=models.PositiveIntegerField(blank=True, help_text='Optional custom display width in pixels.', null=True),
        ),
    ]
