# Generated by Django 5.2.14 on 2026-06-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_homepagevendorsection_admin_controls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagebanner',
            options={'ordering': ['placement', 'display_order', 'id'], 'verbose_name': 'Homepage Banner', 'verbose_name_plural': 'Homepage Banners'},
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='banner_style',
            field=models.CharField(choices=[('hero_slider', 'Hero slider'), ('wide_strip', 'Wide strip banner'), ('two_column', 'Two-column promo'), ('image_only', 'Image-only banner'), ('card_grid', 'Promo card/grid style')], default='hero_slider', help_text='Choose the visual structure for this banner.', max_length=30),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='full_width',
            field=models.BooleanField(default=False, help_text='Allow banner to stretch wider than the normal homepage container.'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='placement',
            field=models.CharField(choices=[('top', 'Top of homepage'), ('after_categories', 'After categories'), ('after_products', 'After product sections'), ('after_manufacturers', 'After manufacturers'), ('after_vendors', 'After vendor sections'), ('before_newsletter', 'Before newsletter'), ('custom', 'Custom/manual placement')], db_index=True, default='top', help_text='Choose where this banner should appear on the homepage.', max_length=40),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='show_on_homepage',
            field=models.BooleanField(db_index=True, default=True, help_text='Turn off if you want to keep this banner saved but hide it from the homepage.'),
        ),
    ]
