# Generated by Django 5.2.14 on 2026-06-11 16:56

import django.db.models.deletion
from django.db import migrations, models


def preserve_section_layouts(apps, schema_editor):
    HomepageSection = apps.get_model('homepage', 'HomepageSection')
    layout_by_type = {
        'trending': 'editorial',
        'featured': 'compact',
        'new': 'market_grid',
        'bestsellers': 'carousel',
        'custom': 'carousel',
    }
    for section_type, layout_style in layout_by_type.items():
        HomepageSection.objects.filter(section_type=section_type).update(
            layout_style=layout_style
        )


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_homepagebanner_options_and_more'),
        ('products', '0019_product_detail_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='accent_color',
            field=models.CharField(default='#0F2D6B', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='background_color',
            field=models.CharField(default='transparent', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Optional: limit this section to one brand.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_product_sections', to='products.brand'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional: limit this section to one category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_product_sections', to='products.category'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='empty_state_text',
            field=models.CharField(blank=True, default='No products available in this section yet.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='fill_automatically',
            field=models.BooleanField(default=True, help_text='Fill remaining slots automatically after curated products.'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='layout_style',
            field=models.CharField(choices=[('editorial', 'Editorial image slider'), ('compact', 'Compact two-row deals'), ('market_grid', 'Marketplace grid'), ('carousel', 'Product card carousel')], default='carousel', help_text='Controls the visual structure independently from the product source.', max_length=30),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='show_add_to_cart',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='show_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='show_rating',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='show_subscription_badge',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='show_vendor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='show_view_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='sort_mode',
            field=models.CharField(choices=[('automatic', 'Automatic for section type'), ('newest', 'Newest first'), ('best_selling', 'Best selling first'), ('trending', 'Most viewed and selling'), ('top_rated', 'Top rated first'), ('featured', 'Featured first'), ('price_low', 'Price: low to high'), ('price_high', 'Price: high to low')], default='automatic', help_text='Choose how automatically selected products are ordered.', max_length=30),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='use_subscription_priority',
            field=models.BooleanField(default=True, help_text='Give active higher-tier vendors stronger placement after curated products.'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='vendor_type',
            field=models.CharField(blank=True, choices=[('', 'All vendor types'), ('manufacturer', 'Manufacturers'), ('distributor', 'Distributors'), ('wholesaler', 'Wholesalers'), ('retailer', 'Retailers'), ('service_provider', 'Service providers')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='verified_vendors_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='view_all_text',
            field=models.CharField(blank=True, default='View All', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='products_limit',
            field=models.PositiveIntegerField(default=8, help_text='Number of products to show'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('featured', 'Featured Products'), ('new', 'New Arrivals'), ('bestsellers', 'Best Sellers'), ('trending', 'Trending Deals'), ('custom', 'Custom Section')], default='featured', max_length=20),
        ),
        migrations.CreateModel(
            name='HomepageSectionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_section_links', to='products.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='homepage.homepagesection')),
            ],
            options={
                'verbose_name': 'Curated Homepage Product',
                'verbose_name_plural': 'Curated Homepage Products',
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('section', 'product'), name='unique_homepage_section_product')],
            },
        ),
        migrations.RunPython(
            preserve_section_layouts,
            migrations.RunPython.noop,
        ),
    ]
