# Generated by Django 5.2.14 on 2026-06-08 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='page_background_blur',
            field=models.BooleanField(default=False, help_text='Softly blur the full-page background image.'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='page_background_fixed',
            field=models.BooleanField(default=True, help_text='Keep background image fixed while scrolling for a premium effect.'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='page_background_image',
            field=models.ImageField(blank=True, help_text='Optional full-page background image shown behind landing page sections.', null=True, upload_to='landing_pages/backgrounds/'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='page_background_overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.35, help_text='Background overlay opacity. Use 0.00 for clear image, 1.00 for very strong overlay.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='page_background_position',
            field=models.CharField(default='center center', help_text='CSS background position. Example: center center, top center, center right.', max_length=50),
        ),
    ]
