# Generated by Django 5.2.14 on 2026-06-08 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0002_landingpage_page_background_blur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='page_mobile_background_image',
            field=models.ImageField(blank=True, help_text='Mobile full-page background image. Recommended: 1080x1350 WebP or 1080x1920 WebP.', null=True, upload_to='landing_pages/backgrounds/mobile/'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='page_mobile_background_overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.45, help_text='Mobile overlay opacity. Mobile usually needs a slightly stronger overlay for readability.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='page_mobile_background_position',
            field=models.CharField(default='center center', help_text='Mobile CSS background position. Example: center center, top center, center right.', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='page_background_image',
            field=models.ImageField(blank=True, help_text='Optional full-page background image shown behind landing page sections.', null=True, upload_to='landing_pages/backgrounds/desktop/'),
        ),
    ]
