# Generated by Django 5.2.14 on 2026-05-31 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0004_deliveryrequest_is_ready_for_rider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pin_hash', models.CharField(blank=True, max_length=128)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_credential', to='deliveries.riderprofile')),
            ],
            options={
                'verbose_name': 'Rider mobile credential',
                'verbose_name_plural': 'Rider mobile credentials',
            },
        ),
        migrations.CreateModel(
            name='StaffMobileToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('rider', 'Rider')], max_length=20)),
                ('token', models.CharField(db_index=True, max_length=120, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=180)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_tokens', to='deliveries.riderprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_mobile_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['token', 'is_active'], name='staff_mobil_token_7d227a_idx'), models.Index(fields=['role', 'is_active'], name='staff_mobil_role_352e20_idx')],
            },
        ),
    ]
