# Generated by Django 5.2.14 on 2026-06-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmobiletoken',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('provider', 'Provider'), ('rider', 'Rider')], max_length=20),
        ),
    ]
