# Generated by Django 5.2.14 on 2026-08-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_publishing', '0002_socialpublication_deferred_video_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpublication',
            name='archive_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='socialpublication',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpublication',
            name='original_content_type_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='socialpublication',
            name='original_object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
