# Generated by Django 5.2.14 on 2026-08-25 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_publishing', '0003_socialpublication_archive_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConnectionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_role', models.CharField(blank=True, choices=[('vendor', 'Vendor'), ('provider', 'Service Provider'), ('admin', 'Arolana Admin')], max_length=20)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn')], db_index=True, max_length=20)),
                ('event', models.CharField(db_index=True, max_length=64)),
                ('external_identity_id', models.CharField(blank=True, max_length=255)),
                ('selected_destination_id', models.CharField(blank=True, max_length=255)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('provider_error_code', models.CharField(blank=True, max_length=120)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_audit_logs', to='social_publishing.socialaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_role', models.CharField(choices=[('vendor', 'Vendor'), ('provider', 'Service Provider'), ('admin', 'Arolana Admin')], max_length=20)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('session_binding_hash', models.CharField(blank=True, max_length=64)),
                ('mobile_launch_hash', models.CharField(blank=True, max_length=64)),
                ('safe_return_target', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pending_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('pending_scopes', models.JSONField(blank=True, default=list)),
                ('pending_destinations', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'expires_at', 'used_at'], name='social_publ_platfor_c97c13_idx')],
            },
        ),
    ]
