# Generated by Django 6.0.4 on 2026-04-30 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_links', to='products.product'),
        ),
        migrations.AddField(
            model_name='manufacturerproduct',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='manufacturerapplication',
            unique_together={('vendor', 'manufacturer')},
        ),
        migrations.AlterUniqueTogether(
            name='manufacturerproduct',
            unique_together={('manufacturer', 'product')},
        ),
    ]
