# Generated by Django 5.2.14 on 2026-05-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='priority_score',
            field=models.IntegerField(default=0, help_text='Higher score = better placement'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('plus', 'Plus'), ('pro', 'Pro'), ('special', 'Special'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
