# Generated by Django 5.2.14 on 2026-06-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_plan_admin_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_receive_callback_requests',
            field=models.BooleanField(default=False, help_text='Allow customers to request a callback without exposing the vendor phone.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_show_direct_contact_badge',
            field=models.BooleanField(default=False, help_text='Show premium direct-contact badge on storefronts and mobile.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_show_phone',
            field=models.BooleanField(default=False, help_text='Allow approved vendors on this plan to expose a direct phone number when the vendor also opts in.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_show_whatsapp',
            field=models.BooleanField(default=False, help_text='Allow approved vendors on this plan to expose WhatsApp when the vendor also opts in.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='hide_phone_until_click',
            field=models.BooleanField(default=True, help_text='Mask phone in listing payloads and reveal only through a tracked backend action.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='lead_tracking_enabled',
            field=models.BooleanField(default=False, help_text='Record phone/WhatsApp/callback leads for this plan.'),
        ),
    ]
