# Generated by Django 5.2.14 on 2026-06-18 16:02

from django.db import migrations


def seed_direct_contact_plan_permissions(apps, schema_editor):
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    tier_permissions = {
        'free': {},
        'basic': {},
        'plus': {
            'can_receive_callback_requests': True,
            'lead_tracking_enabled': True,
            'hide_phone_until_click': True,
        },
        'pro': {
            'can_receive_callback_requests': True,
            'lead_tracking_enabled': True,
            'hide_phone_until_click': True,
        },
        'special': {
            'can_show_phone': True,
            'can_show_whatsapp': True,
            'can_receive_callback_requests': True,
            'can_show_direct_contact_badge': True,
            'lead_tracking_enabled': True,
            'hide_phone_until_click': False,
        },
        'enterprise': {
            'can_show_phone': True,
            'can_show_whatsapp': True,
            'can_receive_callback_requests': True,
            'can_show_direct_contact_badge': True,
            'lead_tracking_enabled': True,
            'hide_phone_until_click': False,
        },
    }
    for plan in SubscriptionPlan.objects.all():
        tier = str(plan.name or '').strip().lower()
        tier = {'premium': 'pro', 'featured': 'special'}.get(tier, tier)
        permissions = tier_permissions.get(tier)
        if permissions is None:
            continue
        for field in [
            'can_show_phone',
            'can_show_whatsapp',
            'can_receive_callback_requests',
            'can_show_direct_contact_badge',
            'lead_tracking_enabled',
            'hide_phone_until_click',
        ]:
            if field in permissions:
                setattr(plan, field, permissions[field])
        plan.save(update_fields=list(permissions.keys()) or ['updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscriptionplan_can_receive_callback_requests_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_direct_contact_plan_permissions, migrations.RunPython.noop),
    ]
