# Generated by Django 5.2.14 on 2026-06-18 16:23

from django.db import migrations
from django.utils import timezone


LEGACY_TIER_MAP = {
    'premium': 'pro',
    'featured': 'special',
}

DEFAULT_LIMITS = {
    'free': {'max_products': 1, 'max_images_per_product': 3, 'max_variants_per_product': 0, 'priority_score': 0, 'support_level': 'basic', 'badge_level': 'Free Vendor'},
    'basic': {'max_products': 5, 'max_images_per_product': 5, 'max_variants_per_product': 2, 'priority_score': 20, 'support_level': 'basic', 'badge_level': 'Basic Vendor'},
    'plus': {'max_products': 20, 'max_images_per_product': 10, 'max_variants_per_product': 5, 'priority_score': 40, 'support_level': 'standard', 'badge_level': 'Plus Vendor'},
    'pro': {'max_products': 100, 'max_images_per_product': 10, 'max_variants_per_product': 20, 'priority_score': 65, 'support_level': 'priority', 'badge_level': 'Pro Vendor'},
    'special': {'max_products': 300, 'max_images_per_product': 10, 'max_variants_per_product': 50, 'priority_score': 85, 'support_level': 'priority', 'badge_level': 'Special Vendor'},
    'enterprise': {'max_products': -1, 'max_images_per_product': 30, 'max_variants_per_product': -1, 'priority_score': 100, 'support_level': 'dedicated', 'badge_level': 'Enterprise Vendor'},
}


def normalize_tier(value):
    tier = str(value or 'free').strip().lower()
    tier = LEGACY_TIER_MAP.get(tier, tier)
    return tier if tier in DEFAULT_LIMITS else 'free'


def plan_limits(plan):
    tier = normalize_tier(getattr(plan, 'name', None))
    limits = DEFAULT_LIMITS[tier].copy()
    field_map = {
        'max_products': 'max_products',
        'max_images_per_product': 'max_images_per_product',
        'max_variants_per_product': 'max_variants_per_product',
        'priority_score': 'priority_score',
        'support_level': 'support_level',
        'badge_level': 'badge_label',
    }
    for limit_key, plan_field in field_map.items():
        if hasattr(plan, plan_field):
            limits[limit_key] = getattr(plan, plan_field)
    for field in [
        'can_upload_video',
        'can_upload_pdf',
        'can_upload_certificates',
        'can_access_rfq',
        'can_receive_direct_enquiries',
        'can_use_boosting',
        'can_show_on_homepage',
        'can_access_analytics',
        'can_access_advanced_analytics',
        'can_access_ads',
    ]:
        limits[field] = bool(getattr(plan, field, False))
    return tier, limits


def apply_limits(profile, tier, limits):
    profile.subscription_tier = tier
    profile.product_limit = limits['max_products']
    profile.image_limit = limits['max_images_per_product']
    profile.variant_limit = limits['max_variants_per_product']
    profile.can_upload_video = limits.get('can_upload_video', False)
    profile.can_upload_pdf = limits.get('can_upload_pdf', False)
    profile.can_upload_certificates = limits.get('can_upload_certificates', False)
    profile.can_access_rfq = limits.get('can_access_rfq', False)
    profile.can_receive_direct_enquiries = limits.get('can_receive_direct_enquiries', False)
    profile.can_use_boosting = limits.get('can_use_boosting', False)
    profile.can_show_on_homepage = limits.get('can_show_on_homepage', False)
    profile.can_access_analytics = limits.get('can_access_analytics', tier != 'free')
    profile.can_access_advanced_analytics = limits.get('can_access_advanced_analytics', False)
    profile.can_access_ads = limits.get('can_access_ads', False)
    profile.priority_score = limits['priority_score']
    profile.support_level = limits['support_level']
    profile.badge_level = limits['badge_level']


def sync_existing_vendor_subscriptions(apps, schema_editor):
    VendorSubscription = apps.get_model('subscriptions', 'VendorSubscription')
    VendorProfile = apps.get_model('vendors', 'VendorProfile')
    now = timezone.now()

    VendorSubscription.objects.filter(is_active=True, end_date__lte=now).update(
        is_active=False,
        auto_renew=False,
        updated_at=now,
    )

    vendor_ids = set(VendorSubscription.objects.values_list('vendor_id', flat=True))
    vendor_ids.update(VendorProfile.objects.exclude(subscription_tier='free').values_list('user_id', flat=True))
    for profile in VendorProfile.objects.filter(user_id__in=vendor_ids):
        current = (
            VendorSubscription.objects
            .filter(vendor_id=profile.user_id, is_active=True, end_date__gt=now)
            .select_related('plan')
            .order_by('-end_date', '-created_at')
            .first()
        )
        if current:
            tier, limits = plan_limits(current.plan)
            profile.subscription_active = True
            profile.subscription_started_at = current.start_date
            profile.subscription_expires_at = current.end_date
            profile.subscription_expiry = current.end_date
            apply_limits(profile, tier, limits)
        else:
            tier = 'free'
            limits = DEFAULT_LIMITS[tier].copy()
            for field in [
                'can_upload_video',
                'can_upload_pdf',
                'can_upload_certificates',
                'can_access_rfq',
                'can_receive_direct_enquiries',
                'can_use_boosting',
                'can_show_on_homepage',
                'can_access_analytics',
                'can_access_advanced_analytics',
                'can_access_ads',
            ]:
                limits[field] = False
            limits['can_access_analytics'] = True
            profile.subscription_active = False
            profile.subscription_started_at = None
            profile.subscription_expires_at = None
            profile.subscription_expiry = None
            apply_limits(profile, tier, limits)
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_seed_direct_contact_plan_permissions'),
    ]

    operations = [
        migrations.RunPython(sync_existing_vendor_subscriptions, migrations.RunPython.noop),
    ]
