# Generated by Django 5.2.14 on 2026-06-18 16:33

from django.db import migrations
from django.utils import timezone


def clear_stale_free_subscription_active_flags(apps, schema_editor):
    VendorSubscription = apps.get_model('subscriptions', 'VendorSubscription')
    VendorProfile = apps.get_model('vendors', 'VendorProfile')
    now = timezone.now()
    active_vendor_ids = VendorSubscription.objects.filter(
        is_active=True,
        end_date__gt=now,
    ).values_list('vendor_id', flat=True)
    VendorProfile.objects.filter(
        subscription_tier='free',
        subscription_active=True,
    ).exclude(user_id__in=active_vendor_ids).update(
        subscription_active=False,
        subscription_started_at=None,
        subscription_expires_at=None,
        subscription_expiry=None,
        updated_at=now,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_sync_existing_vendor_subscriptions'),
    ]

    operations = [
        migrations.RunPython(clear_stale_free_subscription_active_flags, migrations.RunPython.noop),
    ]
