# Generated by Django 5.2.14 on 2026-07-14 11:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arolana_payments', '0004_paymenttransaction_gateway_capture_id_paymentrefund_and_more'),
        ('subscriptions', '0008_clear_stale_free_subscription_active_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=24)),
                ('new_status', models.CharField(blank=True, max_length=24)),
                ('source_platform', models.CharField(blank=True, max_length=30)),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=200)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('gateway', models.CharField(blank=True, max_length=40)),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('source_platform', models.CharField(blank=True, max_length=30)),
                ('verification_summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=100)),
                ('channel', models.CharField(default='in_app', max_length=20)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='role_entitlements',
            field=models.JSONField(blank=True, default=dict, help_text="Optional role-specific overrides keyed by vendor, manufacturer, or provider. The shared entitlement resolver merges these with Arolana's safe defaults."),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=12),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='grace_period_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='payment_state',
            field=models.CharField(db_index=True, default='paid', max_length=24),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='pending_change_effective_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='pending_change_type',
            field=models.CharField(blank=True, choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade')], max_length=16),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_account_subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='source_platform',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('pending_payment', 'Pending payment'), ('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('grace_period', 'Grace period'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=24),
        ),
        migrations.AddField(
            model_name='vendorsubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='vendorsubscription',
            index=models.Index(fields=['vendor', 'is_active', 'status', 'end_date'], name='subscriptio_vendor__2e9973_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorsubscription',
            index=models.Index(fields=['status', 'end_date'], name='subscriptio_status_09beb4_idx'),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_changes_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='new_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_history_new', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='previous_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_history_previous', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_events', to='subscriptions.vendorsubscription'),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_history_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payment_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payment_record', to='arolana_payments.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payments', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to='subscriptions.vendorsubscription'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionreminderlog',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='subscriptions.vendorsubscription'),
        ),
        migrations.AddIndex(
            model_name='subscriptionhistory',
            index=models.Index(fields=['user', 'event_type', '-created_at'], name='subscriptio_user_id_c3d01a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['user', 'status', '-created_at'], name='subscriptio_user_id_7535a1_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpayment',
            index=models.Index(fields=['plan', 'billing_cycle', 'status'], name='subscriptio_plan_id_65f67d_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionreminderlog',
            constraint=models.UniqueConstraint(fields=('subscription', 'event_key', 'channel'), name='unique_subscription_reminder_event_channel'),
        ),
    ]
