# Generated by Django 5.2.14 on 2026-07-10 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_clear_stale_free_subscription_active_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vendorsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_id', ''), _negated=True), fields=('transaction_id',), name='uniq_vendor_subscription_transaction_nonblank'),
        ),
    ]
