# Generated by Django 5.2.14 on 2026-07-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_vendorsubscription_uniq_vendor_subscription_transaction_nonblank'),
        ('subscriptions', '0010_consolidate_account_subscriptions'),
    ]

    operations = [
    ]
