# Generated by Django 5.2.14 on 2026-06-25 23:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0022_alter_productarticlelink_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=190, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='installers/categories/')),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('matching_keywords', models.TextField(blank=True, help_text='Comma-separated product/category keywords used for automatic matching.')),
                ('product_categories', models.ManyToManyField(blank=True, help_text='Products in these categories will suggest this service.', related_name='service_categories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business_name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('contact_person', models.CharField(max_length=160)),
                ('provider_type', models.CharField(choices=[('installer', 'Installer'), ('repair_engineer', 'Repair Engineer'), ('maintenance_technician', 'Maintenance Technician'), ('setup_specialist', 'Setup / Configuration Specialist'), ('trainer', 'Trainer'), ('consultant', 'Consultant')], max_length=40)),
                ('phone_number', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, preferably with country code.', regex='^\\+?[0-9][0-9\\s().-]{6,24}$')])),
                ('whatsapp_number', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, preferably with country code.', regex='^\\+?[0-9][0-9\\s().-]{6,24}$')])),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('service_coverage', models.CharField(blank=True, help_text='Cities, states, or regions this provider serves.', max_length=300)),
                ('description', models.TextField()),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('cac_number', models.CharField(blank=True, max_length=100)),
                ('government_id_upload', models.FileField(blank=True, null=True, upload_to='installers/verification/%Y/%m/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='installers/providers/%Y/%m/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('verification_note', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_completed_jobs', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_verified', '-average_rating', 'business_name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='installers/portfolio/%Y/%m/')),
                ('video_url', models.URLField(blank=True)),
                ('project_location', models.CharField(blank=True, max_length=180)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='installers.serviceproviderprofile')),
            ],
            options={
                'ordering': ['-completed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_services', to='installers.servicecategory')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='installers.serviceproviderprofile')),
            ],
            options={
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, preferably with country code.', regex='^\\+?[0-9][0-9\\s().-]{6,24}$')])),
                ('whatsapp', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, preferably with country code.', regex='^\\+?[0-9][0-9\\s().-]{6,24}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('service_needed', models.CharField(max_length=220)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='installers.servicecategory')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_quote_requests', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_quote_requests', to='products.product')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='installers.serviceproviderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('professionalism_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quality_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeliness_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reviews', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='installers.serviceproviderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='serviceproviderprofile',
            index=models.Index(fields=['verification_status', 'is_verified', 'is_active'], name='installers__verific_42c2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceproviderprofile',
            index=models.Index(fields=['country', 'state', 'city'], name='installers__country_b3e0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceproviderprofile',
            index=models.Index(fields=['provider_type', 'is_active'], name='installers__provide_a3ae07_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerservice',
            constraint=models.UniqueConstraint(fields=('provider', 'category', 'service_name'), name='unique_provider_service_name'),
        ),
        migrations.AddIndex(
            model_name='servicequoterequest',
            index=models.Index(fields=['status', '-created_at'], name='installers__status_8d5d52_idx'),
        ),
        migrations.AddIndex(
            model_name='servicequoterequest',
            index=models.Index(fields=['provider', 'status'], name='installers__provide_b53c5d_idx'),
        ),
    ]
