# Generated by Django 5.2.14 on 2026-06-25 23:52

from django.db import migrations, models


def create_homepage_section(apps, schema_editor):
    Section = apps.get_model("installers", "ServiceMarketplaceHomepageSection")
    Section.objects.get_or_create(
        title="Need installation, repair, or setup?",
        defaults={
            "subtitle": "Find verified Arolana installers, engineers, technicians, trainers, and consultants.",
            "eyebrow": "Verified professional services",
            "customer_button_text": "Find Verified Installers & Engineers",
            "provider_button_text": "Register as a Service Provider",
            "background_color": "#071A44",
            "accent_color": "#FF7A00",
            "display_order": 60,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMarketplaceHomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(default='Need installation, repair, or setup?', max_length=180)),
                ('subtitle', models.CharField(default='Find verified Arolana installers, engineers, technicians, trainers, and consultants.', max_length=500)),
                ('eyebrow', models.CharField(blank=True, default='Verified professional services', max_length=100)),
                ('customer_button_text', models.CharField(default='Find Verified Installers & Engineers', max_length=80)),
                ('provider_button_text', models.CharField(default='Register as a Service Provider', max_length=80)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='installers/homepage/')),
                ('background_color', models.CharField(default='#071A44', max_length=20)),
                ('accent_color', models.CharField(default='#FF7A00', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=60)),
            ],
            options={
                'verbose_name': 'Service Marketplace Homepage Section',
                'verbose_name_plural': 'Service Marketplace Homepage Section',
                'ordering': ['display_order'],
            },
        ),
        migrations.RunPython(create_homepage_section, migrations.RunPython.noop),
    ]
