# Generated by Django 5.2.14 on 2026-06-26 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_provider_statuses(apps, schema_editor):
    ServiceProviderProfile = apps.get_model('installers', 'ServiceProviderProfile')
    ServiceProviderProfile.objects.filter(verification_status='pending').update(verification_status='pending_review')
    ServiceProviderProfile.objects.filter(verification_status='approved', is_verified=True).update(verification_status='verified')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0002_servicemarketplacehomepagesection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderKYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('government_id', 'Government ID'), ('cac_certificate', 'CAC / Business Certificate'), ('address_proof', 'Address Proof'), ('selfie', 'Selfie / Profile Verification'), ('other', 'Other Document')], max_length=40)),
                ('file', models.FileField(upload_to='installers/kyc/%Y/%m/')),
                ('note', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('proposed_values', models.JSONField(blank=True, default=dict)),
                ('sensitive_fields', models.JSONField(blank=True, default=list)),
                ('proposed_file', models.FileField(blank=True, null=True, upload_to='installers/profile-change-requests/%Y/%m/')),
                ('proposed_file_field', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='allow_limited_jobs_without_kyc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='availability_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='availability_status',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('busy', 'Busy'), ('away', 'Away')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='bank_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='business_banner',
            field=models.ImageField(blank=True, null=True, upload_to='installers/providers/banners/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='business_hours',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='installers/providers/logos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='cac_certificate_upload',
            field=models.FileField(blank=True, null=True, upload_to='installers/verification/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='changes_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='changes_requested_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='kyc_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='kyc_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='kyc_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='last_sensitive_update_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='preferred_language',
            field=models.CharField(choices=[('english', 'English'), ('pidgin', 'Pidgin English'), ('yoruba', 'Yoruba'), ('igbo', 'Igbo'), ('hausa', 'Hausa'), ('french', 'French')], default='english', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='review_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='review_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_service_providers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='sensitive_update_cooldown_unlocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='subscription_plan',
            field=models.CharField(default='Free / Starter', max_length=80),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='subscription_status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('trial', 'Trial'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='support_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='support_whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='servicequoterequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicequoterequest',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicequoterequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicequoterequest',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_quote_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicequoterequest',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicequoterequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicequoterequest',
            name='contact_preference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='servicequoterequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicequoterequest',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicequoterequest',
            name='provider_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicequoterequest',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='provider_type',
            field=models.CharField(choices=[('installer', 'Installer'), ('repair_engineer', 'Repair Engineer'), ('maintenance_technician', 'Maintenance Technician'), ('consultant', 'Consultant'), ('training_provider', 'Training Provider'), ('av_engineer', 'AV Engineer'), ('cctv_security_installer', 'CCTV / Security Installer'), ('network_engineer', 'Network Engineer'), ('smart_home_installer', 'Smart Home Installer'), ('cinema_installer', 'Cinema Installer'), ('interactive_board_installer', 'Interactive Board Installer'), ('projector_technician', 'Projector Technician'), ('electrical_low_voltage_technician', 'Electrical / Low-voltage Technician'), ('rider_logistics_partner', 'Rider / Logistics Partner'), ('vendor_service_agent', 'Vendor Service Agent'), ('other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='verification_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_review', 'Pending review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('expired', 'Expired')], db_index=True, default='pending_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicequoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('under_review', 'Under review'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected_by_provider', 'Rejected by provider'), ('on_the_way', 'On the way'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('closed', 'Closed'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20),
        ),
        migrations.RunPython(normalize_provider_statuses, noop),
        migrations.AddIndex(
            model_name='serviceproviderprofile',
            index=models.Index(fields=['kyc_status', 'subscription_status'], name='installers__kyc_sta_82eb84_idx'),
        ),
        migrations.AddField(
            model_name='providerkycdocument',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='installers.serviceproviderprofile'),
        ),
        migrations.AddField(
            model_name='providerprofilechangerequest',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_change_requests', to='installers.serviceproviderprofile'),
        ),
        migrations.AddField(
            model_name='providerprofilechangerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_profile_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerprofilechangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_provider_profile_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='providerprofilechangerequest',
            index=models.Index(fields=['provider', 'status', '-created_at'], name='installers__provide_487232_idx'),
        ),
    ]
