# Generated by Django 5.2.14 on 2026-06-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0003_providerkycdocument_providerprofilechangerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicequoterequest',
            name='completion_photo',
            field=models.ImageField(blank=True, null=True, upload_to='installers/completions/%Y/%m/'),
        ),
    ]
