# Generated by Django 5.2.14 on 2026-06-27 21:26

from decimal import Decimal
from django.db import migrations, models


def seed_provider_plans(apps, schema_editor):
    plan_model = apps.get_model("installers", "ProviderSubscriptionPlan")
    plans = [
        {
            "name": "Free / Starter",
            "description": "Create a public provider profile and receive standard Arolana support.",
            "price_monthly": Decimal("0.00"),
            "price_yearly": Decimal("0.00"),
            "benefits": ["Public provider profile", "Standard support", "Portfolio and service listings"],
            "display_order": 10,
            "is_default": True,
        },
        {
            "name": "Standard",
            "description": "For active installers building visibility and a steady service history.",
            "price_monthly": Decimal("10000.00"),
            "price_yearly": Decimal("100000.00"),
            "benefits": ["Improved provider visibility", "Job notifications", "Provider analytics"],
            "display_order": 20,
        },
        {
            "name": "Premium",
            "description": "Enhanced visibility and support for established service businesses.",
            "price_monthly": Decimal("25000.00"),
            "price_yearly": Decimal("250000.00"),
            "benefits": ["Priority visibility", "Priority support", "Enhanced provider profile"],
            "display_order": 30,
        },
        {
            "name": "Verified Pro",
            "description": "Professional provider access for verified engineers and installation teams.",
            "price_monthly": Decimal("50000.00"),
            "price_yearly": Decimal("500000.00"),
            "benefits": ["Verified Pro badge", "Serious job eligibility", "Priority matching and support"],
            "display_order": 40,
        },
        {
            "name": "Enterprise",
            "description": "Custom operations support for large service companies and national teams.",
            "price_monthly": Decimal("100000.00"),
            "price_yearly": Decimal("1000000.00"),
            "benefits": ["Enterprise badge", "Dedicated support", "Custom coverage and assignment support"],
            "display_order": 50,
        },
    ]
    for plan in plans:
        name = plan.pop("name")
        plan_model.objects.update_or_create(name=name, defaults=plan)


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0004_servicequoterequest_completion_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_order', 'price_monthly', 'name'],
            },
        ),
        migrations.RunPython(seed_provider_plans, migrations.RunPython.noop),
    ]
