# Generated by Django 5.2.14 on 2026-07-05 14:51

import core.image_protection
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from django.utils.text import slugify


def backfill_existing_projects(apps, schema_editor):
    ServicePortfolio = apps.get_model("installers", "ServicePortfolio")
    ProviderService = apps.get_model("installers", "ProviderService")
    now = timezone.now()
    for project in ServicePortfolio.objects.select_related("provider").all().iterator():
        base = slugify(
            " ".join(
                value for value in [
                    project.title,
                    getattr(project.provider, "city", ""),
                    getattr(project.provider, "business_name", ""),
                ]
                if value
            )
        )[:205] or "arolana-project"
        category_id = (
            ProviderService.objects
            .filter(provider_id=project.provider_id, is_active=True)
            .values_list("category_id", flat=True)
            .first()
        )
        project.slug = f"{base}-{uuid.uuid4().hex[:8]}"
        project.approval_status = "approved"
        project.is_active = True
        project.published_at = project.created_at or now
        project.created_by_id = getattr(project.provider, "user_id", None)
        project.country = getattr(project.provider, "country", "") or ""
        project.state = getattr(project.provider, "state", "") or ""
        project.city = getattr(project.provider, "city", "") or ""
        project.location_display = project.project_location or ", ".join(
            value for value in [project.city, project.state, project.country] if value
        )
        project.service_category_id = category_id
        project.save(update_fields=[
            "slug", "approval_status", "is_active", "published_at", "created_by",
            "country", "state", "city", "location_display", "service_category",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0005_providersubscriptionplan'),
        ('products', '0026_product_draft_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedServiceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProjectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'View'), ('video_view', 'Video view'), ('product_click', 'Product click'), ('provider_click', 'Provider click'), ('share', 'Share'), ('save', 'Save'), ('quote_request', 'Quote request')], db_index=True, max_length=30)),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('before_image', 'Before image'), ('after_image', 'After image'), ('progress_image', 'Progress image'), ('document', 'Document')], db_index=True, default='image', max_length=24)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('installers/projects/gallery'))),
                ('video', models.FileField(blank=True, null=True, upload_to='installers/projects/videos/%Y/%m/')),
                ('external_video_url', models.URLField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('installers/projects/thumbnails'))),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('alt_text', models.CharField(blank=True, max_length=220)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProjectModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=24)),
                ('new_status', models.CharField(max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProjectProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_note', models.CharField(blank=True, max_length=500)),
                ('quantity_used', models.PositiveIntegerField(default=1)),
                ('is_primary_product', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=120)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='serviceportfolio',
            options={'ordering': ['-is_featured', '-published_at', '-completed_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('approved', 'Approved'), ('requires_changes', 'Requires changes'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='draft', max_length=24),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='challenge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='customer_consent_to_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='customer_name_display',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='customer_name_private',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='customer_outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('private', 'Private customer'), ('business', 'Business'), ('government', 'Government'), ('education', 'Education'), ('religious', 'Religious organization'), ('nonprofit', 'Nonprofit'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='implementation_process',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='is_verified_project',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='local_video',
            field=models.FileField(blank=True, null=True, upload_to='installers/projects/videos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='location_display',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='moderation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='product_click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='project_duration_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='project_result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='project_type',
            field=models.CharField(choices=[('installation', 'Installation'), ('repair', 'Repair'), ('maintenance', 'Maintenance'), ('consulting', 'Consulting'), ('deployment', 'Deployment'), ('training', 'Training'), ('before_after', 'Before and after'), ('other', 'Other')], db_index=True, default='installation', max_length=30),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='project_value_currency',
            field=models.CharField(default='NGN', max_length=8),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='project_value_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='project_value_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='provider_click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='quote_requests_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='saves_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='installers.servicecategory'),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='services_performed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='shares_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='short_summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='show_project_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='slug',
            field=models.SlugField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='technologies_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='video_duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds.'),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='video_source',
            field=models.CharField(choices=[('none', 'No video'), ('youtube', 'YouTube'), ('external', 'External video'), ('upload', 'Arolana upload')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('installers/projects/video-thumbnails')),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='video_views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceportfolio',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_existing_projects, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='serviceportfolio',
            name='slug',
            field=models.SlugField(blank=True, max_length=240, unique=True),
        ),
        migrations.AddField(
            model_name='servicequoterequest',
            name='source_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='installers.serviceportfolio'),
        ),
        migrations.AlterField(
            model_name='serviceportfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('installers/portfolio')),
        ),
        migrations.AddIndex(
            model_name='serviceportfolio',
            index=models.Index(fields=['approval_status', 'is_active', '-published_at'], name='installers__approva_809920_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceportfolio',
            index=models.Index(fields=['service_category', 'approval_status', '-completed_at'], name='installers__service_e9815d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceportfolio',
            index=models.Index(fields=['country', 'state', 'city'], name='installers__country_cf481f_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceportfolio',
            index=models.Index(fields=['provider', 'approval_status', '-created_at'], name='installers__provide_0f0313_idx'),
        ),
        migrations.AddField(
            model_name='savedserviceproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='installers.serviceportfolio'),
        ),
        migrations.AddField(
            model_name='savedserviceproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_service_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceprojectevent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='installers.serviceportfolio'),
        ),
        migrations.AddField(
            model_name='serviceprojectevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceprojectmedia',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='installers.serviceportfolio'),
        ),
        migrations.AddField(
            model_name='serviceprojectmoderationlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceprojectmoderationlog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_history', to='installers.serviceportfolio'),
        ),
        migrations.AddField(
            model_name='serviceprojectproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_projects', to='products.product'),
        ),
        migrations.AddField(
            model_name='serviceprojectproduct',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_products', to='installers.serviceportfolio'),
        ),
        migrations.AddField(
            model_name='serviceprojectreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='installers.serviceportfolio'),
        ),
        migrations.AddField(
            model_name='serviceprojectreport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='savedserviceproject',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_saved_service_project'),
        ),
        migrations.AddIndex(
            model_name='serviceprojectevent',
            index=models.Index(fields=['project', 'event_type', '-created_at'], name='installers__project_0583e0_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprojectmedia',
            index=models.Index(fields=['project', 'approval_status', 'display_order'], name='installers__project_a57bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprojectmedia',
            index=models.Index(fields=['media_type', 'approval_status'], name='installers__media_t_b536fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceprojectproduct',
            constraint=models.UniqueConstraint(fields=('project', 'product'), name='unique_project_product'),
        ),
    ]
