# Generated by Django 5.2.14 on 2026-07-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0006_savedserviceproject_serviceprojectevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemarketplacehomepagesection',
            name='projects_button_text',
            field=models.CharField(default='Explore Completed Projects', max_length=80),
        ),
        migrations.AddField(
            model_name='servicemarketplacehomepagesection',
            name='projects_enabled',
            field=models.BooleanField(default=True, help_text='Show approved professional projects on the marketplace homepage.'),
        ),
        migrations.AddField(
            model_name='servicemarketplacehomepagesection',
            name='projects_eyebrow',
            field=models.CharField(blank=True, default='Real Arolana professional work', max_length=100),
        ),
        migrations.AddField(
            model_name='servicemarketplacehomepagesection',
            name='projects_limit',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='servicemarketplacehomepagesection',
            name='projects_subtitle',
            field=models.CharField(default='Explore verified installations, repairs, equipment deployments, and customer outcomes.', max_length=500),
        ),
        migrations.AddField(
            model_name='servicemarketplacehomepagesection',
            name='projects_title',
            field=models.CharField(default='Projects & Proof Network', max_length=180),
        ),
    ]
