# Generated by Django 5.2.14 on 2026-07-06 10:01

import core.image_protection
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0007_servicemarketplacehomepagesection_projects_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderprofile',
            name='business_hours_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured opening hours keyed by weekday.'),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='availability_status',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('busy', 'Busy'), ('unavailable', 'Unavailable'), ('vacation', 'Vacation'), ('away', 'Away')], default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='business_banner',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('installers/providers/banners')),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('installers/providers/logos')),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('installers/providers/profiles')),
        ),
    ]
