# Generated by Django 5.2.14 on 2026-07-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0008_serviceproviderprofile_business_hours_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersubscriptionplan',
            name='is_deprecated',
            field=models.BooleanField(default=True, help_text='Deprecated catalogs cannot activate or price subscriptions.'),
        ),
        migrations.AddField(
            model_name='providersubscriptionplan',
            name='official_tier_key',
            field=models.CharField(blank=True, choices=[('', 'Not mapped'), ('free', 'Free'), ('basic', 'Basic'), ('plus', 'Plus'), ('pro', 'Pro'), ('special', 'Special'), ('enterprise', 'Enterprise')], db_index=True, default='', help_text='Compatibility mapping to the official account-level tier.', max_length=20),
        ),
    ]
