# Generated by Django 5.2.14 on 2026-07-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0008_serviceproviderprofile_business_hours_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprojectmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('before_image', 'Before image'), ('during_image', 'During image'), ('after_image', 'After image'), ('progress_image', 'Progress image'), ('document', 'Document')], db_index=True, default='image', max_length=24),
        ),
    ]
