# Generated by Django 5.2.14 on 2026-07-10 05:57

import core.private_upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0009_alter_serviceprojectmedia_media_type'),
        ('products', '0030_alter_productreview_video_review_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='serviceprojectproduct',
            name='unique_project_product',
        ),
        migrations.AlterField(
            model_name='providerkycdocument',
            name='file',
            field=models.FileField(upload_to='installers/kyc/%Y/%m/', validators=[core.private_upload_validation.PrivateUploadValidator('kyc')]),
        ),
        migrations.AlterField(
            model_name='providerprofilechangerequest',
            name='proposed_file',
            field=models.FileField(blank=True, null=True, upload_to='installers/profile-change-requests/%Y/%m/', validators=[core.private_upload_validation.PrivateUploadValidator('sensitive_profile_file')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='cac_certificate_upload',
            field=models.FileField(blank=True, null=True, upload_to='installers/verification/%Y/%m/', validators=[core.private_upload_validation.PrivateUploadValidator('kyc')]),
        ),
        migrations.AlterField(
            model_name='serviceproviderprofile',
            name='government_id_upload',
            field=models.FileField(blank=True, null=True, upload_to='installers/verification/%Y/%m/', validators=[core.private_upload_validation.PrivateUploadValidator('kyc')]),
        ),
        migrations.AlterField(
            model_name='servicequoterequest',
            name='completion_photo',
            field=models.ImageField(blank=True, null=True, upload_to='installers/completions/%Y/%m/', validators=[core.private_upload_validation.PrivateUploadValidator('private_profile_image')]),
        ),
        migrations.AddConstraint(
            model_name='serviceprojectproduct',
            constraint=models.UniqueConstraint(fields=('project', 'product'), name='unique_service_project_product'),
        ),
    ]
