# Generated by Django 5.2.14 on 2026-07-15 12:43

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0009_providersubscriptionplan_is_deprecated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerservice',
            name='short_description',
            field=models.CharField(blank=True, help_text='A compact customer-facing summary used on service cards.', max_length=240),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Explain what is included, the customers served, supported systems, and relevant experience.', verbose_name='Service description'),
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['provider', 'is_active'], name='installers__provide_40ca27_idx'),
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['category', 'is_active'], name='installers__categor_33ce84_idx'),
        ),
        migrations.AddIndex(
            model_name='providerservice',
            index=models.Index(fields=['-created_at'], name='installers__created_1728a2_idx'),
        ),
    ]
