# Generated by Django 5.2.14 on 2026-07-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0010_providerservice_short_description_and_more'),
        ('installers', '0010_remove_serviceprojectproduct_unique_project_product_and_more'),
    ]

    operations = [
    ]
