# Generated by Django 5.2.14 on 2026-07-16 04:10

import core.image_protection
import core.private_upload_validation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installers', '0011_merge_20260715_2219'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='serviceprojectmedia',
            name='installers__media_t_b536fd_idx',
        ),
        migrations.AddField(
            model_name='serviceprojectmedia',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=core.image_protection.ProtectedFileUploadPath('installers/projects/documents'), validators=[core.private_upload_validation.PublicUploadValidator('project_document')]),
        ),
        migrations.AddField(
            model_name='serviceprojectmedia',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceprojectmedia',
            name='is_cover',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='serviceprojectmedia',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='serviceprojectmedia',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceprojectmedia',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='serviceprojectmedia',
            name='processed_video',
            field=models.FileField(blank=True, null=True, upload_to=core.image_protection.ProtectedFileUploadPath('installers/projects/videos/processed'), validators=[core.private_upload_validation.PublicUploadValidator('project_video')]),
        ),
        migrations.AddField(
            model_name='serviceprojectmedia',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceprojectmedia',
            name='processing_status',
            field=models.CharField(choices=[('none', 'Not required'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceprojectmedia',
            name='stage',
            field=models.CharField(choices=[('general', 'General'), ('cover', 'Cover'), ('before', 'Before'), ('progress', 'Progress'), ('installation', 'Installation'), ('repair_diagnosis', 'Repair diagnosis'), ('repair_process', 'Repair process'), ('testing', 'Testing'), ('commissioning', 'Commissioning'), ('after', 'After'), ('final_result', 'Final result'), ('walkthrough', 'Walkthrough'), ('customer_testimonial', 'Customer testimonial'), ('supporting_document', 'Supporting document')], db_index=True, default='general', max_length=32),
        ),
        migrations.AddField(
            model_name='serviceprojectmedia',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_service_project_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceprojectmedia',
            name='video_duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds when known.'),
        ),
        migrations.AlterField(
            model_name='serviceprojectmedia',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_changes', 'Requires changes')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprojectmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], db_index=True, default='image', max_length=24),
        ),
        migrations.AlterField(
            model_name='serviceprojectmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=core.image_protection.ProtectedFileUploadPath('installers/projects/videos'), validators=[core.private_upload_validation.PublicUploadValidator('project_video')]),
        ),
        migrations.AddIndex(
            model_name='serviceprojectmedia',
            index=models.Index(fields=['media_type', 'stage', 'approval_status'], name='installers__media_t_6f9183_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprojectmedia',
            index=models.Index(fields=['project', 'is_cover', 'is_featured'], name='installers__project_f1dafc_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprojectmedia',
            index=models.Index(fields=['project', 'created_at'], name='installers__project_f1cc48_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceprojectmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('project',), name='unique_service_project_cover_media'),
        ),
    ]
