# Generated by Django 6.0.4 on 2026-04-30 12:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise'), ('featured', 'Featured')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_limit', models.IntegerField(default=10)),
                ('featured_products', models.IntegerField(default=0)),
                ('priority_support', models.BooleanField(default=False)),
                ('analytics_access', models.BooleanField(default=False)),
                ('promoted_listing', models.BooleanField(default=False)),
                ('dedicated_account_manager', models.BooleanField(default=False)),
                ('icon', models.CharField(default='fa-store', max_length=50)),
                ('color', models.CharField(default='blue', max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store_name', models.CharField(max_length=200)),
                ('store_slug', models.SlugField(unique=True)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/')),
                ('store_banner', models.ImageField(blank=True, null=True, upload_to='vendors/banners/')),
                ('description', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_documents', models.FileField(blank=True, null=True, upload_to='vendors/documents/')),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise'), ('featured', 'Featured')], default='free', max_length=20)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('priority_score', models.IntegerField(default=0, help_text='Higher score = better placement')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_sales', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('response_time', models.CharField(blank=True, default='< 1 hour', max_length=50)),
                ('fulfillment_rate', models.DecimalField(decimal_places=2, default=99.5, max_digits=5)),
                ('return_rate', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_trusted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_score', '-subscription_tier', '-rating_avg', '-total_sales'],
            },
        ),
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorsubscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_vendors', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='vendors.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'vendor')},
            },
        ),
    ]
