# Generated by Django 5.2.14 on 2026-05-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('plus', 'Plus'), ('pro', 'Pro'), ('special', 'Special'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorsubscriptionplan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('plus', 'Plus'), ('pro', 'Pro'), ('special', 'Special'), ('enterprise', 'Enterprise')], max_length=20, unique=True),
        ),
    ]
