# Generated by Django 5.2.14 on 2026-05-19 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendorprofile_subscription_tier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('comment', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified_customer', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_store_reviews', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_reviews', to='vendors.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'is_active', '-created_at'], name='vendors_ven_vendor__97346b_idx'), models.Index(fields=['rating'], name='vendors_ven_rating_f726c7_idx')],
                'unique_together': {('vendor', 'user')},
            },
        ),
    ]
