# Generated by Django 5.2.14 on 2026-05-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorreview',
            unique_together=set(),
        ),
    ]
