# Generated by Django 5.2.14 on 2026-05-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_alter_vendorreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='pickup_address',
            field=models.TextField(blank=True, help_text='Exact store/warehouse pickup address used for checkout delivery pricing.'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pickup_contact_name',
            field=models.CharField(blank=True, help_text='Name riders should ask for at pickup. Defaults to store name when blank.', max_length=160),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Pickup map latitude for exact rider distance pricing.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Pickup map longitude for exact rider distance pricing.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pickup_phone',
            field=models.CharField(blank=True, help_text='Phone number riders should call at pickup.', max_length=50),
        ),
    ]
