# Generated by Django 5.2.14 on 2026-05-31 19:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productwholesaletier_product_bulk_price_and_more'),
        ('vendors', '0005_vendorprofile_pickup_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_name', models.CharField(max_length=180)),
                ('account_name', models.CharField(max_length=180)),
                ('account_number', models.CharField(max_length=80)),
                ('bank_country', models.CharField(choices=[('nigeria', 'Nigeria'), ('china', 'China'), ('usa', 'USA'), ('uk', 'UK'), ('canada', 'Canada'), ('other', 'Other')], default='nigeria', max_length=30)),
                ('swift_code', models.CharField(blank=True, max_length=40)),
                ('iban', models.CharField(blank=True, max_length=80)),
                ('routing_number', models.CharField(blank=True, max_length=80)),
                ('sort_code', models.CharField(blank=True, max_length=80)),
                ('bank_address', models.TextField(blank=True)),
                ('preferred_currency', models.CharField(default='NGN', max_length=10)),
                ('is_default', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorFactoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='vendors/factory/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorRFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('delivery_location', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20)),
                ('quote_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quote_lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_note', models.TextField(blank=True)),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('order_earning', 'Order Earning'), ('commission_deduction', 'Commission Deduction'), ('withdrawal_request', 'Withdrawal Request'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('subscription_payment', 'Subscription Payment')], db_index=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('withdrawable_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('admin_note', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendor_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='export_countries',
            field=models.TextField(blank=True, help_text='Comma-separated export countries or regions.'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='factory_name',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='factory_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='main_product_categories',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='manufacturer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='manufacturer_badge_label',
            field=models.CharField(blank=True, default='Verified Manufacturer', max_length=80),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='manufacturer_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='number_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='production_capacity',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='quality_control_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='support_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('service_provider', 'Service Provider')], db_index=True, default='retailer', max_length=30),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='warehouse_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='years_in_business',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['vendor_type', 'approval_status'], name='vendors_ven_vendor__0a24cf_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['manufacturer_verified', '-priority_score'], name='vendors_ven_manufac_d149e8_idx'),
        ),
        migrations.AddField(
            model_name='vendorbankaccount',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='vendorbankaccount',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vendor_bank_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorfactoryphoto',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_photos', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='vendorrfq',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_rfqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorrfq',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='products.product'),
        ),
        migrations.AddField(
            model_name='vendorrfq',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='vendortransaction',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='vendorwallet',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='vendortransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vendors.vendorwallet'),
        ),
        migrations.AddField(
            model_name='vendorwithdrawal',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='vendors.vendorbankaccount'),
        ),
        migrations.AddField(
            model_name='vendorwithdrawal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vendor_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorwithdrawal',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='vendors.vendorprofile'),
        ),
        migrations.AddIndex(
            model_name='vendorbankaccount',
            index=models.Index(fields=['vendor', 'is_default'], name='vendors_ven_vendor__5ff83e_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbankaccount',
            index=models.Index(fields=['vendor', 'is_verified'], name='vendors_ven_vendor__5872cf_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorrfq',
            index=models.Index(fields=['vendor', 'status'], name='vendors_ven_vendor__c409bf_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorrfq',
            index=models.Index(fields=['status', '-created_at'], name='vendors_ven_status_2b9430_idx'),
        ),
        migrations.AddIndex(
            model_name='vendortransaction',
            index=models.Index(fields=['vendor', '-created_at'], name='vendors_ven_vendor__a02fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='vendortransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='vendors_ven_transac_b83242_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorwithdrawal',
            index=models.Index(fields=['vendor', 'status'], name='vendors_ven_vendor__4dddb7_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorwithdrawal',
            index=models.Index(fields=['status', '-requested_at'], name='vendors_ven_status_7cef4b_idx'),
        ),
    ]
