# Generated by Django 5.2.14 on 2026-06-18 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_detail_config'),
        ('vendors', '0010_vendorprofile_preferred_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='allow_callback_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='allow_phone_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='allow_whatsapp_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='business_phone',
            field=models.CharField(blank=True, help_text='Customer-facing business phone. Exposed only when vendor and subscription permissions allow it.', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Customer-facing WhatsApp number. Exposed only when vendor and subscription permissions allow it.', max_length=50),
        ),
        migrations.CreateModel(
            name='VendorCallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_name', models.CharField(blank=True, max_length=180)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('contacted', 'Contacted'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vendor_callback_requests', to=settings.AUTH_USER_MODEL)),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_callback_requests', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_callback_requests', to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_requests', to='vendors.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status', '-created_at'], name='vendors_ven_vendor__457a8e_idx'), models.Index(fields=['customer_phone', '-created_at'], name='vendors_ven_custome_7c637c_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_type', models.CharField(choices=[('callback_request', 'Callback request'), ('phone_reveal', 'Phone reveal'), ('phone_call', 'Phone call'), ('whatsapp_click', 'WhatsApp click'), ('chat_click', 'Chat click')], db_index=True, max_length=40)),
                ('customer_name', models.CharField(blank=True, max_length=180)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_contact_leads', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_contact_leads', to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_leads', to='vendors.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'action_type', '-created_at'], name='vendors_ven_vendor__aeca4e_idx'), models.Index(fields=['product', '-created_at'], name='vendors_ven_product_147b62_idx')],
            },
        ),
    ]
