# Generated by Django 5.2.14 on 2026-06-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_vendorprofile_allow_callback_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorlead',
            name='action_type',
            field=models.CharField(choices=[('callback_request', 'Callback request'), ('phone_reveal', 'Phone reveal'), ('phone_call', 'Phone call'), ('call_click', 'Call click'), ('whatsapp_click', 'WhatsApp click'), ('product_link_shared_to_whatsapp', 'Product link shared to WhatsApp'), ('chat_click', 'Chat click')], db_index=True, max_length=40),
        ),
    ]
