# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_alter_vendorlead_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlead',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='currency',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='guest_session_key',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='page_url',
            field=models.URLField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='product_url',
            field=models.URLField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='vendorlead',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='vendorlead',
            name='action_type',
            field=models.CharField(choices=[('callback_request', 'Callback request'), ('phone_reveal', 'Phone reveal'), ('phone_call', 'Phone call'), ('call_click', 'Call click'), ('whatsapp_click', 'WhatsApp click'), ('product_link_shared_to_whatsapp', 'Product link shared to WhatsApp'), ('chat_started', 'Chat started'), ('chat_message_sent', 'Chat message sent'), ('chat_click', 'Chat click'), ('add_to_cart', 'Add to cart'), ('buy_now_click', 'Buy now click'), ('checkout_started', 'Checkout started'), ('order_created', 'Order created')], db_index=True, max_length=40),
        ),
    ]
