# Generated by Django 5.2.14 on 2026-06-19 14:40

from django.db import migrations, models


def backfill_known_vendor_locations(apps, schema_editor):
    VendorProfile = apps.get_model('vendors', 'VendorProfile')

    VendorProfile.objects.filter(store_name__iexact='Cyfex Limited').update(
        address_line_1='Ikeja, Lagos',
        city='Ikeja',
        state='Lagos',
        country='Nigeria',
        is_verified=True,
        subscription_tier='enterprise',
        subscription_active=True,
        badge_level='Enterprise Vendor',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_vendorlead_tracking_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.RunPython(backfill_known_vendor_locations, migrations.RunPython.noop),
    ]
