# Generated by Django 5.2.14 on 2026-06-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_vendorprofile_address_line_1_vendorprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='business_hours',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='delivery_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='featured_categories',
            field=models.TextField(blank=True, help_text='Featured storefront categories, one per line.'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='featured_products_note',
            field=models.TextField(blank=True, help_text='Optional featured product notes for the storefront.'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='return_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='store_gallery_notes',
            field=models.TextField(blank=True, help_text='Optional storefront gallery image URLs or notes, one per line.'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='store_slogan',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='store_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='storefront_accent_color',
            field=models.CharField(blank=True, default='#FF7A00', help_text='Storefront accent color. Example: #FF7A00.', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='warranty_note',
            field=models.TextField(blank=True),
        ),
    ]
