# Generated by Django 5.2.14 on 2026-07-10 05:57

import core.private_upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_vendorprofile_business_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='verification_documents',
            field=models.FileField(blank=True, null=True, upload_to='vendors/documents/', validators=[core.private_upload_validation.PrivateUploadValidator('kyc')]),
        ),
    ]
