# Generated by Django 5.2.14 on 2026-07-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_alter_vendorprofile_verification_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Pickup map latitude for exact rider distance pricing.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Pickup map longitude for exact rider distance pricing.', max_digits=12, null=True),
        ),
    ]
