# Generated by Django 5.2.14 on 2026-05-30 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_ai', '0002_searchanalytics_user_alter_searchanalytics_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.CharField(blank=True, max_length=200)),
                ('transcript', models.CharField(max_length=500)),
                ('ai_reply', models.TextField(blank=True)),
                ('results_count', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='searchanalytics',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='category',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='intent',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['intent'], name='search_ai_s_intent_545f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['category'], name='search_ai_s_categor_bf14ac_idx'),
        ),
        migrations.AddField(
            model_name='voicesearchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='voicesearchlog',
            index=models.Index(fields=['transcript'], name='search_ai_v_transcr_06bb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='voicesearchlog',
            index=models.Index(fields=['-created_at'], name='search_ai_v_created_214a6e_idx'),
        ),
    ]
