# Generated by Django 5.2.14 on 2026-07-20 15:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI')], default='openai', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('base_url', models.URLField(blank=True)),
                ('api_key_env_var', models.CharField(default='OPENAI_API_KEY', max_length=80)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIToolDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=120, unique=True)),
                ('feature', models.CharField(db_index=True, max_length=80)),
                ('description', models.TextField()),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('requires_human_approval', models.BooleanField(default=False)),
                ('safe_serializer', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['feature', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, db_index=True, max_length=30)),
                ('feature', models.CharField(blank=True, db_index=True, max_length=80)),
                ('action', models.CharField(choices=[('provider_request', 'Provider request'), ('tool_call', 'Tool call'), ('redaction', 'Redaction'), ('quota_check', 'Quota check'), ('policy_block', 'Policy block'), ('configuration_change', 'Configuration change')], db_index=True, max_length=40)),
                ('object_label', models.CharField(blank=True, max_length=160)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('safe_summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIDataBoundaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('model_label', models.CharField(db_index=True, max_length=120)),
                ('field_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('redact', 'Redact'), ('block', 'Block')], db_index=True, default='block', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['model_label', 'field_name', 'action'],
                'indexes': [models.Index(fields=['model_label', 'field_name', 'is_active'], name='ai_core_aid_model_l_355777_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('provider', 'Provider'), ('rider', 'Rider'), ('admin', 'Admin'), ('guest', 'Guest')], db_index=True, max_length=30)),
                ('feature', models.CharField(db_index=True, max_length=80)),
                ('max_requests_per_day', models.PositiveIntegerField(default=100)),
                ('max_tokens_per_day', models.PositiveIntegerField(default=100000)),
                ('max_cost_per_day', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', 'feature'],
                'constraints': [models.UniqueConstraint(fields=('role', 'feature'), name='unique_ai_quota_role_feature')],
            },
        ),
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=160)),
                ('feature', models.CharField(db_index=True, max_length=80)),
                ('system_prompt', models.TextField()),
                ('developer_prompt', models.TextField(blank=True)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ai_prompts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key', '-version'],
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='unique_ai_prompt_version')],
            },
        ),
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=120)),
                ('feature', models.CharField(db_index=True, max_length=80)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('supports_structured_outputs', models.BooleanField(default=True)),
                ('supports_tool_calls', models.BooleanField(default=True)),
                ('input_token_cost_per_1k', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('output_token_cost_per_1k', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('max_input_tokens', models.PositiveIntegerField(default=128000)),
                ('max_output_tokens', models.PositiveIntegerField(default=4096)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_core.aiproviderconfig')),
            ],
            options={
                'ordering': ['feature', '-is_default', 'model_name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'model_name', 'feature'), name='unique_ai_model_feature')],
            },
        ),
        migrations.CreateModel(
            name='AIUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=30)),
                ('feature', models.CharField(db_index=True, max_length=80)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('prompt_key', models.CharField(blank=True, max_length=120)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=12)),
                ('status', models.CharField(choices=[('success', 'Success'), ('blocked', 'Blocked'), ('error', 'Error'), ('skipped', 'Skipped')], db_index=True, default='success', max_length=20)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role', 'feature', '-created_at'], name='ai_core_aiu_role_82d6f8_idx'), models.Index(fields=['user', 'feature', '-created_at'], name='ai_core_aiu_user_id_7c8ac3_idx')],
            },
        ),
    ]
