# Generated by Django 5.2.14 on 2026-07-20 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitooldefinition',
            name='name',
            field=models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='Use a dotted lowercase tool name such as quotes.create_quote_request.', regex='^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$')]),
        ),
    ]
