# Generated by Django 5.2.14 on 2026-05-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrecord',
            name='factory_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='import_export_license_number',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='manufacturer_certificate_number',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='warehouse_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('business_registration', 'Business Registration Certificate'), ('cac_certificate', 'CAC / Company Certificate'), ('tax_id', 'Tax ID / VAT Certificate'), ('tin_certificate', 'TIN Certificate'), ('bank_statement', 'Bank Account Statement'), ('utility_bill', 'Utility Bill (Address Proof)'), ('proof_of_address', 'Proof of Address'), ('id_proof', 'Government ID Proof'), ('product_license', 'Product License/Certification'), ('manufacturer_certificate', 'Manufacturer Certificate'), ('import_export_license', 'Import / Export License'), ('factory_document', 'Factory / Warehouse Document'), ('other', 'Other Document')], max_length=30),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='kyc_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending Verification'), ('under_review', 'Under Review'), ('in_review', 'Under Review'), ('approved', 'Approved'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('requires_changes', 'Requires Changes'), ('suspended', 'Suspended')], default='not_started', max_length=20),
        ),
    ]
