# Generated by Django 5.2.14 on 2026-07-10 05:57

import core.private_upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycrecord_factory_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='document_file',
            field=models.FileField(upload_to='kyc/documents/%Y/%m/', validators=[core.private_upload_validation.PrivateUploadValidator('kyc')]),
        ),
    ]
