# Generated by Django 5.2.14 on 2026-05-23 16:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def create_default_delivery_providers(apps, schema_editor):
    DeliveryProvider = apps.get_model('orders', 'DeliveryProvider')
    defaults = [
        {
            'name': 'Arolana Driver',
            'code': 'arolana-driver',
            'provider_type': 'arolana_driver',
            'description': 'Arolana riders and approved local dispatch riders assigned by admin.',
            'supports_tracking': True,
            'supports_driver_assignment': True,
        },
        {
            'name': 'Manual Dispatch',
            'code': 'manual-dispatch',
            'provider_type': 'manual_dispatch',
            'description': 'Manual dispatch partner, vendor rider, or local courier selected by admin.',
            'supports_tracking': True,
            'supports_driver_assignment': True,
        },
        {
            'name': 'Uber Direct',
            'code': 'uber-direct',
            'provider_type': 'uber_direct',
            'description': 'Uber Direct delivery provider placeholder for future integration.',
            'supports_tracking': True,
            'supports_driver_assignment': False,
        },
        {
            'name': 'DHL',
            'code': 'dhl',
            'provider_type': 'dhl',
            'description': 'DHL courier delivery provider.',
            'supports_tracking': True,
            'supports_driver_assignment': False,
        },
        {
            'name': 'GIG Logistics',
            'code': 'gig-logistics',
            'provider_type': 'gig_logistics',
            'description': 'GIG Logistics delivery provider.',
            'supports_tracking': True,
            'supports_driver_assignment': False,
        },
        {
            'name': 'Pickup from Vendor',
            'code': 'pickup-from-vendor',
            'provider_type': 'vendor_pickup',
            'description': 'Customer pickup from vendor location after order confirmation.',
            'supports_tracking': False,
            'supports_driver_assignment': False,
        },
    ]

    for provider in defaults:
        DeliveryProvider.objects.update_or_create(
            code=provider['code'],
            defaults={**provider, 'is_active': True},
        )


def remove_default_delivery_providers(apps, schema_editor):
    DeliveryProvider = apps.get_model('orders', 'DeliveryProvider')
    DeliveryProvider.objects.filter(
        code__in=[
            'arolana-driver',
            'manual-dispatch',
            'uber-direct',
            'dhl',
            'gig-logistics',
            'pickup-from-vendor',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('provider_type', models.CharField(choices=[('arolana_driver', 'Arolana Driver'), ('manual_dispatch', 'Manual Dispatch'), ('uber_direct', 'Uber Direct'), ('dhl', 'DHL'), ('gig_logistics', 'GIG Logistics'), ('vendor_pickup', 'Pickup from Vendor'), ('other', 'Other Provider')], default='arolana_driver', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_tracking', models.BooleanField(default=True)),
                ('supports_driver_assignment', models.BooleanField(default=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'provider_type'], name='orders_deli_is_acti_2d7142_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_level', models.CharField(choices=[('standard', 'Standard Delivery'), ('express', 'Express Delivery'), ('arolana_dispatch', 'Arolana Dispatch'), ('uber_direct', 'Uber Direct'), ('pickup_from_vendor', 'Pickup from Vendor')], default='standard', max_length=30)),
                ('pickup_address', models.TextField(blank=True)),
                ('dropoff_address', models.TextField()),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tracking_status', models.CharField(choices=[('pending_assignment', 'Pending Assignment'), ('assigned', 'Assigned to Driver'), ('accepted', 'Accepted by Driver'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending_assignment', max_length=30)),
                ('tracking_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('driver_name', models.CharField(blank=True, max_length=120)),
                ('driver_phone', models.CharField(blank=True, max_length=50)),
                ('latest_location', models.CharField(blank=True, max_length=255)),
                ('latest_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('latest_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('driver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='orders.order')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_requests', to='orders.deliveryprovider')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_status', '-created_at'], name='orders_deli_trackin_083270_idx'), models.Index(fields=['service_level', '-created_at'], name='orders_deli_service_c023a7_idx'), models.Index(fields=['tracking_code'], name='orders_deli_trackin_a5bec5_idx')],
            },
        ),
        migrations.RunPython(create_default_delivery_providers, remove_default_delivery_providers),
    ]
