# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_deliveryprovider_deliveryrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="paystack", max_length=50),
        ),
    ]
