# Generated by Codex on 2026-05-23

from decimal import Decimal

from django.db import migrations


def set_provider_fee_defaults(apps, schema_editor):
    DeliveryProvider = apps.get_model('orders', 'DeliveryProvider')
    defaults = {
        'arolana-driver': Decimal('2500.00'),
        'manual-dispatch': Decimal('3000.00'),
        'uber-direct': Decimal('4500.00'),
        'dhl': Decimal('7500.00'),
        'gig-logistics': Decimal('5000.00'),
        'pickup-from-vendor': Decimal('0.00'),
    }
    for code, fee in defaults.items():
        DeliveryProvider.objects.filter(code=code, base_fee=0).update(base_fee=fee)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_paystack_default'),
    ]

    operations = [
        migrations.RunPython(set_provider_fee_defaults, migrations.RunPython.noop),
    ]
