# Generated by Django 5.2.14 on 2026-05-25 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_deliveryquoterequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deliveryquoterequest',
            new_name='orders_deli_status_12226a_idx',
            old_name='orders_deli_status_58accc_idx',
        ),
        migrations.RenameIndex(
            model_name='deliveryquoterequest',
            new_name='orders_deli_route_t_bfd77c_idx',
            old_name='orders_deli_route_t_5e3a6f_idx',
        ),
    ]
