# Generated by Django 5.2.14 on 2026-05-30 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_customer_email_order_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.CreateModel(
            name='MobilePushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('expo_push_token', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('platform', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('last_registered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_registered_at'],
                'indexes': [models.Index(fields=['phone_number', 'is_active'], name='orders_mobi_phone_n_3926ee_idx'), models.Index(fields=['email', 'is_active'], name='orders_mobi_email_9758c0_idx')],
            },
        ),
    ]
