# Generated by Django 5.2.14 on 2026-07-07 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_customer_email_order_customer_name_and_more'),
        ('products', '0027_productvariantspecification_vendorproductoffer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='vendor_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.vendorproductoffer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name_snapshot',
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_sku_snapshot',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_name_snapshot',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_id_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_name_snapshot',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.vendorproductoffer'),
        ),
    ]
