# Generated by Django 5.2.14 on 2026-05-31 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobile_customers', '0003_mobilecustomer_profile_image'),
        ('orders', '0010_order_customer_email_order_customer_name_and_more'),
        ('products', '0017_category_hero_height_desktop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=80)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ops_status_history', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='arolana_ops_order_i_e0a9d3_idx'), models.Index(fields=['status', '-created_at'], name='arolana_ops_status_161caf_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('last_seen_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='mobile_customers.mobilecustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_price_alerts', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'is_active'], name='arolana_ops_custome_3961a6_idx'), models.Index(fields=['product', 'is_active'], name='arolana_ops_product_f9f125_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'product'), name='unique_mobile_customer_price_alert')],
            },
        ),
    ]
