# Generated by Django 5.2.14 on 2026-05-31 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arolana_ops', '0001_initial'),
        ('mobile_customers', '0003_mobilecustomer_profile_image'),
        ('products', '0017_category_hero_height_desktop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_interactions', to='mobile_customers.mobilecustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_interactions', to='products.product')),
            ],
            options={
                'ordering': ['-last_viewed_at'],
                'indexes': [models.Index(fields=['customer', '-last_viewed_at'], name='arolana_ops_custome_7895d9_idx'), models.Index(fields=['customer', '-view_count'], name='arolana_ops_custome_0920f2_idx'), models.Index(fields=['product', '-last_viewed_at'], name='arolana_ops_product_bad2a0_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'product'), name='unique_mobile_customer_product_interaction')],
            },
        ),
    ]
