# Generated by Django 6.0.4 on 2026-05-03 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('desktop_notifications', models.BooleanField(default=True)),
                ('cart_updates', models.BooleanField(default=True)),
                ('order_updates', models.BooleanField(default=True)),
                ('promotions', models.BooleanField(default=False)),
                ('vendor_alerts', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True)),
                ('product_updates', models.BooleanField(default=False)),
                ('review_alerts', models.BooleanField(default=True)),
                ('message_alerts', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(default='22:00', help_text='Start of quiet hours')),
                ('quiet_hours_end', models.TimeField(default='08:00', help_text='End of quiet hours')),
                ('do_not_disturb', models.BooleanField(default=False)),
                ('dnd_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_type', models.CharField(choices=[('cart', '🛒 Cart Update'), ('order', '📦 Order Update'), ('payment', '💰 Payment'), ('message', '💬 New Message'), ('review', '⭐ New Review'), ('vendor', '🏪 Vendor Update'), ('product', '📱 Product Update'), ('promotion', '🎉 Promotion'), ('shipping', '🚚 Shipping Update'), ('system', '⚙️ System Alert'), ('security', '🔒 Security Alert'), ('wishlist', '❤️ Wishlist'), ('follow', '👥 New Follower'), ('achievement', '🏆 Achievement'), ('reminder', '⏰ Reminder'), ('newsletter', '📰 Newsletter'), ('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Information')], default='system', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2, help_text='Notification priority level')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Archive instead of delete')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(blank=True, help_text='URL to redirect when clicked', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like product_id, order_id')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'), models.Index(fields=['user', 'is_archived'], name='notificatio_user_id_523edd_idx')],
            },
        ),
    ]
