# Generated by Django 4.2.7 on 2026-05-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotificationsettings',
            options={'verbose_name': 'User Notification Setting', 'verbose_name_plural': 'User Notification Settings'},
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='vendor_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('signup', 'Sign Up'), ('order', 'Order Update'), ('payment', 'Payment'), ('message', 'New Message'), ('review', 'New Review'), ('follow', 'New Follower'), ('vendor', 'Vendor Update'), ('system', 'System Alert')], default='system', max_length=20),
        ),
    ]
