# Generated by Django 5.2.14 on 2026-05-24 01:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_delivery_provider_fee_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('vehicle_type', models.CharField(choices=[('bicycle', 'Bicycle'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck')], max_length=30, unique=True)),
                ('base_capacity_kg', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8)),
                ('base_speed_kmph', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=8)),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12)),
                ('per_km_fee', models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=12)),
                ('rider_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('radius_km', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['country', 'state', 'city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tracking_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('arrived_at_pickup', 'Arrived at Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('arrived_at_customer', 'Arrived at Customer'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('returned', 'Returned')], db_index=True, default='pending', max_length=30)),
                ('pickup_name', models.CharField(blank=True, max_length=160)),
                ('pickup_phone', models.CharField(blank=True, max_length=50)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('dropoff_name', models.CharField(blank=True, max_length=160)),
                ('dropoff_phone', models.CharField(blank=True, max_length=50)),
                ('dropoff_address', models.TextField()),
                ('dropoff_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('dropoff_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rider_earning', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('customer_note', models.TextField(blank=True)),
                ('rider_note', models.TextField(blank=True)),
                ('proof_of_delivery', models.ImageField(blank=True, null=True, upload_to='delivery/proofs/')),
                ('proof_note', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True)),
                ('legacy_delivery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_delivery', to='orders.deliveryrequest')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_delivery_requests', to='orders.order')),
                ('requested_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_requests', to='deliveries.deliveryvehicle')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='deliveries.deliveryzone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('arrived_at_pickup', 'Arrived at Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('arrived_at_customer', 'Arrived at Customer'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('returned', 'Returned')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_status_updates', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='deliveries.deliveryrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12)),
                ('per_km_fee', models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=12)),
                ('minimum_fee', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=12)),
                ('maximum_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('rider_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_rules', to='deliveries.deliveryvehicle')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_rules', to='deliveries.deliveryzone')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rider_type', models.CharField(choices=[('arolana', 'Arolana Rider'), ('vendor', 'Vendor Rider'), ('independent', 'Independent Dispatch Rider'), ('admin_assigned', 'Admin Assigned Rider')], default='independent', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('emergency_phone', models.CharField(blank=True, max_length=50)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='delivery/riders/id_documents/')),
                ('driver_license', models.FileField(blank=True, null=True, upload_to='delivery/riders/licenses/')),
                ('vehicle_document', models.FileField(blank=True, null=True, upload_to='delivery/riders/vehicle_documents/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='delivery/riders/photos/')),
                ('is_online', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_location_at', models.DateTimeField(blank=True, null=True)),
                ('completed_deliveries', models.PositiveIntegerField(default=0)),
                ('failed_deliveries', models.PositiveIntegerField(default=0)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('admin_notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='deliveries.deliveryvehicle')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='deliveries.deliveryzone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_name', models.CharField(blank=True, max_length=160)),
                ('account_number', models.CharField(blank=True, max_length=40)),
                ('admin_note', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='deliveries.riderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='deliveries.riderprofile'),
        ),
        migrations.CreateModel(
            name='DeliveryLocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('speed_kmph', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='deliveries.deliveryrequest')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_pings', to='deliveries.riderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='deliveries.riderprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['kyc_status', 'is_online', 'is_available'], name='deliveries__kyc_sta_559c90_idx'),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['rider_type', 'kyc_status'], name='deliveries__rider_t_83c86e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrequest',
            index=models.Index(fields=['status', '-created_at'], name='deliveries__status_a5a345_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrequest',
            index=models.Index(fields=['tracking_code'], name='deliveries__trackin_13066c_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrequest',
            index=models.Index(fields=['rider', 'status'], name='deliveries__rider_i_85d460_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylocationping',
            index=models.Index(fields=['delivery', '-created_at'], name='deliveries__deliver_cd298b_idx'),
        ),
    ]
