# Generated by Django 5.2.14 on 2026-05-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_deliveryrequest_base_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='is_ready_for_rider',
            field=models.BooleanField(db_index=True, default=True, help_text='Show this delivery to riders only after vendor/admin confirms it is ready for pickup.'),
        ),
    ]
