# Generated by Django 5.2.14 on 2026-07-10 05:57

import core.private_upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_riderprofile_profile_edit_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='proof_of_delivery',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/proofs/', validators=[core.private_upload_validation.PrivateUploadValidator('private_profile_image')]),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='dashboard_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/riders/banners/', validators=[core.private_upload_validation.PrivateUploadValidator('private_profile_image')]),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='driver_license',
            field=models.FileField(blank=True, null=True, upload_to='delivery/riders/licenses/', validators=[core.private_upload_validation.PrivateUploadValidator('rider_document')]),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='delivery/riders/id_documents/', validators=[core.private_upload_validation.PrivateUploadValidator('rider_document')]),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/riders/photos/', validators=[core.private_upload_validation.PrivateUploadValidator('private_profile_image')]),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='vehicle_document',
            field=models.FileField(blank=True, null=True, upload_to='delivery/riders/vehicle_documents/', validators=[core.private_upload_validation.PrivateUploadValidator('rider_document')]),
        ),
    ]
