# Generated by Django 6.0.4 on 2026-04-30 12:00

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('specifications', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Product specifications and technical details', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=10, null=True)),
                ('cost_per_item', models.DecimalField(blank=True, decimal_places=2, help_text='Your cost per item', max_digits=10, null=True)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current stock quantity')),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Alert when stock reaches this level')),
                ('is_in_stock', models.BooleanField(default=True)),
                ('allow_backorder', models.BooleanField(default=False, help_text='Allow customers to order when out of stock')),
                ('main_image', models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='products/%Y/%m/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords, comma separated', max_length=200)),
                ('views_count', models.IntegerField(default=0)),
                ('sales_count', models.IntegerField(default=0)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_new', models.BooleanField(default=False, help_text='Mark as new arrival')),
                ('is_bestseller', models.BooleanField(default=False, help_text='Mark as bestseller')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('vendor', models.ForeignKey(limit_choices_to={'user_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(help_text='Product gallery image', upload_to='products/gallery/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='Image alt text for SEO', max_length=200)),
                ('is_main', models.BooleanField(default=False, help_text='Set as main product image')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductQnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Q&A',
                'verbose_name_plural': 'Product Q&As',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5 stars')),
                ('title', models.CharField(help_text='Review title', max_length=200)),
                ('review', models.TextField(help_text='Your review')),
                ('verified_purchase', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0, help_text='Number of users who found this helpful')),
                ('video_review', models.FileField(blank=True, null=True, upload_to='reviews/videos/%Y/%m/')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_type', models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('material', 'Material'), ('style', 'Style'), ('other', 'Other')], default='other', help_text='Type of variant', max_length=20)),
                ('name', models.CharField(help_text='Variant name (Size, Color, etc.)', max_length=100)),
                ('value', models.CharField(help_text='Variant value (Large, Red, etc.)', max_length=100)),
                ('sku', models.CharField(blank=True, help_text='Unique SKU for this variant', max_length=50, unique=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Additional cost (positive) or discount (negative)', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Stock quantity for this variant')),
                ('image', models.ImageField(blank=True, help_text='Variant specific image', null=True, upload_to='products/variants/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ['variant_type', 'name', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='products/variants/gallery/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
