# Generated by Django 6.0.4 on 2026-05-06 11:02

import django.core.validators
import django.db.models.deletion
import taggit.managers
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Accessories'},
        ),
        migrations.AlterModelOptions(
            name='accessoryproduct',
            options={'ordering': ['display_order'], 'verbose_name': 'Product Accessory', 'verbose_name_plural': 'Product Accessories'},
        ),
        migrations.AlterModelOptions(
            name='manufacturerwarranty',
            options={'verbose_name': 'Manufacturer Warranty', 'verbose_name_plural': 'Manufacturer Warranties'},
        ),
        migrations.AlterModelOptions(
            name='productvariantimage',
            options={'ordering': ['order'], 'verbose_name': 'Variant Image', 'verbose_name_plural': 'Variant Images'},
        ),
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['display_order'], 'verbose_name': 'Product Video', 'verbose_name_plural': 'Product Videos'},
        ),
        migrations.AlterModelOptions(
            name='reviewvideo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shippinginfo',
            options={'verbose_name': 'Shipping Information', 'verbose_name_plural': 'Shipping Information'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-added_at']},
        ),
        migrations.RemoveIndex(
            model_name='wishlist',
            name='products_wi_user_id_7792c0_idx',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='images',
        ),
        migrations.RemoveField(
            model_name='reviewvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='accessoryproduct',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brand',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (160 chars)'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title', max_length=200),
        ),
        migrations.AddField(
            model_name='manufacturerwarranty',
            name='exclusions',
            field=models.TextField(blank=True, help_text="What's not covered"),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved_quantity',
            field=models.IntegerField(default=0, help_text='Quantity reserved for pending orders', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='unhelpful_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reviewvideo',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/thumbs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='reviewvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload review video', null=True, upload_to='reviews/videos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='stock_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='accessoryproduct',
            name='discount_when_bought_together',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount % when bought together', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS icon class or icon name', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='manufacturerwarranty',
            name='coverage_details',
            field=models.TextField(blank=True, help_text="What's covered"),
        ),
        migrations.AlterField(
            model_name='manufacturerwarranty',
            name='duration_months',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='manufacturerwarranty',
            name='duration_years',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='manufacturerwarranty',
            name='registration_url',
            field=models.URLField(blank=True, help_text='Warranty registration URL'),
        ),
        migrations.AlterField(
            model_name='manufacturerwarranty',
            name='terms_url',
            field=models.URLField(blank=True, help_text='Link to warranty terms'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Your cost per item (for profit calculation)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimension_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('in', 'Inches'), ('mm', 'Millimeters')], default='cm', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='extended_warranty_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(db_index=True, default=False, help_text='Bestseller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_in_stock',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False, help_text='New arrival'),
        ),
        migrations.AlterField(
            model_name='product',
            name='local_video',
            field=models.FileField(blank=True, help_text='Local video file (MP4, WebM)', null=True, upload_to='products/videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=5, help_text='Alert when stock reaches this level', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main product image (featured)', null=True, upload_to='products/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (160 chars)', max_length=160),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (60 chars)', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Unique product identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(db_index=True, default=0, help_text='Current stock quantity', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_type',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('local', 'Local Video')], default='youtube', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='views_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_description',
            field=models.TextField(blank=True, help_text='Warranty terms'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_years',
            field=models.IntegerField(default=1, help_text='Warranty period in years', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Product weight', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds'), ('g', 'Grams'), ('oz', 'Ounces')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for SEO', max_length=200),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_product_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='helpful_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productquestion',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='helpful_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(help_text='Your detailed review'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='verified_purchase',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='video_review',
            field=models.FileField(blank=True, help_text='Optional review video', null=True, upload_to='reviews/videos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price adjustment (positive or negative)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_type',
            field=models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('material', 'Material'), ('style', 'Style'), ('pattern', 'Pattern'), ('finish', 'Finish'), ('capacity', 'Capacity'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='local_video',
            field=models.FileField(blank=True, help_text='MP4, WebM, or Ogg format', null=True, upload_to='products/videos/additional/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='source',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('local', 'Local Video')], default='youtube', max_length=20),
        ),
        migrations.AlterField(
            model_name='recentlyviewed',
            name='viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='estimated_delivery_days_max',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='estimated_delivery_days_min',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='hazmat',
            field=models.BooleanField(default=False, help_text='Is this a hazardous material?'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='shipping_restrictions',
            field=models.TextField(blank=True, help_text='Shipping restrictions or special handling notes'),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='weight_shipping',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Shipping weight (kg/lbs)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['is_active', 'display_order'], name='products_ac_is_acti_648c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active', 'featured'], name='products_br_is_acti_270d67_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'order'], name='products_ca_is_acti_65c3de_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='products_ca_parent__1cafc9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'is_active'], name='products_pr_vendor__69616a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', '-created_at'], name='products_pr_is_feat_88faea_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_bestseller', '-sales_count'], name='products_pr_is_best_8319c5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rating_avg', '-rating_count'], name='products_pr_rating__a25809_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'order'], name='products_pr_product_e55bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='productquestion',
            index=models.Index(fields=['product', 'is_public'], name='products_pr_product_505f62_idx'),
        ),
        migrations.AddIndex(
            model_name='productquestion',
            index=models.Index(fields=['user', '-created_at'], name='products_pr_user_id_7c3d07_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['user', '-created_at'], name='products_pr_user_id_3d2494_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['verified_purchase', '-helpful_count'], name='products_pr_verifie_ec68ca_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_66459e_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', '-added_at'], name='products_wi_user_id_c49cfd_idx'),
        ),
    ]
