# Generated by Django 6.0.4 on 2026-05-06 12:48

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_accessory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('shop_slug', models.SlugField(unique=True)),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/%Y/%m/')),
                ('shop_banner', models.ImageField(blank=True, null=True, upload_to='vendors/banners/%Y/%m/')),
                ('shop_description', models.TextField(blank=True)),
                ('shop_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('shop_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('shop_website', models.URLField(blank=True)),
                ('business_address', models.TextField(blank=True)),
                ('business_license', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('total_products', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_sales', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rating_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_reviews', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('response_time', models.CharField(blank=True, help_text='Average response time', max_length=50)),
                ('return_policy', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_verified', 'is_active'], name='products_ve_is_veri_0c32b7_idx'), models.Index(fields=['-rating_avg'], name='products_ve_rating__d7aef2_idx')],
            },
        ),
    ]
