# Generated by Django 6.0.4 on 2026-05-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_vendor'),
        ('products', 'NNNN_fix_product_slugs'),
    ]

    operations = [
    ]
