# Generated by Django 6.0.4 on 2026-05-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_merge_0004_vendor_NNNN_fix_product_slugs'),
    ]

    operations = [
    ]
