# Generated by Django 6.0.4 on 2026-05-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_category_background_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Hero background image for category landing page (1920x400 recommended)', null=True, upload_to='categories/backgrounds/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='category',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Hero subtitle text displayed on category landing page', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Custom hero title (overrides default category name)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Category description for SEO'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category thumbnail image (for cards)', null=True, upload_to='categories/%Y/%m/'),
        ),
    ]
