# Generated by Django 6.0.4 on 2026-05-11 00:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_background_image_category_hero_subtitle_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_50f5f1_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Notes from admin about approval/rejection'),
        ),
        migrations.AddField(
            model_name='product',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_changes', 'Requires Changes')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='submitted_for_review_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active', 'approval_status'], name='products_pr_categor_374bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['approval_status', '-submitted_for_review_at'], name='products_pr_approva_b8affd_idx'),
        ),
    ]
