# Generated by Django 6.0.4 on 2026-05-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_products_pr_categor_50f5f1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
