# Generated by Django 5.2.14 on 2026-05-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_accessory_slug_alter_brand_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color_code',
            field=models.CharField(blank=True, help_text='Optional color swatch value, for example #111827 or rgb(17, 24, 39)', max_length=20),
        ),
    ]
