# Generated by Django 5.2.14 on 2026-05-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productvariant_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListingBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Discover the future of shopping', max_length=160)),
                ('subtitle', models.TextField(blank=True, default='Explore trusted products from verified vendors, compare prices, filter faster, and shop with a premium marketplace experience built for every screen.')),
                ('eyebrow', models.CharField(default='Arolana Marketplace', max_length=80)),
                ('placement', models.CharField(choices=[('products_list', 'Products List Page')], db_index=True, default='products_list', max_length=40)),
                ('background_image', models.ImageField(blank=True, help_text='Main banner background image. Recommended: 1920x700.', null=True, upload_to='products/listing_banners/%Y/%m/')),
                ('side_image', models.ImageField(blank=True, help_text='Optional floating side image/icon for desktop.', null=True, upload_to='products/listing_banners/side/%Y/%m/')),
                ('cta_text', models.CharField(blank=True, default='Start shopping', max_length=80)),
                ('cta_link', models.CharField(blank=True, default='#products-section', max_length=255)),
                ('metric_one_icon', models.CharField(default='box', max_length=50)),
                ('metric_one_text', models.CharField(default='Products', max_length=80)),
                ('metric_two_icon', models.CharField(default='shield-alt', max_length=50)),
                ('metric_two_text', models.CharField(default='Verified Vendors', max_length=80)),
                ('metric_three_icon', models.CharField(default='truck', max_length=50)),
                ('metric_three_text', models.CharField(default='Fast Delivery', max_length=80)),
                ('primary_color', models.CharField(blank=True, default='#2563eb', max_length=20)),
                ('secondary_color', models.CharField(blank=True, default='#7c3aed', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Product Listing Banner',
                'verbose_name_plural': 'Product Listing Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
