# Generated by Django 5.2.14 on 2026-05-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_hero_background_color_and_more'),
        ('products', '0011_productlistingbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text='Optional button/card title override', max_length=120)),
                ('teaser', models.TextField(blank=True, help_text='Optional short teaser override')),
                ('placement', models.CharField(choices=[('overview', 'Below product overview'), ('articles_tab', 'Articles tab'), ('description', 'Description support link'), ('hero', 'Product top section')], default='articles_tab', max_length=30)),
                ('open_behavior', models.CharField(choices=[('same_page', 'Open in same page'), ('new_page', 'Open in new tab'), ('popup', 'Open in popup modal')], default='same_page', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='blog.blogpost')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_links', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Article Link',
                'verbose_name_plural': 'Product Article Links',
                'ordering': ['sort_order', 'article__published_at'],
                'unique_together': {('product', 'article', 'placement')},
            },
        ),
    ]
