# Generated by Django 5.2.14 on 2026-05-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productarticlelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer_sku',
            field=models.CharField(blank=True, db_index=True, help_text='Optional SKU/model number supplied by the manufacturer', max_length=100),
        ),
    ]
