# Generated by Django 5.2.14 on 2026-05-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_optional_banner_content_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('open_box', 'Open Box'), ('uk_used', 'UK Used'), ('foreign_used', 'Foreign Used'), ('locally_used', 'Locally Used'), ('refurbished', 'Refurbished'), ('fairly_used', 'Fairly Used'), ('certified_pre_owned', 'Certified Pre-Owned')], db_index=True, default='brand_new', help_text='Clearly disclose whether this item is brand new, used, open box, or refurbished.', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='manual_pdf',
            field=models.FileField(blank=True, help_text='Optional PDF manual, brochure, or specification sheet for customer download.', null=True, upload_to='products/manuals/%Y/%m/'),
        ),
    ]
