# Generated by Django 5.2.14 on 2026-05-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_condition_product_manual_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hero_height_desktop',
            field=models.PositiveIntegerField(default=520, help_text='Category hero height on desktop in pixels.'),
        ),
        migrations.AddField(
            model_name='category',
            name='hero_height_mobile',
            field=models.PositiveIntegerField(default=360, help_text='Category hero height on mobile in pixels.'),
        ),
        migrations.AddField(
            model_name='category',
            name='hero_height_tablet',
            field=models.PositiveIntegerField(default=440, help_text='Category hero height on tablet in pixels.'),
        ),
        migrations.AddField(
            model_name='category',
            name='hero_image_brightness',
            field=models.PositiveSmallIntegerField(default=62, help_text='Hero image brightness percentage. Lower values make the banner darker; 100 keeps the image original.'),
        ),
    ]
