# Generated by Django 5.2.14 on 2026-05-31 19:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_category_hero_height_desktop_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWholesaleTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'min_quantity'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional bulk buying unit price.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='Certification names or document labels.'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated production/dispatch lead time in days.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum order quantity for wholesale/manufacturer orders.'),
        ),
        migrations.AddField(
            model_name='product',
            name='moq_unit',
            field=models.CharField(blank=True, default='unit', help_text='MOQ unit, e.g. unit, carton, pallet, roll.', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='sample_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sample_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional manufacturer/wholesale unit price.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['minimum_order_quantity'], name='products_pr_minimum_447de3_idx'),
        ),
        migrations.AddField(
            model_name='productwholesaletier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_tiers', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='productwholesaletier',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_ddc576_idx'),
        ),
        migrations.AddIndex(
            model_name='productwholesaletier',
            index=models.Index(fields=['min_quantity'], name='products_pr_min_qua_b8964e_idx'),
        ),
    ]
