# Generated by Django 5.2.14 on 2026-06-18 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_local_video_and_more'),
        ('products', '0019_product_detail_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text='Optional button/card title override', max_length=120)),
                ('teaser', models.TextField(blank=True, help_text='Optional short teaser override')),
                ('placement', models.CharField(choices=[('overview', 'Below category hero'), ('guide_card', 'Category guide card'), ('articles_tab', 'Articles section')], default='guide_card', max_length=30)),
                ('open_behavior', models.CharField(choices=[('same_page', 'Open in same page'), ('new_page', 'Open in new tab'), ('popup', 'Open in popup modal')], default='same_page', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='blog.blogpost')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_links', to='products.category')),
            ],
            options={
                'verbose_name': 'Category Article Link',
                'verbose_name_plural': 'Category Article Links',
                'ordering': ['sort_order', 'article__published_at'],
                'indexes': [models.Index(fields=['category', 'is_active', 'sort_order'], name='products_ca_categor_232084_idx'), models.Index(fields=['placement', 'is_active'], name='products_ca_placeme_ed154a_idx')],
                'unique_together': {('category', 'article', 'placement')},
            },
        ),
    ]
