# Generated by Django 5.2.14 on 2026-06-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productarticlelink_admin_reader_controls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productarticlelink',
            options={'ordering': ['sort_order', 'article__published_at'], 'verbose_name': 'Product Article Link', 'verbose_name_plural': 'Product Article Links'},
        ),
        migrations.RemoveField(
            model_name='productarticlelink',
            name='reader_show_author_box',
        ),
        migrations.RemoveField(
            model_name='productarticlelink',
            name='reader_show_share_box',
        ),
        migrations.AlterField(
            model_name='categoryarticlelink',
            name='open_behavior',
            field=models.CharField(choices=[('same_page', 'Open article in same page'), ('new_page', 'Open article in new tab'), ('side_reader', 'Open beside product (same-page split reader)'), ('popup', 'Legacy popup / split reader')], default='same_page', max_length=20),
        ),
        migrations.AlterField(
            model_name='productarticlelink',
            name='open_behavior',
            field=models.CharField(choices=[('same_page', 'Open article in same page'), ('new_page', 'Open article in new tab'), ('side_reader', 'Open beside product (same-page split reader)'), ('popup', 'Legacy popup / split reader')], db_index=True, default='side_reader', help_text='Admin controls how this article opens from the product page. Choose same page, new tab, or the B&H-style same-page split reader.', max_length=20),
        ),
        migrations.AlterField(
            model_name='productarticlelink',
            name='reader_content_mode',
            field=models.CharField(choices=[('clean_full_article', 'Full article page, cleaned for product reader'), ('full_article', 'Full article page exactly as article layout'), ('body_only', 'Main article body only')], default='clean_full_article', help_text='Used only when Open behavior is split reader/popup. Clean full article is recommended for product pages.', max_length=30),
        ),
        migrations.AlterField(
            model_name='productarticlelink',
            name='reader_show_ads',
            field=models.BooleanField(default=False, help_text='Used only in split reader. Turn on if you intentionally want article ad placements inside the product reader.'),
        ),
        migrations.AlterField(
            model_name='productarticlelink',
            name='reader_show_chat_widgets',
            field=models.BooleanField(default=False, help_text='Used only in split reader. Normally keep off to avoid duplicate floating chat buttons.'),
        ),
        migrations.AlterField(
            model_name='productarticlelink',
            name='reader_show_comments',
            field=models.BooleanField(default=True, help_text='Used only in split reader. Show/hide comments inside the reader.'),
        ),
        migrations.AlterField(
            model_name='productarticlelink',
            name='reader_show_cookie_banner',
            field=models.BooleanField(default=False, help_text='Used only in split reader. Normally keep off so imported cookie banners do not cover the product page.'),
        ),
        migrations.AlterField(
            model_name='productarticlelink',
            name='reader_show_newsletter',
            field=models.BooleanField(default=True, help_text='Used only in split reader. Show/hide article newsletter signup blocks inside the reader.'),
        ),
        migrations.AlterField(
            model_name='productarticlelink',
            name='reader_show_site_header_footer',
            field=models.BooleanField(default=False, help_text='Used only in split reader. Normally keep off because the product page already has the site header/footer.'),
        ),
    ]
