# Generated by Django 5.2.14 on 2026-06-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_productarticlelink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_fill_description_images',
            field=models.BooleanField(default=True, help_text='Automatically fill image placeholders in the styled product description using uploaded product gallery images.'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_auto_overview_gallery',
            field=models.BooleanField(default=True, help_text='Show uploaded product images automatically inside the Overview tab.'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_top_gallery',
            field=models.BooleanField(default=True, help_text='Show the normal product image gallery at the top of the product detail page.'),
        ),
    ]
