# Generated by Django 5.2.14 on 2026-06-29 15:07

import core.image_protection
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_auto_fill_description_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main product image (featured)', null=True, upload_to=core.image_protection.ProtectedImageUploadPath('products')),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Product gallery image', upload_to=core.image_protection.ProtectedImageUploadPath('products/gallery')),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('products/variants')),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='image',
            field=models.ImageField(upload_to=core.image_protection.ProtectedImageUploadPath('products/variants/gallery')),
        ),
    ]
