# Generated by Django 5.2.14 on 2026-06-29 15:23

import core.image_protection
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_main_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('accessories')),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('brands')),
        ),
        migrations.AlterField(
            model_name='category',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Hero background image for category landing page (1920x400 recommended)', null=True, upload_to=core.image_protection.ProtectedImageUploadPath('categories/backgrounds')),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category thumbnail image (for cards)', null=True, upload_to=core.image_protection.ProtectedImageUploadPath('categories')),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('products/video_thumbs')),
        ),
        migrations.AlterField(
            model_name='productlistingbanner',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Main banner background image. Recommended: 1920x700.', null=True, upload_to=core.image_protection.ProtectedImageUploadPath('products/listing_banners')),
        ),
        migrations.AlterField(
            model_name='productlistingbanner',
            name='side_image',
            field=models.ImageField(blank=True, help_text='Optional floating side image/icon for desktop.', null=True, upload_to=core.image_protection.ProtectedImageUploadPath('products/listing_banners/side')),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('products/video_thumbs/additional')),
        ),
        migrations.AlterField(
            model_name='reviewvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('reviews/thumbs')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop_banner',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('vendors/banners')),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('vendors/logos')),
        ),
    ]
