# Generated by Django 5.2.14 on 2026-07-07 12:59

import core.image_protection
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_draft_approval_status'),
        ('vendors', '0015_vendorprofile_business_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.CharField(blank=True, help_text='Example: Display, Audio, Connectivity.', max_length=120)),
                ('name', models.CharField(max_length=160)),
                ('value', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_highlight', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_order', 'group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VendorProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_sku', models.CharField(blank=True, db_index=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('brand_new', 'Brand New'), ('open_box', 'Open Box'), ('uk_used', 'UK Used'), ('foreign_used', 'Foreign Used'), ('locally_used', 'Locally Used'), ('refurbished', 'Refurbished'), ('fairly_used', 'Fairly Used'), ('certified_pre_owned', 'Certified Pre-Owned')], default='brand_new', max_length=20)),
                ('seller_warranty', models.TextField(blank=True)),
                ('return_policy', models.TextField(blank=True)),
                ('delivery_note', models.TextField(blank=True)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('fulfilment_method', models.CharField(choices=[('vendor', 'Vendor Fulfilled'), ('arolana', 'Arolana Fulfilled'), ('dropship', 'Dropship'), ('pickup', 'Pickup Only')], default='vendor', max_length=20)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved / Live'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('approval_notes', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_preferred', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-is_preferred', '-is_featured', 'price', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['display_order', 'variant_type', 'name', 'value'], 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AlterModelOptions(
            name='productvariantimage',
            options={'ordering': ['sort_order', 'order'], 'verbose_name': 'Variant Image', 'verbose_name_plural': 'Variant Images'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='canonical_override',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='compatibility_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='dimension_unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('in', 'Inches'), ('mm', 'Millimeters')], default='cm', max_length=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='dimensions_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='dimensions_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='dimensions_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='ean',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='extended_warranty_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='gtin',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('products/variants/hover')),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='included_accessories',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_indexable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='key_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='local_video',
            field=models.FileField(blank=True, null=True, upload_to='products/variants/videos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='manual_pdf',
            field=models.FileField(blank=True, null=True, upload_to='products/variants/manuals/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='manufacturer_sku',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='model_number',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='recommended_use',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='selector_type',
            field=models.CharField(choices=[('text', 'Text Button'), ('color', 'Color Swatch'), ('image', 'Image Swatch'), ('dropdown', 'Dropdown'), ('card', 'Configuration Card')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(blank=True, help_text='Variant URL/selector slug. Auto-generated when blank.', max_length=255),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='specifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='upc',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_mode',
            field=models.CharField(choices=[('simple', 'Simple selector variant'), ('full', 'Full sellable catalog variant')], db_index=True, default='simple', help_text='Simple variants inherit product content. Full variants can override content, media, warranty, SEO, and specifications.', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('products/variants/video_thumbs')),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='video_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='video_type',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('local', 'Local Video')], default='youtube', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='warranty_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='warranty_years',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds'), ('g', 'Grams'), ('oz', 'Ounces')], default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='image_type',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('swatch', 'Selector Swatch'), ('packaging', 'Packaging'), ('lifestyle', 'Lifestyle'), ('diagram', 'Diagram / Spec'), ('certificate', 'Certificate'), ('other', 'Other')], default='gallery', max_length=30),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'variant_mode', 'is_active'], name='products_pr_product_2ee040_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'slug'], name='products_pr_product_4b0c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariantimage',
            index=models.Index(fields=['variant', 'is_active', 'sort_order'], name='products_pr_variant_65ee80_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariantimage',
            index=models.Index(fields=['variant', 'image_type'], name='products_pr_variant_ef9f79_idx'),
        ),
        migrations.AddField(
            model_name='productvariantspecification',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_specs', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='vendorproductoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_offers', to='products.product'),
        ),
        migrations.AddField(
            model_name='vendorproductoffer',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_offers', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='vendorproductoffer',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='vendors.vendorprofile'),
        ),
        migrations.AddIndex(
            model_name='productvariantspecification',
            index=models.Index(fields=['variant', 'display_order'], name='products_pr_variant_a0ecba_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariantspecification',
            index=models.Index(fields=['variant', 'is_highlight'], name='products_pr_variant_c36ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproductoffer',
            index=models.Index(fields=['vendor', 'is_active', 'approval_status'], name='products_ve_vendor__1c876b_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproductoffer',
            index=models.Index(fields=['product', 'is_active', 'approval_status'], name='products_ve_product_ea950e_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproductoffer',
            index=models.Index(fields=['variant', 'is_active', 'approval_status'], name='products_ve_variant_ee0852_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproductoffer',
            index=models.Index(fields=['condition'], name='products_ve_conditi_1f41f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendorproductoffer',
            constraint=models.UniqueConstraint(fields=('vendor', 'product', 'variant', 'seller_sku'), name='unique_vendor_offer_sku_per_catalog_item'),
        ),
    ]
