# Generated by Django 5.2.14 on 2026-07-07 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_productvariantspecification_vendorproductoffer_and_more'),
        ('vendors', '0015_vendorprofile_business_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatalogRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('request_type', models.CharField(choices=[('new_product', 'New catalog product'), ('new_variant', 'Missing product variant')], db_index=True, max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=120)),
                ('model_number', models.CharField(blank=True, max_length=120)),
                ('manufacturer_sku', models.CharField(blank=True, max_length=120)),
                ('gtin', models.CharField(blank=True, max_length=64)),
                ('upc', models.CharField(blank=True, max_length=64)),
                ('ean', models.CharField(blank=True, max_length=64)),
                ('barcode', models.CharField(blank=True, max_length=128)),
                ('requested_attributes', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('vendor_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs more information')], db_index=True, default='pending', max_length=24)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_requests', to='products.product')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_catalog_requests', to=settings.AUTH_USER_MODEL)),
                ('resulting_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_catalog_requests', to='products.product')),
                ('resulting_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_catalog_requests', to='products.productvariant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_product_catalog_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_requests', to='vendors.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status', '-created_at'], name='products_pr_vendor__adec60_idx'), models.Index(fields=['request_type', 'status'], name='products_pr_request_ccb65d_idx'), models.Index(fields=['product', 'status'], name='products_pr_product_c13bc0_idx')],
            },
        ),
    ]
