# Generated by Django 5.2.14 on 2026-07-10 05:57

import core.image_protection
import core.private_upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_backfill_default_vendor_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='video_review',
            field=models.FileField(blank=True, help_text='Optional review video. MP4 or WebM only.', null=True, upload_to='reviews/videos/%Y/%m/', validators=[core.private_upload_validation.PrivateUploadValidator('review_video')]),
        ),
        migrations.AlterField(
            model_name='reviewvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.image_protection.ProtectedImageUploadPath('reviews/thumbs'), validators=[core.private_upload_validation.PrivateUploadValidator('private_profile_image')]),
        ),
        migrations.AlterField(
            model_name='reviewvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload customer review video. MP4 or WebM only.', null=True, upload_to='reviews/videos/%Y/%m/', validators=[core.private_upload_validation.PrivateUploadValidator('review_video')]),
        ),
        migrations.AlterField(
            model_name='vendorproductoffer',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('open_box', 'Open Box'), ('uk_used', 'UK Used'), ('foreign_used', 'Foreign Used'), ('locally_used', 'Locally Used'), ('refurbished', 'Refurbished'), ('fairly_used', 'Fairly Used'), ('certified_pre_owned', 'Certified Pre-Owned')], default='brand_new', max_length=30),
        ),
    ]
