# Generated by Django 5.2.14 on 2026-07-13 18:14

import core.private_upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_productreview_video_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload customer review video. MP4, WebM, MOV or M4V.', null=True, upload_to='reviews/videos/%Y/%m/', validators=[core.private_upload_validation.PrivateUploadValidator('review_video')]),
        ),
    ]
