# Generated by Django 5.2.14 on 2026-07-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_reviewvideo_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review_video_conversion_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='review_video_conversion_status',
            field=models.CharField(choices=[('none', 'No video'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='productreview',
            name='review_video_converted',
            field=models.FileField(blank=True, help_text='Browser-compatible H.264/AAC MP4 generated automatically from the customer upload.', null=True, upload_to='reviews/videos/converted/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='review_video_converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
