# Generated by Django 5.2.14 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0032_productreview_review_video_conversion_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_navigation_featured",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text=(
                    "Show this top-level category in the desktop priority "
                    "navigation rail. It always remains available in All "
                    "Categories."
                ),
            ),
        ),
    ]
