# Generated by Django 5.2.14 on 2026-08-03 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_category_is_navigation_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListLowerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('why_buy', 'Why Buy From Arolana'), ('buying_guides', 'Buying Guides'), ('recently_viewed', 'Recently Viewed'), ('recommendations', 'You May Also Like'), ('verified_providers', 'See Verified Service Providers'), ('blog', 'From Our Blog')], max_length=40, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('maximum_items', models.PositiveSmallIntegerField(default=40)),
                ('desktop_visible_count', models.PositiveSmallIntegerField(default=4)),
                ('tablet_visible_count', models.PositiveSmallIntegerField(default=3)),
                ('mobile_visible_count', models.PositiveSmallIntegerField(default=2)),
                ('selection_mode', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('mixed', 'Mixed')], default='automatic', max_length=20)),
                ('view_all_text', models.CharField(default='View All', max_length=50)),
                ('view_all_url', models.CharField(blank=True, max_length=300)),
                ('shuffle_on_refresh', models.BooleanField(default=False)),
                ('show_when_empty', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product List Lower Section',
                'verbose_name_plural': 'Product List Lower Sections',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductListTrustBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=220)),
                ('icon', models.CharField(default='fas fa-shield-alt', help_text='Font Awesome class, e.g. fas fa-shield-alt', max_length=80)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(limit_choices_to={'section_type': 'why_buy'}, on_delete=django.db.models.deletion.CASCADE, related_name='trust_benefits', to='products.productlistlowersection')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
