# Generated by Django 5.2.14 on 2026-08-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_productlistlowersection_productlisttrustbenefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_display_mode',
            field=models.CharField(choices=[('contain', 'Contain with padding'), ('fill', 'Fill card'), ('transparent', 'Transparent / no background')], default='contain', help_text='Choose how the uploaded brand logo appears on Brand Detail pages. Use Fill card when the uploaded logo image already includes its own background. Use Transparent / no background for transparent PNG/WebP logos.', max_length=30, verbose_name='Brand logo display'),
        ),
    ]
