# Generated by Django 5.2.14 on 2026-08-10 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_accessory_approved_at_accessory_approved_by_and_more'),
        ('vendors', '0017_alter_vendorprofile_pickup_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='helpful_count',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='moderation_note',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='moderation_status',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='product_clicks',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='rating_sum',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='views_count',
        ),
        migrations.AddField(
            model_name='productvideo',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_product_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='product_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_videos', to='vendors.vendorprofile'),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
