# Generated by Django 5.2.14 on 2026-08-12 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_productvideocomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCommerceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('sponsored', 'Sponsored')], db_index=True, max_length=20)),
                ('source_id', models.PositiveBigIntegerField(db_index=True)),
                ('event_type', models.CharField(choices=[('video_impression', 'Video impression'), ('video_play', 'Video play'), ('video_pause', 'Video pause'), ('video_25', 'Video 25%'), ('video_50', 'Video 50%'), ('video_75', 'Video 75%'), ('video_complete', 'Video complete'), ('video_unmute', 'Video unmute'), ('video_mute', 'Video mute'), ('video_cta_click', 'Video CTA click')], db_index=True, max_length=30)),
                ('owner_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('owner_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('campaign_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(max_length=160, unique=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_commerce_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'source_id', 'event_type'], name='products_vi_content_766225_idx'), models.Index(fields=['event_type', '-created_at'], name='products_vi_event_t_a20816_idx')],
            },
        ),
    ]
