# Generated by Django 5.2.14 on 2026-08-12 12:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_videocommerceevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCommerceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.CharField(choices=[('service', 'Service'), ('sponsored', 'Sponsored')], db_index=True, max_length=20)),
                ('source_id', models.PositiveBigIntegerField(db_index=True)),
                ('body', models.TextField(max_length=1500)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_video_commerce_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_commerce_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'source_id', 'is_visible', '-created_at'], name='products_vi_content_4c7ad1_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'source_id', 'user'), name='unique_video_commerce_comment_user')],
            },
        ),
        migrations.CreateModel(
            name='VideoCommerceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.CharField(choices=[('service', 'Service'), ('sponsored', 'Sponsored')], db_index=True, max_length=20)),
                ('source_id', models.PositiveBigIntegerField(db_index=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_commerce_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'source_id'], name='products_vi_content_b93482_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'source_id', 'user'), name='unique_video_commerce_rating_user')],
            },
        ),
    ]
