# Generated by Django 5.2.14 on 2026-08-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_videocommercecomment_videocommercerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvideo',
            name='youtube_video_id',
            field=models.CharField(blank=True, db_index=True, help_text='YouTube video ID returned by the YouTube API.', max_length=32),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='youtube_visibility',
            field=models.CharField(choices=[('unlisted', 'Unlisted'), ('public', 'Public')], default='unlisted', max_length=16),
        ),
    ]
